### ISSUE TITLE
字符编码可能要修正一下, 出现乱码

### ISSUE THREAD

**Issue by xueqing0622** [yolain/ComfyUI-Easy-Use#1]
字符编码可能要修正一下, 出现乱码
![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/114840118/03ce51b9-4d72-4ceb-a760-3d89eff52b1d)

**Comment by yolain** [comment]
你更换下自己下载的大模型就可以，是因为示例的工作流我把模型放在了中文文件夹路径下。

**Comment by yolain** [comment]
好的，谢谢！👌🏻我调整一下示例

**Comment by xueqing0622** [comment]
你这个从头到脚pipe的运用 , 真的很喜欢, 赞!
