### ISSUE TITLE
虽说pipe用到底很爽, 但是藏了太多的常用输入输出, 感觉用了还是不那么顺手

### ISSUE THREAD

**Issue by xueqing0622** [yolain/ComfyUI-Easy-Use#10]
虽说pipe用到底很爽, 但是藏了太多的常用输入输出, 感觉用了还是不那么顺手,

**Comment by yolain** [comment]
![Uploading ComfyUI---Google-Chrome-2023_12_14-21_10_49.png…]()
习惯就好，也没有整天再处理工作流啊，肯定是为了方便跑图跟看着舒服。新push的那个我加了个image_to_latent，可以这样使。

**Comment by yolain** [comment]
![1](https://github.com/yolain/ComfyUI-Easy-Use/assets/73304135/988ebbb7-50b4-4e98-bee5-c59e37603179)
习惯就好，也没有整天再处理工作流啊，肯定是为了方便跑图跟看着舒服。新push的那个我加了个image_to_latent，可以这样使。

**Comment by yolain** [comment]
animatediff 我不太会玩，你试试看 按新Push的 去调整看工作流是否有问题

**Comment by xueqing0622** [comment]
![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/114840118/26d04cb0-023b-4e3c-abd4-c9e8d3f3d82b)
这个值是一个渐进的, 作者说0.825是最像prompt is more important的

**Comment by xueqing0622** [comment]
他是从0通过每一步慢慢到最后这个值的过程, 所以很顺滑  
这个也可以用在动画里

**Comment by xueqing0622** [comment]
https://githubfast.com/Kosinkadink/ComfyUI-Advanced-ControlNet/issues/24
你可以看看这里, 我找了很久sd这个功能怎么在comfyui实现, 这个作者最后帮我解答我才理解了

**Comment by xueqing0622** [comment]
![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/114840118/6ac6440a-b807-4773-a554-ad597189eb85)

**Comment by yolain** [comment]
嗯嗯，有空看看。

**Comment by solomon-s2020** [comment]
> ![1](https://private-user-images.githubusercontent.com/73304135/290529135-988ebbb7-50b4-4e98-bee5-c59e37603179.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5MTA5MTAsIm5iZiI6MTcwMjkxMDYxMCwicGF0aCI6Ii83MzMwNDEzNS8yOTA1MjkxMzUtOTg4ZWJiYjctNTBiNC00ZTk4LWJlZTUtYzU5ZTM3NjAzMTc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDE0NDMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4OGE0YjQ1MjQ2MTBhOTdiOGI0ZTBmMWFhNjgyMjUzYzg1NGMzYjIxNTE0MjQwOGQyOGMwNzZmZjg5YzczZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P4dxEb71c6DbxwmYF4Ao1YoqpQRH0aSvuX6X8SjYHyQ) 习惯就好，也没有整天再处理工作流啊，肯定是为了方便跑图跟看着舒服。新push的那个我加了个image_to_latent，可以这样使。

请问这是什么主题？节点框还挺好看。

**Comment by yolain** [comment]
> > ![1](https://private-user-images.githubusercontent.com/73304135/290529135-988ebbb7-50b4-4e98-bee5-c59e37603179.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5MTA5MTAsIm5iZiI6MTcwMjkxMDYxMCwicGF0aCI6Ii83MzMwNDEzNS8yOTA1MjkxMzUtOTg4ZWJiYjctNTBiNC00ZTk4LWJlZTUtYzU5ZTM3NjAzMTc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDE0NDMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4OGE0YjQ1MjQ2MTBhOTdiOGI0ZTBmMWFhNjgyMjUzYzg1NGMzYjIxNTE0MjQwOGQyOGMwNzZmZjg5YzczZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P4dxEb71c6DbxwmYF4Ao1YoqpQRH0aSvuX6X8SjYHyQ) 习惯就好，也没有整天再处理工作流啊，肯定是为了方便跑图跟看着舒服。新push的那个我加了个image_to_latent，可以这样使。
> 
> 
> 
> 请问这是什么主题？节点框还挺好看。

我修改的主题，后面我看下 可以的话放这个包里
