### ISSUE TITLE
additional inpaint patch differential diffusion do not perform as well as standalone plugins

### ISSUE THREAD

**Issue by whmc76** [yolain/ComfyUI-Easy-Use#104]
![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/129386342/10035ba1-d166-4ad1-a9c8-966a50e35974)

![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/129386342/1a60585a-f89a-4a30-a0fb-33accd0bcafa)

**Comment by whmc76** [comment]
不过。。也许是使用的不对？

**Comment by yolain** [comment]
fooocus inpaint的我没有让它走dd。我试试fooocus inpaint能不能行

**Comment by whmc76** [comment]
主要就是觉得这两个一起用疗效好哈哈 等待大佬验证
