### ISSUE TITLE
自定义json放在styles底下后，在提示词选择中还是只有Fooocus的样式json

### ISSUE THREAD

**Issue by Gileanxxx** [yolain/ComfyUI-Easy-Use#107]
自定义json放在styles底下后，在提示词选择中还是只有Fooocus的样式json，是我使用错误吗?

**Comment by yolain** [comment]
命名需要有_styles.json

**Comment by Gileanxxx** [comment]
谢谢，问题已经解决。
另外目前似乎自定义的提示词无法与默认提示词重叠勾选。不知道有没有办法解决
