### ISSUE TITLE
请支持FaceDetailer

### ISSUE THREAD

**Issue by cybercall** [yolain/ComfyUI-Easy-Use#12]
请支持FaceDetailer的连接

**Comment by yolain** [comment]
> 请支持FaceDetailer的连接

包里有细节修复的节点，或者你用 easy pipe out 出去

**Comment by cybercall** [comment]
找到了，谢谢~
另外，个人觉得pipeOut里的pos和neg字段的命名，很让人困惑，建议改名回positive和negative

**Comment by yolain** [comment]
> 找到了，谢谢~
> 
> 另外，个人觉得pipeOut里的pos和neg字段的命名，很让人困惑，建议改名回positive和negative

参考老外原版的，也很多包都这么缩写.没啥好困惑的 🤔️颜色也能分辨出来
