### ISSUE TITLE
Easy Apply IPAdapter (Advanced) error when use_tiled is set to false

### ISSUE THREAD

**Issue by ManOrMonster** [yolain/ComfyUI-Easy-Use#123]
I can't get Easy Apply IPAdapter (Advanced) to work without setting "use_tiled" to true. I get `Exception: Images or Embeds are required`

It works if "use_tiled" is set to true, but then it tiles even when a prepped square image is sent to it.

![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/3925151/9daec819-5e57-413a-bd13-914db81539b2)

```
[EasyUse] easy ipadapterApply: Using SD1.5\CLIP-ViT-H-14-laion2B-s32B-b79K.safetensors
[EasyUse] easy ipadapterApply: Using IPAdapter\ip-adapter-plus_sdxl_vit-h.safetensors
!!! Exception during processing !!!
Traceback (most recent call last):
  File "C:\stable-diffusion\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\stable-diffusion\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\stable-diffusion\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\stable-diffusion\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py", line 2357, in apply
    model, = cls().apply_ipadapter(model, ipadapter, image, weight, weight_type, start_at, end_at, combine_embeds=combine_embeds, weight_faceidv2=weight_faceidv2, image_negative=image_negative, clip_vision=clip_vision, attn_mask=attn_mask, insightface=None, embeds_scaling=embeds_scaling)
  File "C:\stable-diffusion\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 637, in apply_ipadapter
    return (ipadapter_execute(model.clone(), ipadapter_model, clip_vision, **ipa_args), )
  File "C:\stable-diffusion\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 254, in ipadapter_execute
    raise Exception("Images or Embeds are required")
Exception: Images or Embeds are required
```

**Comment by yolain** [comment]
Maybe it's because of the changes over at ipadapter's new commit.

**Comment by ManOrMonster** [comment]
Oops, looks like I spoke too soon.

It is indeed working now, but when passing a non-square image to the node, it's cropping it into a square, which kind of defeats the purpose of tiling.

In the image below, the bottom image is the output of "tiles" from the advanced node. Note that the image passed in is not square:

![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/3925151/ce0223cf-0ce7-466c-a387-c407536dbdb8)

**Comment by ManOrMonster** [comment]
Never mind. This issue is definitely with IPAdapter Plus nodes:

![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/3925151/931fa1bc-0c02-452c-9001-93087b198997)
