### ISSUE TITLE
 cleanGpuUsed可以释放GPU资源的使用吗？

### ISSUE THREAD

**Issue by solomon-s2020** [yolain/ComfyUI-Easy-Use#124]
如题，加载过了模型一直会占用GPU的使用， cleanGpuUsed此节点可以释放GPU的资源吗，试了GPU还是会一直占用。

**Comment by yolain** [comment]
只能清除暂存区的，大模型的占用清不掉的。这个节点目前没啥太大作用呢，python只有这么一个方法，但是在comfy中没啥用，目前只有重启进程才会释放

**Comment by solomon-s2020** [comment]
ComfyUI-MuseV这个插件，运行完成后，能把加载的模型占用都释放掉。 GPU恢复到初始状态。

**Comment by yolain** [comment]
> ComfyUI-MuseV这个插件，运行完成后，能把加载的模型占用都释放掉。 GPU恢复到初始状态。

好的，我有空看下

**Comment by solomon-s2020** [comment]
哈哈，大佬效率这么快，看完了。

**Comment by yolain** [comment]
我找到办法了，原来comfyui有预留个方法的，以前居然没看到。

**Comment by solomon-s2020** [comment]
> 我找到办法了，原来comfyui有预留个方法的，以前居然没看到。

大佬真牛

**Comment by solomon-s2020** [comment]
> 我找到办法了，原来comfyui有预留个方法的，以前居然没看到。

刚更新试了，确实有效果，哈哈，太牛了。

**Comment by alpttex19** [comment]
> 我找到办法了，原来comfyui有预留个方法的，以前居然没看到。

什么方法呀大佬？

**Comment by yolain** [comment]
> > 我找到办法了，原来comfyui有预留个方法的，以前居然没看到。
> 
> 
> 
> 什么方法呀大佬？

很早就写easyuse里了。manager新版也有这个功能。

**Comment by hewenzhuo1** [comment]
可是我用了没有反应列
