### ISSUE TITLE
Some issues with usage habits

### ISSUE THREAD

**Issue by alex13by** [yolain/ComfyUI-Easy-Use#128]
I changed the shortcut menu of ipadapter, which makes it inconvenient for me. Is there any way to prevent easy-use from changing the shortcut menu of other plug-ins?
![1](https://github.com/yolain/ComfyUI-Easy-Use/assets/121482598/11304dbb-8734-45fa-b813-6f9cc690d9df)
![2](https://github.com/yolain/ComfyUI-Easy-Use/assets/121482598/10a7eefa-38f4-4aa9-9ffc-40744bc71a2a)
want to use the original settings of the iadapter plug-in, but easy-use is too good in other aspects and I don’t want to discard it. It would be perfect if it could take into account such needs.

**Comment by yolain** [comment]
That's from comfyui's default connection suggestion. Maybe if you use the original ipadapter node more, it should correlate. I only make connection suggestions for easyuse related nodes.

**Comment by yolain** [comment]
By the way, you can increase the "number of node suggestions" in the settings
