### ISSUE TITLE
请问大佬这个可以加个功能不

### ISSUE THREAD

**Issue by 1to3fall5** [yolain/ComfyUI-Easy-Use#143]
![cc](https://github.com/yolain/ComfyUI-Easy-Use/assets/29686377/2dedb706-f0bf-4f39-b32b-1fe82a4d9ebe)
请问有没有方法把这个按钮做成设置随机种子并queue prompt，相当于一个roll的按钮，按完直接换种子重跑了，然后按内置的queue prompt是种子还是fix的。因为我发现我用的时候逻辑是点一下换种子然后再点一下queue。

**Comment by yolain** [comment]
可以

**Comment by 1to3fall5** [comment]
![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/29686377/c52570f0-d9f9-473c-8952-97de035f5b10)
感谢，期待更新，那能不能再加一个feature request哈哈，就是输出多张的时候图像预览这里有数字可以切换图片，有没有什么方法获取当前查看图片的index，这样就变相的实现了image chooser 节点的功能。我看到刚刚把image chooser集成了，但每次都需要点一下，在有些渲染多图的工作流中有些麻烦。例如如果有一个渲四张小图再高清放大的工作流，就可在预览的时候调到想放大那一张，再点一下queue prompt，在固定种子的情况下就会直接跑放大的流程了。

**Comment by yolain** [comment]
之前说的那个有更过了。
preview_latent这个应该是实现不了，所以才会有chooser这样的方案。 comfy不变prompt它不会走队列任务，变了prompt它就又要重新diffusion了。所以即便能取到图片索引值也不方便

**Comment by 1to3fall5** [comment]
哇感谢，用上了，好用！关于选择图像下面是我用其他的节点实现的，可能会清楚一些，就是想把中间这个选择图像的组集成到easyksampler的preview中
![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/29686377/35c7dcd4-404e-4f05-a451-aae98624c16c)

**Comment by yolain** [comment]
不行呢， 一定得有一个节点来过渡才可以。

**Comment by 1to3fall5** [comment]
了解，谢咯
