### ISSUE TITLE
feature request - nvidia AYS scheduler support

### ISSUE THREAD

**Issue by whmc76** [yolain/ComfyUI-Easy-Use#146]
as title, it is amazing
comfyui官方刚更新了支持Align Your Steps

**Comment by yolain** [comment]
看了示例效果不错，😄我试试。

**Comment by yolain** [comment]
> is that possible to set denoise ?

Wait a minute, I'm changing it.

**Comment by whmc76** [comment]
666 我看他不仅是没有降噪 还设置了一个最低10步得限制 不知道低于这个会怎样

**Comment by yolain** [comment]
> 666 我看他不仅是没有降噪 还设置了一个最低10步得限制 不知道低于这个会怎样

没有吧。哪里看到的，应该是步数越少效果越好感觉。

**Comment by yolain** [comment]
应该是说反了吧，比较适合 lcm 、lighting 跟 蒸馏的那些。步数大的反而效果很差。

**Comment by whmc76** [comment]
就comfyui自带那个ays调度器 最小就拉到10

**Comment by yolain** [comment]
> 就comfyui自带那个ays调度器 最小就拉到10

还真的是，我测试看看。难道数值小于10效果不行吗😂我就开头试了一下一样 就没去看自带那个了。 奇怪了，下午我还lcm测了 steps才开了5，效果有比原本要好。怪了

**Comment by whmc76** [comment]
!!! Exception during processing!!! Please update your ComfyUI
Traceback (most recent call last):
  File "E:\IMAGE\ComfyUI-base-py311-0329\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py", line 4155, in process_sample_state
    sigmas, = AlignYourStepsScheduler().get_sigmas(model_type.upper(), steps)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AlignYourStepsScheduler.get_sigmas() missing 1 required positional argument: 'denoise'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\IMAGE\ComfyUI-base-py311-0329\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base-py311-0329\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base-py311-0329\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base-py311-0329\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py", line 4402, in run
    return samplerFull().run(pipe, None, None, None, None, None, image_output, link_id, save_prefix,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base-py311-0329\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py", line 4368, in run
    return process_sample_state(pipe, samp_model, samp_clip, samp_samples, samp_vae, samp_seed, samp_positive, samp_negative, steps, start_step, last_step, cfg, sampler_name, scheduler, denoise, image_output, link_id, save_prefix, tile_size, prompt, extra_pnginfo, my_unique_id, preview_latent, force_full_denoise, disable_noise, samp_custom)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base-py311-0329\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py", line 4157, in process_sample_state
    raise Exception("Please update your ComfyUI")
Exception: Please update your ComfyUI

**Comment by whmc76** [comment]
不知道为啥不能用了

**Comment by whmc76** [comment]
好像是官方的sigma更新了一个denoise

**Comment by yolain** [comment]
> 好像是官方的sigma更新了一个denoise

那很好，我明天调整下
