### ISSUE TITLE
生成第二幅图的时候报错

### ISSUE THREAD

**Issue by ccculing** [yolain/ComfyUI-Easy-Use#15]
![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/103477836/082a4bb0-f450-40ac-babc-436b85c492c0)
生成第一张图没什么问题，什么都不改，生成第二张图的时候报错
![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/103477836/a57f503b-1375-4408-9b5a-cfad4e80a72b)
直接git clone的最新的也这样

**Comment by yolain** [comment]
d7449769f384ba6a6c68521e5d4428c8920e8fe4 修复了。
