### ISSUE TITLE
BUG 风格提示词预览图片会根据鼠标缩放偏移

### ISSUE THREAD

**Issue by hahajaja** [yolain/ComfyUI-Easy-Use#156]
![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/23209894/bf80d9fe-fda6-44b9-9cda-c43ae5168475)

**Comment by yolain** [comment]
这不好解决，不太影响使用呢。

**Comment by hahajaja** [comment]
大佬有办法自定义一个自己的风格提示词节点吗，我想和fooocus隔开不想加到fooocus_styles.json里面
