### ISSUE TITLE
启动的时候报错，但是不影响使用

### ISSUE THREAD

**Issue by ccculing** [yolain/ComfyUI-Easy-Use#16]
是我缺少什么节点，还是什么其他原因呢？
![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/103477836/ac05f26c-049e-4d54-9a94-7fb894fb4d90)

**Comment by yolain** [comment]
你之前没有用过脸部修复那块吧。应该是少了Comfy-Impact-pack 。models  缺少 ultralytics

**Comment by ccculing** [comment]
谢谢，安装了Comfy-Impact-pack就好了
