### ISSUE TITLE
'SDXLClipModel' object has no attribute 'clip_layer'

### ISSUE THREAD

**Issue by the2ndface** [yolain/ComfyUI-Easy-Use#165]
内核和扩展都已经更新到最新版本，使用扩展的默认工作流，云端环境，貌似和torch有关系？
`File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")`
![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/12891537/f5d386cc-ea15-4c08-8d2b-30e20ad90a98)

**Comment by yolain** [comment]
可能是云端取不到内核版本号。我更新下去掉版本判断吧，一个月前官方的修改了，现在大家基本都用比较新的版本了。

**Comment by the2ndface** [comment]
大佬666，已经可以了，才发现我在B站竟然已经关注过大佬了，然而并不是因为这个扩展关注的。。

**Comment by yolain** [comment]
> 大佬666，已经可以了，才发现我在B站竟然已经关注过大佬了，然而并不是因为这个扩展关注的。。

哈哈，感谢关注!
