### ISSUE TITLE
如何在一幅图里面针对不同region 应用不同的lora

### ISSUE THREAD

**Issue by whmc76** [yolain/ComfyUI-Easy-Use#168]
以前我一直以为这个非常基础，直到最近好像只有impact pack里面有个regional prompt 但是用起来非常之复杂

**Comment by whmc76** [comment]
我看到你在非常早期的版本就加入了 latentcompositemaskedwithcond 但是感觉这个是用来做regional text prompt的 这个能针对lora分区应用嘛 做一左一右两个人的

**Comment by yolain** [comment]
没呢，我没有有做regional prompt类似的功能。
