### ISSUE TITLE
怎么安装ComfyUI-Easy-Use后在UI中只找见ComfyUI Easy Padding?

### ISSUE THREAD

**Issue by freemde23** [yolain/ComfyUI-Easy-Use#17]
![2024-01-01_173123](https://github.com/yolain/ComfyUI-Easy-Use/assets/122530501/de05e323-18cf-4d7c-b568-b2f15af81e06)

**Comment by yolain** [comment]
重启下comfyUI看下。包没有运行？右键菜单中是否有EasyUse
