### ISSUE TITLE
feature request - auto translate prompt

### ISSUE THREAD

**Issue by whmc76** [yolain/ComfyUI-Easy-Use#172]
经常想复制一大段文字进来又懒得翻译哈哈哈，mixlab有这个功能但是启动太慢了

**Comment by yolain** [comment]
有空看下呢，我还没用过，记得好像是下个llama模型放本地推理的吧，有看到你经常在用，哈哈。不造会不会很占用显存

**Comment by whmc76** [comment]
你想多了，mixlab用的api 我觉得不费什么事哈哈



---Original---
From: ***@***.***&gt;
Date: Fri, May 17, 2024 15:04 PM
To: ***@***.***&gt;;
Cc: "Cyber Dick ***@***.******@***.***&gt;;
Subject: Re: [yolain/ComfyUI-Easy-Use] feature request - auto translate prompt(Issue #172)




 
有空看下呢，我还没用过，记得好像是下个llama模型放本地推理的吧，有看到你经常在用，哈哈。不造会不会很占用显存

**Comment by yolain** [comment]
是走的这个 Helsinki-NLP/opus-mt-zh-en，有空写个
