### ISSUE TITLE
Styles Selector 节点在画布缩放后, 标签的提示图距离显示不正常.

### ISSUE THREAD

**Issue by xiexiaobo135** [yolain/ComfyUI-Easy-Use#176]
https://github.com/yolain/ComfyUI-Easy-Use/blob/24526623fbcefbef6fc8ca287cd460fba1d2d5de/web/js/easy/easySelector.js#L97

>> 加上缩放比例进行校正下好些:     
img.style.left =  x/app.canvas.ds.scale+"px";
img.style.top =  y/app.canvas.ds.scale+"px";

**Comment by yolain** [comment]
thanks

**Comment by xiexiaobo135** [comment]
感谢花时间修复~
