### ISSUE TITLE
XY Plot 节点是否未对随机种子进行固定

### ISSUE THREAD

**Issue by xiexiaobo135** [yolain/ComfyUI-Easy-Use#177]
测试A:
![demo1](https://github.com/yolain/ComfyUI-Easy-Use/assets/7458194/6de0d138-8c6d-4d29-bb9d-3ce5e8af6768)

测试B:
![demo2](https://github.com/yolain/ComfyUI-Easy-Use/assets/7458194/a2bf7613-050c-4a80-afa2-2498517cce0a)

这是https://github.com/yolain/ComfyUI-Yolain-Workflows中的 base下的 1-7 XY对比示例.
修改了Input X轴 的 batch_count 为1后, 想看看Y轴不同 step 下的区别, 结果显示的效果是随机了种子的对比图, 图片结果每次都不一样, 可见种子并未固定.
上面两个测试A和B中, A1和B1, A2和B3它们均种子一样参数相同, 结果却大相径庭. 无法体现 step 参数的变化形态

**Comment by yolain** [comment]
wildcards没fixed吧

**Comment by xiexiaobo135** [comment]
感觉也就那个seed差距很大, 其它的没那么大, 可能是个别问题吧, 但使用KSampler Progress (Inspire) 这个节点分析时, 看这些步数差距又不大, 但因为没办法还原到一致, 出的图不一样也不好判断了, 很奇怪. 可能是缓存问题吧, 这个step的XY场景一般也没啥大用, 我关了吧
