### ISSUE TITLE
出现干扰其它插件的正常工作了

### ISSUE THREAD

**Issue by xiexiaobo135** [yolain/ComfyUI-Easy-Use#186]
您的插件造成了 ComfyUI_tinyterraNodes 插件的节点使用异常了, 我之前跑他那边提交问题了, 具体现象描述请查看如下提交的地址: 

https://github.com/TinyTerra/ComfyUI_tinyterraNodes/issues/117

python好多年没摸了, 忘光了没法帮你找bug了, 请您抽空看下, 代码逻辑的隔离性是否合理.🙂

**Comment by yolain** [comment]
不造他在seed那边写了啥，默认的kSampler都正常，我排查下看看。 这边我在初始的时候 将 control_after_generate 改成before了，默认ComfyUI有bug，显示不对（如果是widget_control设置时before的时候）。

**Comment by yolain** [comment]
https://github.com/TinyTerra/ComfyUI_tinyterraNodes/blob/6375107b02a58e63d8ed80a94141439d390e6b54/js/ttNwidgets.js#L13

需要增加下对 control_before_generate的判断

```javascript
// else if (w.name === "control_after_generate") {
else if (w.name === "control_after_generate" || w.name === "control_before_generate") {
```

**Comment by xiexiaobo135** [comment]
感谢回复, 修改后已能正常工作.
