### ISSUE TITLE
Pipe信息传递的问题

### ISSUE THREAD

**Issue by cardenluo** [yolain/ComfyUI-Easy-Use#190]
![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/133877069/814b13ef-5735-4413-be59-8d32a1f83fbd)
经过测试发现，采样器无法把模型微调后的信息编入到pipe中进行传递，但是可以通过节点束输入或者编辑将模型微调后的信息编入。
是否逻辑就是这样设置的，还是说是个bug？我还没测试其他采样器。是否其他都是这样？模型信息只能通过节点束输入或者节点束编辑编入pipe中进行传递。

**Comment by cardenluo** [comment]
![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/133877069/ceb6246f-e03a-4525-8c64-b53667813400)
AD会比较明显

**Comment by yolain** [comment]
逻辑就是这样设置的，应该改成这样有一两个月了，覆盖掉有很多衍生问题。
采样器输出的还是默认pipe当中的model，并联的model不会加入到采样器的输出。

**Comment by cardenluo** [comment]
原来如此，谢谢
