### ISSUE TITLE
风格选择器逻辑问题

### ISSUE THREAD

**Issue by liulsg** [yolain/ComfyUI-Easy-Use#194]
问题：
1.“风格选择器”左侧如果链接其他文本节点，则文本节点输出的提示词会添加到“风格选择器”提示词第一个提示词后面，且没有“，”分割
2.自定义风格json文件必须附带“fooocus_styles”前缀，否则识别不了
3.如果添加了自定义json文件，当通过“风格选择器”切换时（已选择了自定义json中的某个风格），选择新的提示词，输出提示词会报错

**Comment by yolain** [comment]
1.是参考原版fooocus styles逻辑的，左侧描述的主要提示词是穿插在风格提示词设定的某个位置上
2.带_styles就可以
3.应该是bug，有时间我修复一下
