### ISSUE TITLE
咨询重绘节点

### ISSUE THREAD

**Issue by liulsg** [yolain/ComfyUI-Easy-Use#197]
目前easy use有三种重绘节点方式

1.Easy Apply Inpaint（最新添加，包含了brushnet、fooocus重绘、常规重绘......）
2.brushnet重绘节点、fooocus重绘节点.......（单独的节点）
3.简易K采样器 (内补)   （采样节点重绘）

这三种目前不是重复实现的功能吗？

**Comment by yolain** [comment]
更方便使用而已，推荐使用前两种吧。这两天把Brushnet也整合进来了，之前是直接调用原作者包里的类，因为作者也常有改动，我担心后续会因为版本不一导致报错问题，目前这个版本我感觉已经很稳定了，索性还是合进来吧。

1. Easy Apply Inpaint 
可以在一个节点上选择不同的重绘模式，初次使用，不需要选择模型文件，自动按默认配置从Hug下载的（不开代理也会走国内镜像下载）
2. brushnet、powerpaint、fooocus 单独的节点
需要自行选择模型文件
3. kSamplingInpainting
使用的都是默认参数，重绘模式多了，设计上看起来不是太合理了，然后image和mask要分去两个节点，容易连错或忘了连。
