### ISSUE TITLE
虽然有点占空间, 但是还是建议把vae, clip, positive, negative, 的output,input节点跟pipe样拉出来,不然和其他节点共用的很难

### ISSUE THREAD

**Issue by xueqing0622** [yolain/ComfyUI-Easy-Use#2]
虽然有点占空间, 但是还是建议把vae, clip, positive, negative, 的output,input节点跟pipe样拉出来,不然和其他节点共用的很难

**Comment by yolain** [comment]
可以配合terratinynodes有pipein，pipeout和pipeedit，是可以比较方便地实现共用的，如果需求上要使用更完整的就使用它原版的那个。

**Comment by xueqing0622** [comment]
![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/114840118/28bf7264-3096-4970-a442-ea627400508b)
如果不加的话,自己拉节点 感觉更乱,

**Comment by xueqing0622** [comment]
你这个是跟ttn的pipeout pipein兼容的就好, 也很好用啦

**Comment by xueqing0622** [comment]
我关掉这个issues了, 你最好这个pipe的运用跟广大水友说一下,很多人估计不知道怎么用
这个有点重要

**Comment by xueqing0622** [comment]
![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/114840118/c2f77dea-f0c1-4ccc-97cd-3a9f6e7fa485)
你可以拿controlnet这个实例说一下pipeEdit, 不然很多小伙伴不知道, 而且你collapse(最小化)了,有些人更不懂了
