### ISSUE TITLE
为何每次启动都会安装？而且会覆盖诸如inference-gpu 等依赖？

### ISSUE THREAD

**Issue by Pythonpa** [yolain/ComfyUI-Easy-Use#209]
hello，作者您好。
请问下为何每次启动comfyui，这个easy-use的节点都会安装一次依赖，而且是赶在manager的security scan运行之前？
我卸载掉这个easy-use节点之后，就不会出现重新安装一些依赖节点的问题了。

**Comment by yolain** [comment]
没有吧，没有强制初始化安装依赖。

**Comment by Pythonpa** [comment]
ok ,那可能是我没有排查对，我再排查下吧，辛苦了，祝安好。

**Comment by xxskkk** [comment]
@Pythonpa  请问您的问题解决了吗？我也出现了类似的问题，每次打开comfyui就会重新安装一遍easyuse所需依赖。

**Comment by Pythonpa** [comment]
> @Pythonpa 请问您的问题解决了吗？我也出现了类似的问题，每次打开comfyui就会重新安装一遍easyuse所需依赖。

解决了，不是Easy-use节点的问题，其他节点问题，但是忘了是哪个了，你一个个删除卸载去排除吧。

**Comment by Pythonpa** [comment]
> @Pythonpa 请问您的问题解决了吗？我也出现了类似的问题，每次打开comfyui就会重新安装一遍easyuse所需依赖。

又仔细排查了下，你确认下你的插件节点里是不是安装有ZHO作者的[ComfyUI-YoloWorld-EfficientSAM](https://github.com/ZHO-ZHO-ZHO/ComfyUI-YoloWorld-EfficientSAM)这个节点，如果是的话，可能是里面的inference-gpu版本限制太死的问题。我直接卸载掉了这个节点，换其他同等替代了。未再出现这个问题。

**Comment by Pythonpa** [comment]
> @Pythonpa 请问您的问题解决了吗？我也出现了类似的问题，每次打开comfyui就会重新安装一遍easyuse所需依赖。

又仔细排查了下，你确认下你的插件节点里是不是安装有ZHO作者的[ComfyUI-YoloWorld-EfficientSAM](https://github.com/ZHO-ZHO-ZHO/ComfyUI-YoloWorld-EfficientSAM)这个节点，如果是的话，可能是里面的inference-gpu版本限制太死的问题。我直接卸载掉了这个节点，换其他同等替代了。未再出现这个问题。

**Comment by yolain** [comment]
> > @Pythonpa 请问您的问题解决了吗？我也出现了类似的问题，每次打开comfyui就会重新安装一遍easyuse所需依赖。
> 
> 又仔细排查了下，你确认下你的插件节点里是不是安装有ZHO作者的[ComfyUI-YoloWorld-EfficientSAM](https://github.com/ZHO-ZHO-ZHO/ComfyUI-YoloWorld-EfficientSAM)这个节点，如果是的话，可能是里面的inference-gpu版本限制太死的问题。我直接卸载掉了这个节点，换其他同等替代了。未再出现这个问题。

我也有zho大佬的yoloworld, 可能早先的版本不会有这问题吧，蛮久没更新了。

**Comment by xxskkk** [comment]
非常感谢大佬们的回答，听了您的建议我又自己排查了一下，问题暂时解决了。我从Easy-use节点的依赖文件中分别对所需依赖单个禁用。当禁用 sentencepiece==0.2.0时，我的comfyui就可以不安装其他依赖正常启动。但是我一个一个翻阅我所安装的节点的依赖文件暂时没有发现sentencepiece要求，所以我就暂时只能将Easy-use节点依赖文件的sentencepiece==0.2.0禁用。

**Comment by yolain** [comment]
> 非常感谢大佬们的回答，听了您的建议我又自己排查了一下，问题暂时解决了。我从Easy-use节点的依赖文件中分别对所需依赖单个禁用。当禁用 sentencepiece==0.2.0时，我的comfyui就可以不安装其他依赖正常启动。但是我一个一个翻阅我所安装的节点的依赖文件暂时没有发现sentencepiece要求，所以我就暂时只能将Easy-use节点依赖文件的sentencepiece==0.2.0禁用。

提示词自动翻译那边需要 sentencepiece 这个依赖，之前配置云平台的时候，发现运行时会显示缺失所以加到列表中了。

**Comment by yxf551** [comment]
我是同样的问题，且出现红字告警的提示非常快得就跳到正常启动窗口了，用截屏软件才发现原因是sentencepiece版本低于0.2.0。请问作者只有禁用它才可以么？有没有其他的解决方法。谢谢。

**Comment by yxf551** [comment]
我是同样的问题，且出现红字告警的提示非常快地就跳到正常启动窗口了，用截屏软件才发现原因是sentencepiece版本低于0.2.0。请问作者只有禁用它才可以么？有没有其他的解决方法。谢谢。

**Comment by yolain** [comment]
> 

我去掉了依赖文件里sentencepiece的强制版本了。
