### ISSUE TITLE
我下载了插件但是不能使用

### ISSUE THREAD

**Issue by HDCSgit** [yolain/ComfyUI-Easy-Use#21]
![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/101379290/a54dd268-8209-4815-8538-754f548c023e)
![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/101379290/da7c828a-4666-4dd0-a229-b4f075e27eab)

**Comment by HDCSgit** [comment]
![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/101379290/ea381267-11e5-4374-869e-c174010de5e5)
我关闭了另外两个插件仍然存在问题，我原本以为是冲突，看样子不是。是缺少什么文件吗

**Comment by yolain** [comment]
不是太清楚呢。包之间一般是不太会存在加载时冲突的情况，你载入错误的那几个包我都有， 看你这个log  其他包也出现这种情况。有没有可能是下载的时候 网络卡了没下全。看一下log前面还有没有其他报错信息
