### ISSUE TITLE
需求更新适配cosxl ipadapter

### ISSUE THREAD

**Issue by whmc76** [yolain/ComfyUI-Easy-Use#210]
cubic刚更新的 我尝试在easy use去使用但好像还不能生效

**Comment by yolain** [comment]
测试了，有生效。
预采样器自定义修改模型需要 pipe in 或者pipe edit 进，参数太多 没有在kSampler那边维护，所以model直接连到kSampler起不了作用。

**Comment by whmc76** [comment]
got it



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月13日(周四) 晚上7:51
收件人: ***@***.***&gt;;
抄送: "Cyber Dick ***@***.******@***.***&gt;;
主题: Re: [yolain/ComfyUI-Easy-Use] 需求更新适配cosxl ipadapter (Issue #210)




 
测试了，有生效。
 预采样器自定义修改模型需要 pipe in 或者pipe edit 进，参数太多 没有在kSampler那边维护，所以model直接连到kSampler起不了作用。
