### ISSUE TITLE
使用SD3模型提示：'NoneType' object has no attribute 'float'

### ISSUE THREAD

**Issue by yincangshiwei** [yolain/ComfyUI-Easy-Use#214]
工作流：
![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/8185843/2cdc259a-35f4-4a28-9d34-9dea0358031d)
错误：
![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/8185843/47f4e857-5495-4ef6-939f-5b0c488acd53)

**Comment by yincangshiwei** [comment]
官方工作流使用是没问题。可否提供一下EasyUse里面的使用方式。

**Comment by yolain** [comment]
clip_skip 只能为0

**Comment by yincangshiwei** [comment]
> t5xxl版模型的 clip_skip 只能为0

哦哦，好的，谢谢！
