### ISSUE TITLE
简易加载器-每批生成数量-如何获得单张图的种子

### ISSUE THREAD

**Issue by letterk** [yolain/ComfyUI-Easy-Use#23]
每批生成数量打包生成比一批一张速度快20-30%, 但是有个缺点, 比如这一批是10张, 我把图片丢到comfyui里, 他只会显示这一批的种子, 并不能对应具体某张图的种子. 这样就没法复现了

**Comment by yolain** [comment]
官方默认的流程 好像也是这样的。这些图都是同一个种子值。

**Comment by letterk** [comment]
怎么会同一个种子生成不同的图呢, 那种子就不具备唯一性了啊. 官方流程每批一张, 多批生图, 出来的种子就是和图片对应的

**Comment by yolain** [comment]
> 怎么会同一个种子生成不同的图呢, 那种子就不具备唯一性了啊. 官方流程每批一张, 多批生图, 出来的种子就是和图片对应的

你自己试试看呢，官方流程里多批生成出来的图 随机种都是同一个的。我看了prepare noise那块的代码了，它大体是根据批次大小生成了一个随机矩阵tensor的噪声，假如批次为4那么 四个不同的向量数据矩阵就会产生4个不同的图片，然而他们的种子值确实是为同一个。 这个之间还是有对应关系。如果你需要还原图 就和之前生成同样的批次数量 找到同一个索引图它就是一致的。

**Comment by yolain** [comment]
或者想要还原图加个索引值应该也可以还原 ，不过还得记索引值 我感觉也挺麻烦的 没有打算做在节点上。
