### ISSUE TITLE
easyloader 缺少输入点

### ISSUE THREAD

**Issue by nUser0** [yolain/ComfyUI-Easy-Use#231]
c站下的压缩包里的workflow没问题，但自己右键添加的easyloader 缺少正反提示词的输入点。

我把只有上述两个loader的界面保存了一下，内容如下：

{
  "last_node_id": 2,
  "last_link_id": 0,
  "nodes": [
    {
      "id": 1,
      "type": "easy comfyLoader",
      "pos": [
        697,
        346
      ],
      "size": [
        365.95086669921875,
        334
      ],
      "flags": {},
      "order": 0,
      "mode": 0,
      "inputs": [
        {
          "name": "optional_lora_stack",
          "type": "LORA_STACK",
          "link": null
        },
        {
          "name": "optional_controlnet_stack",
          "type": "CONTROL_NET_STACK",
          "link": null
        },
        {
          "name": "positive",
          "type": 0,
          "link": null,
          "widget": {
            "name": "positive"
          }
        },
        {
          "name": "negative",
          "type": 0,
          "link": null,
          "widget": {
            "name": "negative"
          }
        }
      ],
      "outputs": [
        {
          "name": "pipe",
          "type": "PIPE_LINE",
          "links": [],
          "shape": 3
        },
        {
          "name": "model",
          "type": "MODEL",
          "links": null,
          "shape": 3
        },
        {
          "name": "vae",
          "type": "VAE",
          "links": [],
          "shape": 3
        }
      ],
      "properties": {
        "Node name for S&R": "easy comfyLoader"
      },
      "widgets_values": [
        "pony.safetensors",
        "Baked VAE",
        -2,
        "None",
        1,
        1,
        "自定义 x 自定义",
        768,
        1024,
        "",
        "",
        1
      ]
    },
    {
      "id": 2,
      "type": "easy comfyLoader",
      "pos": [
        202,
        306
      ],
      "size": [
        400,
        362
      ],
      "flags": {},
      "order": 1,
      "mode": 0,
      "inputs": [
        {
          "name": "optional_lora_stack",
          "type": "LORA_STACK",
          "link": null
        },
        {
          "name": "optional_controlnet_stack",
          "type": "CONTROL_NET_STACK",
          "link": null
        }
      ],
      "outputs": [
        {
          "name": "pipe",
          "type": "PIPE_LINE",
          "links": null,
          "shape": 3
        },
        {
          "name": "model",
          "type": "MODEL",
          "links": null,
          "shape": 3
        },
        {
          "name": "vae",
          "type": "VAE",
          "links": null,
          "shape": 3
        }
      ],
      "properties": {
        "Node name for S&R": "easy comfyLoader"
      },
      "widgets_values": [
        "Pony.safetensors",
        "Baked VAE",
        -1,
        "None",
        1,
        1,
        "512 x 512",
        512,
        512,
        "",
        "",
        1
      ]
    }
  ],
  "links": [],
  "groups": [],
  "config": {},
  "extra": {
    "ds": {
      "scale": 1,
      "offset": [
        0,
        0
      ]
    }
  },
  "version": 0.4
}

**Comment by nUser0** [comment]
可以看到，下面的节点数据中的input字段确实少了两个。

**Comment by yolain** [comment]
🌝 没有少，你自己检查下为啥会不同。

**Comment by nUser0** [comment]
可是我搜comfy，只有一个节点啊？也没看到哪里有选项之类。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年06月29日 16:47 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [yolain/ComfyUI-Easy-Use] easyloader 缺少输入点 (Issue #231) |

🌝 没有少，你自己检查下为啥会不同。

**Comment by nUser0** [comment]
![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/102343229/b16c9fd5-064e-44a5-8575-936199fee0eb)
难道是哪里能设置吗？

**Comment by nUser0** [comment]
> 🌝 没有少，你自己检查下为啥会不同。

下面代码里的positive和negative是文本框吧，哪个是左边的输入点啊？

class a1111Loader(fullLoader):
    @classmethod
    def INPUT_TYPES(cls):
        resolution_strings = [f"{width} x {height}" for width, height in BASE_RESOLUTIONS]
        a1111_prompt_style_default = False
        checkpoints = folder_paths.get_filename_list("checkpoints")
        loras = ["None"] + folder_paths.get_filename_list("loras")
        return {
            "required": {
                "ckpt_name": (checkpoints,),
                "vae_name": (["Baked VAE"] + folder_paths.get_filename_list("vae"),),
                "clip_skip": ("INT", {"default": -1, "min": -24, "max": 0, "step": 1}),

                "lora_name": (loras,),
                "lora_model_strength": ("FLOAT", {"default": 1.0, "min": -10.0, "max": 10.0, "step": 0.01}),
                "lora_clip_strength": ("FLOAT", {"default": 1.0, "min": -10.0, "max": 10.0, "step": 0.01}),

                "resolution": (resolution_strings, {"default": "512 x 512"}),
                "empty_latent_width": ("INT", {"default": 512, "min": 64, "max": MAX_RESOLUTION, "step": 8}),
                "empty_latent_height": ("INT", {"default": 512, "min": 64, "max": MAX_RESOLUTION, "step": 8}),

                "positive": ("STRING", {"default":"", "placeholder": "Positive", "multiline": True}),
                "negative": ("STRING", {"default":"", "placeholder": "Negative", "multiline": True}),
                "batch_size": ("INT", {"default": 1, "min": 1, "max": 64}),
            },
            "optional": {
                "optional_lora_stack": ("LORA_STACK",),
                "optional_controlnet_stack": ("CONTROL_NET_STACK",),
                "a1111_prompt_style": ("BOOLEAN", {"default": a1111_prompt_style_default}),
            },
            "hidden": {"prompt": "PROMPT", "my_unique_id": "UNIQUE_ID"}
        }

**Comment by nUser0** [comment]
> 🌝 没有少，你自己检查下为啥会不同。

下图左边是右键添加的节点，右边是我从别的workflow里面复制过来的。
![屏幕截图 2024-06-29 181329](https://github.com/yolain/ComfyUI-Easy-Use/assets/102343229/8e1cfda8-4cef-43a5-a2cf-adc85237de37)

**Comment by nUser0** [comment]
> 🌝 没有少，你自己检查下为啥会不同。

你的这个库“[ComfyUI-Yolain-Workflows](https://github.com/yolain/ComfyUI-Yolain-Workflows)”，里面的“1-4通配符与风格提示词.json”加载后的loader是下面这个样子：
![屏幕截图 2024-07-01 113027](https://github.com/yolain/ComfyUI-Easy-Use/assets/102343229/eb15a9dc-0790-4412-9742-e45e04cd9477)
左边有输入点，才能和“Styles Selector”配合。
但除了复制，我找不到其他添加这种节点的方法。

**Comment by yolain** [comment]
节点上右键菜单可以把widget转成input的。

🥲不造大家是怎么学Comfy的，感觉很大部分人直接工作流拿来用。基本操作不看下，简单的错误不会排查。
没有说道你的意思，只是觉得大家都想速成，EasyUse是降低大家的学习成本，但是基础的东西还是要会的呀。

**Comment by nUser0** [comment]
> 节点上右键菜单可以把widget转成input的。
> 
> 🥲不造大家是怎么学Comfy的，感觉很大部分人直接工作流拿来用。基本操作不看下，简单的错误不会排查。
> 没有说道你的意思，只是觉得大家都想速成，EasyUse是降低大家的学习成本，但是基础的东西还是要会的呀。

哦哦，找到了。

我是自己摸索着学的，有时搜索一下看看别人怎么操作的。

也没看到有系统的教程或官方文档之类。
所以只是用到什么，摸索什么……

这个convert菜单之前还真没注意。

其实我就是右键菜单等等常规方法都没找到，才来问的，毕竟一般来说看源代码比找菜单难度大是吧。

只是，我以为这种切换是你的nodes的功能，一直没往下面的菜单项看……

为了这个，还去学了怎么写nodes，也没看到怎么指定input项是在左边的点，还是下面的选项或是框……

结果，没想到原来官方功能就是可以随便切换……

**Comment by nUser0** [comment]
> 节点上右键菜单可以把widget转成input的。
> 
> 🥲不造大家是怎么学Comfy的，感觉很大部分人直接工作流拿来用。基本操作不看下，简单的错误不会排查。
> 没有说道你的意思，只是觉得大家都想速成，EasyUse是降低大家的学习成本，但是基础的东西还是要会的呀。

请教一下：
我看到有的节点定义里面有“ForceInput”（凭印象写的，不确定拼写大小写对不对），是不是就是让这个变量默认就是左边的“input”输入点的意思啊？

**Comment by nUser0** [comment]
> > > 节点上右键菜单可以把widget转成input的。
> > > 🥲不造大家是怎么学Comfy的，感觉很大部分人直接工作流拿来用。基本操作不看下，简单的错误不会排查。
> > > 没有说道你的意思，只是觉得大家都想速成，EasyUse是降低大家的学习成本，但是基础的东西还是要会的呀。
> > 
> > 请教一下： 我看到有的节点定义里面有“ForceInput”（凭印象写的，不确定拼写大小写对不对），是不是就是让这个变量默认就是左边的“input”输入点的意思啊？
> 
> 是的。

谢谢！
那我把这个反馈关闭啦。
