### ISSUE TITLE
用这个pony模型就会输出噪点图

### ISSUE THREAD

**Issue by devilweime** [yolain/ComfyUI-Easy-Use#233]
模型：duchaitenPonyXLNo_ponyNoScoreV40.safetensors
模型地址：https://civitai.com/models/376450/duchaiten-pony-xl-no-score
用这个pony模型就输出噪点图，这个模型用其他的加载器和采样器又是正常的
easy-use处理个别xl模型又是正常的
![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/36890816/1fde5629-b3b3-4ceb-a6f0-794528f65f40)

**Comment by yolain** [comment]
方便的话 发我下 提词跟 lora链接

**Comment by devilweime** [comment]
> 方便的话 发我下 提词跟 lora链接

找到原因了。clip停止层改成-2就正常了
