### ISSUE TITLE
那个图像裁切的的节点，百分比模式，无法+1-1，只能+8-8。

### ISSUE THREAD

**Issue by forfai** [yolain/ComfyUI-Easy-Use#24]
那个图像裁切的的节点，修一下百分比模式，无法+1-1，只能+8-8。这样百分比下无法设置成50%。
看了一下rgthree的图像裁剪节点，切换像素模式和百分比模式就没这问题。

**Comment by yolain** [comment]
好的，我晚上fix一下

**Comment by yolain** [comment]
2d0f2f7b3c0e9dc7d4606ec6d9b9a0ede210e695 已修复
