### ISSUE TITLE
bug with node "xy input - target_parametr Sampler & scheduler"

### ISSUE THREAD

**Issue by pvp-by** [yolain/ComfyUI-Easy-Use#240]
how it's supposed to work, what I expect :
![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/10133995/8c84c1ff-724d-43f9-8809-d19568111ea7)
result - nice :
![easyPreview_temp_aneth_00001_](https://github.com/yolain/ComfyUI-Easy-Use/assets/10133995/9120bcf7-8e42-4d6b-a5ee-1f3cc8a633f8)

not work correct . see image bad:
![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/10133995/dc535614-cd46-4e1b-b23c-936a9b7d3a83)
result (seed fixed) img_bad:
![easyPreview_temp_rjahh_00001_](https://github.com/yolain/ComfyUI-Easy-Use/assets/10133995/5664119b-3a57-4c75-90a0-aed412630027)

i see what only sampler change

**Comment by yolain** [comment]
It's fixed. It was caused by an extra space.

**Comment by pvp-by** [comment]
Thanks for your hard work, everything works correctly.
