### ISSUE TITLE
Error occurred when executing easy imageDetailTransfer:  The size of tensor a (1360) must match the size of tensor b (1365) at non-singleton dimension 2

### ISSUE THREAD

**Issue by 0002kgHg** [yolain/ComfyUI-Easy-Use#241]
In my workflow, I only want to use ic-light to change the lighting and shading of the character's face. However, simply using the background removal node will also keep the character's body, which is not what I want. Therefore, as shown in the image below, I used yolo or G-dino for head recognition and then connected ic-light. However, after ksampler generated the image, I wanted to use the Easy Use image detail transfer node, but it failed. In the past, when I used those background removal nodes, there were no errors. I am not sure if this is an issue with ic-light or with the image transfer node, or if the output images and masks from the background removal nodes differ from those of the detection nodes.

Error occurred when executing easy imageDetailTransfer:

The size of tensor a (1360) must match the size of tensor b (1365) at non-singleton dimension 2

File "/comfyui/execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "/comfyui/execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "/comfyui/execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "/comfyui/custom_nodes/ComfyUI-Easy-Use/py/image.py", line 958, in transfer
new_image = torch.lerp(target_tensor, new_image, mask)

![企业微信截图_17201689238374](https://github.com/yolain/ComfyUI-Easy-Use/assets/90631570/110aec73-4ce7-4297-ba4d-6e5a24d2aa2f)

**Comment by yolain** [comment]
You need to make sure that the target image and source image and mask size are the same.

**Comment by 0002kgHg** [comment]
> You need to make sure that the target image and source image and mask size are the same.

Yes, I know, but just by looking at the dimensions, they appear to be the same.

![企业微信截图_17201718119047](https://github.com/yolain/ComfyUI-Easy-Use/assets/90631570/535a737c-4fcf-490b-8ae2-83b65a2a8bdb)

**Comment by 0002kgHg** [comment]
> You need to make sure that the target image and source image and mask size are the same.

Yes, I know, but just by looking at the dimensions, they appear to be the same.

![企业微信截图_17201720707954](https://github.com/yolain/ComfyUI-Easy-Use/assets/90631570/c7736b6b-d8a6-49c9-bd83-3c8c009a4686)

**Comment by yolain** [comment]
Are the sizes generated by the sampler also calibrated?

**Comment by linuxdevopscn** [comment]
The pixel dimensions of the image generated by the sampler might have a slight discrepancy from the original image and need to be corrected.
﻿

**Comment by ZhaoXinyi** [comment]
It still reports an error after unifying the size.RuntimeError: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 1
