### ISSUE TITLE
更新comfy后高级cn节点中的柔和缩放权重报错

### ISSUE THREAD

**Issue by 253701** [yolain/ComfyUI-Easy-Use#242]
退回到6月27号comfy本体能正常试用，之后的版本一旦调柔和缩放权重就会报错，打到1不动能正常跑通

**Comment by yolain** [comment]
Update ComfyUI-Adavaned-Controlnet

**Comment by 253701** [comment]
> Update ComfyUI-Adavaned-Controlnet
谢谢作者，cn插件报错的问题解决了，还有一个预修复的节点报错可以帮我看一下吗
![IPSI)3101AX R(Z)JDU9%DB](https://github.com/yolain/ComfyUI-Easy-Use/assets/127170526/50b8287f-cf7e-4204-95d3-de8284e4b359)
![W~(O (( 5NO% }`1Y NH(2](https://github.com/yolain/ComfyUI-Easy-Use/assets/127170526/1c7b5486-8cc6-40b6-ac4e-0e40bcc0d5e5)

**Comment by yolain** [comment]
> > Update ComfyUI-Adavaned-Controlnet
> > 谢谢作者，cn插件报错的问题解决了，还有一个预修复的节点报错可以帮我看一下吗
> > ![IPSI)3101AX R(Z)JDU9%DB](https://private-user-images.githubusercontent.com/127170526/346314664-50b8287f-cf7e-4204-95d3-de8284e4b359.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzMzM4NjYsIm5iZiI6MTcyMDMzMzU2NiwicGF0aCI6Ii8xMjcxNzA1MjYvMzQ2MzE0NjY0LTUwYjgyODdmLWNmN2UtNDIwNC05NWQzLWRlODI4NGU0YjM1OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwN1QwNjI2MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYWY3YjQ3NTkxNTEzNjBmM2U5NjhkZDE3ZTUxZGY3MjI1YjA2NjVkN2VlMjM1YjI5ZTYwYjBmODI0YjgwMzE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MxWzupeNTKZs8G2GaDvE-8r-6fU7ZVJp__ItOinpHZA)
> > ![W~(O (( 5NO% }`1Y NH(2](https://private-user-images.githubusercontent.com/127170526/346314666-1c7b5486-8cc6-40b6-ac4e-0e40bcc0d5e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzMzM4NjYsIm5iZiI6MTcyMDMzMzU2NiwicGF0aCI6Ii8xMjcxNzA1MjYvMzQ2MzE0NjY2LTFjN2I1NDg2LThjYzYtNDBiNi1hYzRlLTBlNDBiY2MwZDVlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwN1QwNjI2MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYzQxZWNiOGQ0ZGIyMjQxNDc5OTc5NTE0MWJhMmQ5MzEzZDY0NWY3YzVhMzhkYmQ1MzM5N2NhMjdkY2Q1YmE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SzfJUKBLaMMnblG23w43X52aSYufnogZTihO8bC7GhM)

细节修复的 sam 走hq 的模型不行，。

**Comment by 253701** [comment]
> > > Update ComfyUI-Adavaned-Controlnet
> > > 谢谢作者，cn插件报错的问题解决了，还有一个预修复的节点报错可以帮我看一下吗
> > > ![IPSI)3101AX R(Z)JDU9%DB](https://private-user-images.githubusercontent.com/127170526/346314664-50b8287f-cf7e-4204-95d3-de8284e4b359.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzMzM4NjYsIm5iZiI6MTcyMDMzMzU2NiwicGF0aCI6Ii8xMjcxNzA1MjYvMzQ2MzE0NjY0LTUwYjgyODdmLWNmN2UtNDIwNC05NWQzLWRlODI4NGU0YjM1OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwN1QwNjI2MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYWY3YjQ3NTkxNTEzNjBmM2U5NjhkZDE3ZTUxZGY3MjI1YjA2NjVkN2VlMjM1YjI5ZTYwYjBmODI0YjgwMzE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MxWzupeNTKZs8G2GaDvE-8r-6fU7ZVJp__ItOinpHZA)
> > > ![W~(O (( 5NO% }`1Y NH(2](https://private-user-images.githubusercontent.com/127170526/346314666-1c7b5486-8cc6-40b6-ac4e-0e40bcc0d5e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzMzM4NjYsIm5iZiI6MTcyMDMzMzU2NiwicGF0aCI6Ii8xMjcxNzA1MjYvMzQ2MzE0NjY2LTFjN2I1NDg2LThjYzYtNDBiNi1hYzRlLTBlNDBiY2MwZDVlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwN1QwNjI2MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYzQxZWNiOGQ0ZGIyMjQxNDc5OTc5NTE0MWJhMmQ5MzEzZDY0NWY3YzVhMzhkYmQ1MzM5N2NhMjdkY2Q1YmE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SzfJUKBLaMMnblG23w43X52aSYufnogZTihO8bC7GhM)
> 
> 细节修复的 sam 走hq 的模型不行，。

谢谢作者，已解决
