### ISSUE TITLE
easy kolorsLoader没有EulerDiscreteScheduler调度器

### ISSUE THREAD

**Issue by yincangshiwei** [yolain/ComfyUI-Easy-Use#249]
我看ComfyUI-KwaiKolorsWrapper的示例是使用EulerDiscreteScheduler调度器的，但easy kolorsLoader里没找到有。

**Comment by yincangshiwei** [comment]
说错了，应该是说PreSampling里没有这个调度器

**Comment by yolain** [comment]
EulerDiscreteScheduler 就是 scheduler 中的 euler.   
Wrapper 和 comfy native不一样的。 wrapper 走的是 diffusers pipeline 的逻辑，所以要重新写个schduler.
