### ISSUE TITLE
how to use detailer fix

### ISSUE THREAD

**Issue by whmc76** [yolain/ComfyUI-Easy-Use#25]
i dont know how to merge pip and bbox pip to detailer fix thx

**Comment by yolain** [comment]
The preDetailerFix node needs to be added first, and then outputs from UltralyticDetector(pipe) and SamLoader(pipe) must be combined with this node, Finally connect the preDetailerFix output pipe to the DetailerFix.
<img width="1165" alt="DetailerFix" src="https://github.com/yolain/ComfyUI-Easy-Use/assets/73304135/c549da44-9730-471b-b320-728101930450">

**Comment by whmc76** [comment]
> The preDetailerFix node needs to be added first, and then outputs from UltralyticDetector(pipe) and SamLoader(pipe) must be combined with this node, Finally connect the preDetailerFix output pipe to the DetailerFix. <img alt="DetailerFix" width="1165" src="https://private-user-images.githubusercontent.com/73304135/295182786-c549da44-9730-471b-b320-728101930450.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MTU2MjQsIm5iZiI6MTcwNDgxNTMyNCwicGF0aCI6Ii83MzMwNDEzNS8yOTUxODI3ODYtYzU0OWRhNDQtOTczMC00NzFiLWIzMjAtNzI4MTAxOTMwNDUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDE1NDg0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4MWM4NzQ4NjgyNmI4MDE4MzRhMzJiOTU2MjU1YmMxYTM3NWNmODM2Y2QzNjU0ZjlkNjdmMmJhZDNmOGI0ZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.m8NLGwxIM5SwEjg_TMKrU9dYdEcaPIaR8gm2CzO8XAg">

got it , very useful nodes
