### ISSUE TITLE
Arial.ttf isn't free-to-use, should probably replace it with one of the many open source equivalents

### ISSUE THREAD

**Issue by NeedsMoar** [yolain/ComfyUI-Easy-Use#26]
https://en.wikipedia.org/wiki/Arial

Liberation Sans is the open source ripof... I mean equivalent of it:
https://github.com/liberationfonts/liberation-fonts/releases

Or grab one of the Ghostscript fonts.  The font designers don't mess around when it comes to their money cows and there are enough actually free ones out there it's not worth getting your repo taken down over if they go on a round of DMCA filings...  Especially over something as generic as Arial.

**Comment by yolain** [comment]
ok, I'll replace it in the next release
