### ISSUE TITLE
 easy kSampler使用失败报错

### ISSUE THREAD

**Issue by shen774411223d** [yolain/ComfyUI-Easy-Use#262]
求大佬帮忙看下是因为什么

![屏幕截图 2024-07-21 190846](https://github.com/user-attachments/assets/e8893dff-bdf7-4f65-a33d-e7c749e7de1c)
![屏幕截图 2024-07-21 210950](https://github.com/user-attachments/assets/8fdb5c3f-0896-4416-9ff3-06c3aa9bca84)
使用的工作流是ic-light：[3-2-1.电商产品主图](https://github.com/yolain/ComfyUI-Yolain-Workflows/tree/main?tab=readme-ov-file#3-2-1-%E7%94%B5%E5%95%86%E4%BA%A7%E5%93%81%E4%B8%BB%E5%9B%BE)

**Comment by yolain** [comment]
更新 comfyui-advanced-controlnet

**Comment by shen774411223d** [comment]
> 更新 comfyui-advanced-controlnet

多谢作者大佬，按照您的方法成功的解决了。赞！！！
