### ISSUE TITLE
更新ComfyUI后主题会失效

### ISSUE THREAD

**Issue by fs920105** [yolain/ComfyUI-Easy-Use#27]
清楚了缓存，重装节点也不行。
![微信截图_20240112124946](https://github.com/yolain/ComfyUI-Easy-Use/assets/135109872/5f5ba3ba-d2b9-4961-8bd7-167cdea4068f)

**Comment by yolain** [comment]
官方新写了多用户配置引起的。你可以把那些undefined先删除掉。然后先通过导入这个文件解决。
[obsidian_theme.json](https://github.com/yolain/ComfyUI-Easy-Use/files/13915206/obsidian_theme.json)

**Comment by fs920105** [comment]
我也想删，关键是这玩意删除不了，删完之后重新打开就又会出现，导入你的文件，本来圆角还能用，只是没透明哪些UI了，现在圆角也没了。只能删除整个节点重新放回去圆角才能恢复，但是也只有圆角。这个不好修复吗？

**Comment by fs920105** [comment]
> > 我也想删，关键是这玩意删除不了，删完之后重新打开就又会出现，导入你的文件，本来圆角还能用，只是没透明哪些UI了，现在圆角也没了。只能删除整个节点重新放回去圆角才能恢复，但是也只有圆角。这个不好修复吗？
> 
> 我新版本更新已经修复了。但是我看到你这条问题更新comfyui之后并没有出现你这种情况，只是主题加载失败了。你试试删掉user文件夹里default的文件看看。

很完美，解决了
