### ISSUE TITLE
easy hiresFix 高清修复节点报错

### ISSUE THREAD

**Issue by shen774411223d** [yolain/ComfyUI-Easy-Use#274]
作者您好，我使用您的 [3-2-1.电商产品主图](https://github.com/yolain/ComfyUI-Yolain-Workflows#3-2-1-%E7%94%B5%E5%95%86%E4%BA%A7%E5%93%81%E4%B8%BB%E5%9B%BE) workflow时遇到了一些问题。
我将工作流导入我的comfyui后直接运行 在高清修复节点报错。高清节点所需要的两个模型文件我已经下载好。并且esay-use已经更新到最新版本。
# 非常感谢您的指导 谢谢！
### 下面是我的报错信息
![屏幕截图 2024-07-28 221712](https://github.com/user-attachments/assets/af2bd76f-e9a8-4a7f-98ea-aec8406ca232)
![屏幕截图 2024-07-28 221720](https://github.com/user-attachments/assets/31f42c1e-4752-44df-bcd3-158cd2cf04bf)
### 模型存放在
`\models\upscale_models\4x-UltraSharp.pth`
`\models\vae\vae-ft-mse-840000-ema-pruned.safetensors`

**Comment by yolain** [comment]
应该是模型没完全，文件有损坏。

**Comment by shen774411223d** [comment]
> 作者您好，我使用您的 [3-2-1.电商产品主图](https://github.com/yolain/ComfyUI-Yolain-Workflows#3-2-1-%E7%94%B5%E5%95%86%E4%BA%A7%E5%93%81%E4%B8%BB%E5%9B%BE) workflow时遇到了一些问题。 我将工作流导入我的comfyui后直接运行 在高清修复节点报错。高清节点所需要的两个模型文件我已经下载好。并且esay-use已经更新到最新版本。
> 
> # 非常感谢您的指导 谢谢！
> ### 下面是我的报错信息
> ![屏幕截图 2024-07-28 221712](https://private-user-images.githubusercontent.com/23494847/352826726-af2bd76f-e9a8-4a7f-98ea-aec8406ca232.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMTc4ODIsIm5iZiI6MTcyMjIxNzU4MiwicGF0aCI6Ii8yMzQ5NDg0Ny8zNTI4MjY3MjYtYWYyYmQ3NmYtZTlhOC00YTdmLTk4ZWEtYWVjODQwNmNhMjMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDAxNDYyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4YjI3Y2Y4YjM4MGE4ZWRhMDk0OGUyODgxMTZlYjZiYzYwNDEyMWZhNDMxYzNlYzNhNjQxNTI2MmUwODU1NTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HSGwhDDLq3MJtlSexbMXSiXToKUpyQDgylBhmmHpUhM) ![屏幕截图 2024-07-28 221720](https://private-user-images.githubusercontent.com/23494847/352826826-31f42c1e-4752-44df-bcd3-158cd2cf04bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMTc4ODIsIm5iZiI6MTcyMjIxNzU4MiwicGF0aCI6Ii8yMzQ5NDg0Ny8zNTI4MjY4MjYtMzFmNDJjMWUtNDc1Mi00NGRmLWJjZDMtMTU4Y2QyY2YwNGJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDAxNDYyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxNjY0MmRkNzlhMTBmMTQ5YTBhNThjYWI2MWM5NTQzMTA5NTIwY2MzMjRlYzE3NTkyZTc3YzZkYWFjZmI2MGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8HJw6CKGYRYFUMv-CXWQR4drcVJz5lBtmreco8B71Fc)
> 
> ### 模型存放在
> `\models\upscale_models\4x-UltraSharp.pth` `\models\vae\vae-ft-mse-840000-ema-pruned.safetensors`

好的 感谢大佬的指导。晚上重新下载模型试一下，可能从comfyui-manager下载时网络波动导致的

**Comment by shen774411223d** [comment]
> 应该是模型没完全，文件有损坏。

好的，感谢大佬的指导。可能是从comfyui-manager下载时网络波动导致的。晚上重新下载试试

**Comment by shen774411223d** [comment]
> 应该是模型没完全，文件有损坏。

大佬感谢您的协助。重新从网站上下载了模型后。整个工作流成功运行了！感谢您的帮助 大佬棒棒棒！！！
