### ISSUE TITLE
'NoneType' object has no attribute 'tokenize'

### ISSUE THREAD

**Issue by wailovet** [yolain/ComfyUI-Easy-Use#28]
https://github.com/yolain/ComfyUI-Easy-Use/blob/e8640c62064ed2ad083f21f6f6fe4a844252af6f/py/easyNodes.py#L729C68-L729C68
![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/5035199/5493c18b-c8f9-4368-b092-b39053f78cf6)

我使用的时候发现这个地方会报:'NoneType' object has no attribute 'tokenize'
这里是不是少了
```
clip = clip if clip is not None else plot_image_vars["clip"]
```

**Comment by yolain** [comment]
是的，晚点修复一下

**Comment by wailovet** [comment]
> 是的，晚点修复一下

![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/5035199/de506bca-2005-484b-b282-fa629d8c5861)
这个地方我使用方式有没有什么问题
https://github.com/yolain/ComfyUI-Easy-Use/blob/e8640c62064ed2ad083f21f6f6fe4a844252af6f/py/adv_encode.py#L260
我尝试打印这里的text,输出的结果都是aacc

**Comment by yolain** [comment]
412c7abb1d705d99ab78d90c299e8e68aeb48b78 你更新下试试。

**Comment by wailovet** [comment]
> [412c7ab](https://github.com/yolain/ComfyUI-Easy-Use/commit/412c7abb1d705d99ab78d90c299e8e68aeb48b78) 你更新下试试。

可以了,撒花,非常感谢
