### ISSUE TITLE
How to use Hunyuan Dit model loader

### ISSUE THREAD

**Issue by karthikg-09** [yolain/ComfyUI-Easy-Use#280]
How to use Hunyuan Dit easy model loader??
please provide a sample workflow json or screen shot

**Comment by yolain** [comment]
First you need to download the comfy version of the [hunyuanDiT checkpoints](https://huggingface.co/comfyanonymous/hunyuan_dit_comfyui/tree/main),
Then just connect the three nodes as shown, or replace the hunyunDiTLoader with a regular fullLoader or a1111 or comfyLoader, and it will work just as well, just a few more irrelevant params..

<img width="1291" alt="截屏2024-08-01 13 17 40" src="https://github.com/user-attachments/assets/bb41690d-8f72-494b-b5fb-df8944dc34f3">

**Comment by karthikg-09** [comment]
Thank you, @yolain for your quick response
