### ISSUE TITLE
希望可以整合支持flux模型使用

### ISSUE THREAD

**Issue by yincangshiwei** [yolain/ComfyUI-Easy-Use#288]
flux出来的效果很不错，希望可以整合到EasyUse里面，参考：https://comfyanonymous.github.io/ComfyUI_examples/flux/

**Comment by yincangshiwei** [comment]
?

**Comment by yolain** [comment]
暂时不整合到loader呢，可以前面打个组
![image](https://github.com/user-attachments/assets/561c1cf4-3181-425d-89ef-bfdb8e17327e)

**Comment by yincangshiwei** [comment]
> 暂时不整合到loader呢，可以前面打个组 ![image](https://private-user-images.githubusercontent.com/73304135/355403812-561c1cf4-3181-425d-89ef-bfdb8e17327e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5OTk5MDQsIm5iZiI6MTcyMjk5OTYwNCwicGF0aCI6Ii83MzMwNDEzNS8zNTU0MDM4MTItNTYxYzFjZjQtMzE4MS00MjVkLTg5ZWYtYmZkYjhlMTczMjdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDAzMDAwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4YzdmODAwNTliZjA4YzkwZjY4MjZlNzY2YzRmNDRlYjc1YWNmMDVmZTRjNmRiMWNiMWRmZDBjNTQ0ZGViZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ULfKNQI_okMr4F1HnxJsYPdPqrq_WekHbhuXQ0QQgW8)

赞！
