### ISSUE TITLE
A suggestion, is it possible to implement

### ISSUE THREAD

**Issue by BoosterCore** [yolain/ComfyUI-Easy-Use#289]
Is it possible to modify the code so that I can customize the model path , such as SAMS, in the` extra_model_paths.yaml` document?
I think this will allow multiple copies of ComfyUI to share models, avoiding repeated downloads of models and taking up a lot of disk space.
In addition, with more and more plugins nowadays, various dependency conflicts are also very frequent, so it is very necessary to use multiple copies of Comfy UI.

Maybe you can refer to this：
https://github.com/GreenLandisaLie/AuraSR-ComfyUI/issues/10

**Comment by yolain** [comment]
I don't have models stored in my node package，they are all in the models directory of comfyui, e.g. sams, you just need to configure the corresponding paths in extra_model_paths.yaml or set up soft links yet.

**Comment by BoosterCore** [comment]
OK, finally I use `mklink` to solved this issue
