### ISSUE TITLE
经常无法生成新的随机种子 或者在两个同样的种子直接左右横跳

### ISSUE THREAD

**Issue by whmc76** [yolain/ComfyUI-Easy-Use#29]
![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/129386342/4529bed2-cbc5-45a2-9050-fc94c8f3b345)
![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/129386342/4c87505c-c8dc-48e5-afea-a5d6ca487175)
经常无法生成新的随机种子 或者在两个同样的种子直接左右横跳

**Comment by yolain** [comment]
你是不是有接修手的节点

**Comment by yolain** [comment]
目前有两种解决办法
第一种：不调整代码，先将修手的流程bypass，跑到满意的fixed之后再来修手
第二种：修改 ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\mesh_graphormer\pipeline.py 文件，将73行的这一段先注释掉
![微信图片_20240115153445](https://github.com/yolain/ComfyUI-Easy-Use/assets/73304135/2fb66676-6ac5-46c1-b5ef-d6e8f05b6c86)

**Comment by whmc76** [comment]
那个mesh啥的预处理器么 好像是有发自我的手机-------- 原始邮件 --------发件人： yolain ***@***.***>日期： 2024年1月15日周一 下午3:27收件人： yolain/ComfyUI-Easy-Use ***@***.***>抄送： Cyber Dick Lang ***@***.***>, Author ***@***.***>主    题： Re: [yolain/ComfyUI-Easy-Use] 经常无法生成新的随机种子 或者在两个同样的种子直接左右横跳 (Issue #29)
你是不是有接修手的节点

**Comment by whmc76** [comment]
> 目前有两种解决办法 第一种：不调整代码，先将修手的流程bypass，跑到满意的fixed之后再来修手 第二种：修改 ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\mesh_graphormer\pipeline.py 文件，将73行的这一段先注释掉 ![微信图片_20240115153445](https://private-user-images.githubusercontent.com/73304135/296685034-2fb66676-6ac5-46c1-b5ef-d6e8f05b6c86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMDU1OTQsIm5iZiI6MTcwNTMwNTI5NCwicGF0aCI6Ii83MzMwNDEzNS8yOTY2ODUwMzQtMmZiNjY2NzYtNmFjNS00NmMxLWI1ZWYtZDZlOGYwNWI2Yzg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDA3NTQ1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxNTM5YzZkMzBjZmM0OWQ3ODNjOGI5NTFlYjA0MmExNWRhY2EyOTgzNzBmMzA5OGU0NWQ1MjVkMTE0OTU4ODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KH-ex_FWHwaGbDEuMh9mLv8Rmy6g9QUWO3ze-OGcKdI)

坐等大佬battle那个插件
