### ISSUE TITLE
使用高级ipa应用时报错（普通ipa应用不会报错），函数定义中没有包含weight_kolors参数，comfyui和easyuese都已更新到最新

### ISSUE THREAD

**Issue by wch352136** [yolain/ComfyUI-Easy-Use#291]
![image](https://github.com/user-attachments/assets/102e5a10-13e8-42bc-8669-ebed143727c2)

`Traceback (most recent call last):
  File "E:\AI\ComfyUI-aki-v1.1\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "E:\AI\ComfyUI-aki-v1.1\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "E:\AI\ComfyUI-aki-v1.1\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "E:\AI\ComfyUI-aki-v1.1\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py", line 3226, in apply
    model, images = cls().apply_ipadapter(model, ipadapter, weight=weight, weight_type=weight_type, start_at=start_at, end_at=end_at, combine_embeds=combine_embeds, weight_faceidv2=weight_faceidv2, image=image, image_negative=image_negative, weight_style=1.0, weight_composition=1.0, image_style=image_style, image_composition=image_composition, expand_style=expand_style, clip_vision=clip_vision, attn_mask=attn_mask, insightface=None, embeds_scaling=embeds_scaling, weight_kolors=weight_kolors)
TypeError: IPAdapterAdvanced.apply_ipadapter() got an unexpected keyword argument  #'weight_kolors'`

**Comment by yolain** [comment]
ipadapter要更新

**Comment by wch352136** [comment]
> ipadapter要更新

不知道为什么comfyui的管理器并没把ipadapter更新到最新，更新ipa以后解决，感谢。

**Comment by Sdreamtale** [comment]
> ipadapter要更新

Is it about updating the "ComfyUI_IPAdapter_plus" node?
