### ISSUE TITLE
关于Easy-Use的节点缺失问题

### ISSUE THREAD

**Issue by leolee6102** [yolain/ComfyUI-Easy-Use#296]
![1723186315730](https://github.com/user-attachments/assets/10e805d9-58fa-4289-b770-1ee23c1a0e5a)
![1723186551209](https://github.com/user-attachments/assets/641e67ab-6c7b-4790-a780-d9ef5ba7cb3e)
根据你的Easy-Use搭的工作流，会提示缺失节点IPAdapterApply，InsightFaceLoader，IPAdapterApplyFaceID节点。是否是调用了已停用的ComfyUI_IPAdapter_plus的相关节点？

**Comment by yolain** [comment]
你用的哪个流啊

**Comment by leolee6102** [comment]
> 你用的别人做的工作流么？这些缺失节点不是easyuse里的。 他这个工作流里用的ipa节点和你的ipa节点包不是同一个

是我的问题。我此前导入了一个别人的工作流（他的工作流应该用了老版本的ipadapter），我当时只是删除了他的工作流，而不是点清除按钮，就直接按你示例中的工作流搭建，然后才报如上错误。


打扰你了....
