### ISSUE TITLE
Seed那里虽然是control before generate, 但是改回fixed, 点击了queue, 还是会多渲染一回

### ISSUE THREAD

**Issue by xueqing0622** [yolain/ComfyUI-Easy-Use#3]
Seed那里虽然是control before generate, 但是改回fixed, 点击了queue, 还是会多渲染一回

已经很完美了啦, 我吹毛求疵罢了, 是现在完美的seed方案了

**Comment by yolain** [comment]
多了个control before generate 这个值 导致prompt变了，我尝试让它不进prompt(不多渲染一轮)，会导致再次变更control before generate 的时候失效， 哎！🥲看了官方默认seed生成那部分的源码貌似只能监听afterQueued的事件。 先这个样子吧，因为我们锁定种子值的时候，也是为了要去调整其他的参数，也是要去再渲染一轮的。

**Comment by xueqing0622** [comment]
没关系 已经很好了!!!
