### ISSUE TITLE
刚更新，报错KeyError: 'WEB_VERSION'

### ISSUE THREAD

**Issue by 807502278** [yolain/ComfyUI-Easy-Use#300]
Warn!: Traceback (most recent call last):
  File "D:\AI\ComfyUI-3D\ComfyUI\nodes.py", line 1941, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\AI\ComfyUI-3D\ComfyUI\custom_nodes\ComfyUI-Easy-Use\__init__.py", line 76, in <module>
    directory = f"./web_version/{data['WEB_VERSION']}"
                                 ~~~~^^^^^^^^^^^^^^^
KeyError: 'WEB_VERSION'

Warn!: Cannot import D:\AI\ComfyUI-3D\ComfyUI\custom_nodes\ComfyUI-Easy-Use module for custom nodes: 'WEB_VERSION'

![image](https://github.com/user-attachments/assets/0d75efa6-81f4-488c-a7e8-de0a274bb9c6)
![image](https://github.com/user-attachments/assets/a3df7149-958c-4254-b8a0-8acf76331768)

**Comment by 807502278** [comment]
我把前面注释的那几行取消注释就好了

**Comment by moddz** [comment]
same

**Comment by Pythonpa** [comment]
same

**Comment by balala8** [comment]
A pull request has been submitted to fix this issue.[#301 ](https://github.com/yolain/ComfyUI-Easy-Use/pull/301), Please wait for the update or update __init__.py file yourself.

**Comment by yolain** [comment]
9e85e3a25c65dff66a52adf00208fa202fd62f34 修复了...
