### ISSUE TITLE
Flux [ERROR] model or clip is missing

### ISSUE THREAD

**Issue by yincangshiwei** [yolain/ComfyUI-Easy-Use#306]
help！use EasyLoader (Flux) error.
![image](https://github.com/user-attachments/assets/eeabbdd8-4856-4fff-9919-1e2cb9a705de)
![image](https://github.com/user-attachments/assets/1e9dd06a-5bfd-4d7c-86f0-c973a3a7c2c2)

**Comment by yolain** [comment]
model_override is missing!.

Look at https://github.com/yolain/ComfyUI-Easy-Use/pull/303

**Comment by yolain** [comment]
> > model_override is missing!.
> > Look at #303
> 
> ![image](https://private-user-images.githubusercontent.com/8185843/358102546-af331382-84bc-49b2-92fe-c77780e0789d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2OTUyNjUsIm5iZiI6MTcyMzY5NDk2NSwicGF0aCI6Ii84MTg1ODQzLzM1ODEwMjU0Ni1hZjMzMTM4Mi04NGJjLTQ5YjItOTJmZS1jNzc3ODBlMDc4OWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTVUMDQwOTI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTFjYjM2NjY2NWMxYTRiYmY5MjNjMGM0MDJmNTU3YWFhMzgwZWQxZWEwNjliMmMxNTM2ZGIzOWEzZmI2ZDI2MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6nueXh-p7VQeCjZfGuXU2yzZ13bWc565Z0ScL1txcpA)
> 
> Error occurred when executing easy kSampler:
> 
> 'NoneType' object has no attribute 'cdequantize_blockwise_fp32'
> 
> File "/root/ComfyUI/execution.py", line 152, in recursive_execute output_data, output_ui = get_output_data(obj, input_data_all) File "/root/ComfyUI/execution.py", line 82, in get_output_data return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True) File "/root/ComfyUI/execution.py", line 75, in map_node_over_list results.append(getattr(obj, func)(**slice_dict(input_data_all, i))) File "/root/ComfyUI/custom_nodes/ComfyUI-Easy-Use/py/easyNodes.py", line 5392, in simple return super().run(pipe, None, None, None, None, None, image_output, link_id, save_prefix, File "/root/ComfyUI/custom_nodes/ComfyUI-Easy-Use/py/easyNodes.py", line 5361, in run return process_sample_state(pipe, samp_model, samp_clip, samp_samples, samp_vae, samp_seed, samp_positive, samp_negative, steps, start_step, last_step, cfg, sampler_name, scheduler, denoise, image_output, link_id, save_prefix, tile_size, prompt, extra_pnginfo, my_unique_id, preview_latent, force_full_denoise, disable_noise, samp_custom) File "/root/ComfyUI/custom_nodes/ComfyUI-Easy-Use/py/easyNodes.py", line 5131, in process_sample_state samp_samples, _ = sampler.custom_advanced_ksampler(noise, guider, _sampler, sigmas, samp_samples) File "/root/ComfyUI/custom_nodes/ComfyUI-Easy-Use/py/libs/sampler.py", line 182, in custom_advanced_ksampler samples = guider.sample(noise.generate_noise(latent), latent_image, sampler, sigmas, denoise_mask=noise_mask, File "/root/ComfyUI/comfy/samplers.py", line 716, in sample output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed) File "/root/ComfyUI/comfy/samplers.py", line 695, in inner_sample samples = sampler.sample(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar) File "/root/ComfyUI/comfy/samplers.py", line 600, in sample samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options) File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context return func(*args, **kwargs) File "/root/ComfyUI/comfy/k_diffusion/sampling.py", line 143, in sample_euler denoised = model(x, sigma_hat * s_in, **extra_args) File "/root/ComfyUI/comfy/samplers.py", line 299, in **call** out = self.inner_model(x, sigma, model_options=model_options, seed=seed) File "/root/ComfyUI/comfy/samplers.py", line 682, in **call** return self.predict_noise(*args, **kwargs) File "/root/ComfyUI/comfy/samplers.py", line 685, in predict_noise return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed) File "/root/ComfyUI/comfy/samplers.py", line 279, in sampling_function out = calc_cond_batch(model, conds, x, timestep, model_options) File "/root/ComfyUI/custom_nodes/ComfyUI-TiledDiffusion/.patches.py", line 4, in calc_cond_batch return calc_cond_batch_original_tiled_diffusion_7732be64(model, conds, x_in, timestep, model_options) File "/root/ComfyUI/comfy/samplers.py", line 228, in calc_cond_batch output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks) File "/root/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet/adv_control/utils.py", line 64, in apply_model_uncond_cleanup_wrapper return orig_apply_model(self, *args, **kwargs) File "/root/ComfyUI/comfy/model_base.py", line 145, in apply_model model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float() File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "/root/ComfyUI/comfy/ldm/flux/model.py", line 150, in forward out = self.forward_orig(img, img_ids, context, txt_ids, timestep, y, guidance, control) File "/root/ComfyUI/comfy/ldm/flux/model.py", line 104, in forward_orig img = self.img_in(img) File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "/root/ComfyUI/custom_nodes/ComfyUI-Easy-Use/py/bitsandbytes_NF4/**init**.py", line 155, in forward return functional_linear_4bits(x, self.weight, self.bias) File "/root/ComfyUI/custom_nodes/ComfyUI-Easy-Use/py/bitsandbytes_NF4/**init**.py", line 21, in functional_linear_4bits out = bnb.matmul_4bit(x, weight.t(), bias=bias, quant_state=weight.quant_state) File "/root/miniconda3/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py", line 579, in matmul_4bit return MatMul4Bit.apply(A, B, out, bias, quant_state) File "/root/miniconda3/lib/python3.10/site-packages/torch/autograd/function.py", line 539, in apply return super().apply(*args, **kwargs) # type: ignore[misc] File "/root/miniconda3/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py", line 509, in forward output = torch.nn.functional.linear(A, F.dequantize_4bit(B, quant_state).to(A.dtype).t(), bias) File "/root/miniconda3/lib/python3.10/site-packages/bitsandbytes/functional.py", line 1347, in dequantize_4bit absmax = dequantize_blockwise(quant_state.absmax, quant_state.state2) File "/root/miniconda3/lib/python3.10/site-packages/bitsandbytes/functional.py", line 977, in dequantize_blockwise lib.cdequantize_blockwise_fp32(

Has ComfyUI been updated yet?

**Comment by yincangshiwei** [comment]
> > > model_override is missing!. model_override不见了！.
> > > Look at #303 查看 #303
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/8185843/358102546-af331382-84bc-49b2-92fe-c77780e0789d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2OTUyNjUsIm5iZiI6MTcyMzY5NDk2NSwicGF0aCI6Ii84MTg1ODQzLzM1ODEwMjU0Ni1hZjMzMTM4Mi04NGJjLTQ5YjItOTJmZS1jNzc3ODBlMDc4OWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTVUMDQwOTI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTFjYjM2NjY2NWMxYTRiYmY5MjNjMGM0MDJmNTU3YWFhMzgwZWQxZWEwNjliMmMxNTM2ZGIzOWEzZmI2ZDI2MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6nueXh-p7VQeCjZfGuXU2yzZ13bWc565Z0ScL1txcpA)
> > Error occurred when executing easy kSampler:执行 easy kSampler 时出错：
> > 'NoneType' object has no attribute 'cdequantize_blockwise_fp32'“NoneType”对象没有属性“cdequantize_blockwise_fp32”
> > File "/root/ComfyUI/execution.py", line 152, in recursive_execute output_data, output_ui = get_output_data(obj, input_data_all) File "/root/ComfyUI/execution.py", line 82, in get_output_data return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True) File "/root/ComfyUI/execution.py", line 75, in map_node_over_list results.append(getattr(obj, func)(**slice_dict(input_data_all, i))) File "/root/ComfyUI/custom_nodes/ComfyUI-Easy-Use/py/easyNodes.py", line 5392, in simple return super().run(pipe, None, None, None, None, None, image_output, link_id, save_prefix, File "/root/ComfyUI/custom_nodes/ComfyUI-Easy-Use/py/easyNodes.py", line 5361, in run return process_sample_state(pipe, samp_model, samp_clip, samp_samples, samp_vae, samp_seed, samp_positive, samp_negative, steps, start_step, last_step, cfg, sampler_name, scheduler, denoise, image_output, link_id, save_prefix, tile_size, prompt, extra_pnginfo, my_unique_id, preview_latent, force_full_denoise, disable_noise, samp_custom) File "/root/ComfyUI/custom_nodes/ComfyUI-Easy-Use/py/easyNodes.py", line 5131, in process_sample_state samp_samples, _ = sampler.custom_advanced_ksampler(noise, guider, _sampler, sigmas, samp_samples) File "/root/ComfyUI/custom_nodes/ComfyUI-Easy-Use/py/libs/sampler.py", line 182, in custom_advanced_ksampler samples = guider.sample(noise.generate_noise(latent), latent_image, sampler, sigmas, denoise_mask=noise_mask, File "/root/ComfyUI/comfy/samplers.py", line 716, in sample output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed) File "/root/ComfyUI/comfy/samplers.py", line 695, in inner_sample samples = sampler.sample(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar) File "/root/ComfyUI/comfy/samplers.py", line 600, in sample samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options) File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context return func(*args, **kwargs) File "/root/ComfyUI/comfy/k_diffusion/sampling.py", line 143, in sample_euler denoised = model(x, sigma_hat * s_in, **extra_args) File "/root/ComfyUI/comfy/samplers.py", line 299, in **call** out = self.inner_model(x, sigma, model_options=model_options, seed=seed) File "/root/ComfyUI/comfy/samplers.py", line 682, in **call** return self.predict_noise(*args, **kwargs) File "/root/ComfyUI/comfy/samplers.py", line 685, in predict_noise return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed) File "/root/ComfyUI/comfy/samplers.py", line 279, in sampling_function out = calc_cond_batch(model, conds, x, timestep, model_options) File "/root/ComfyUI/custom_nodes/ComfyUI-TiledDiffusion/.patches.py", line 4, in calc_cond_batch return calc_cond_batch_original_tiled_diffusion_7732be64(model, conds, x_in, timestep, model_options) File "/root/ComfyUI/comfy/samplers.py", line 228, in calc_cond_batch output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks) File "/root/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet/adv_control/utils.py", line 64, in apply_model_uncond_cleanup_wrapper return orig_apply_model(self, *args, **kwargs) File "/root/ComfyUI/comfy/model_base.py", line 145, in apply_model model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float() File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "/root/ComfyUI/comfy/ldm/flux/model.py", line 150, in forward out = self.forward_orig(img, img_ids, context, txt_ids, timestep, y, guidance, control) File "/root/ComfyUI/comfy/ldm/flux/model.py", line 104, in forward_orig img = self.img_in(img) File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "/root/ComfyUI/custom_nodes/ComfyUI-Easy-Use/py/bitsandbytes_NF4/**init**.py", line 155, in forward return functional_linear_4bits(x, self.weight, self.bias) File "/root/ComfyUI/custom_nodes/ComfyUI-Easy-Use/py/bitsandbytes_NF4/**init**.py", line 21, in functional_linear_4bits out = bnb.matmul_4bit(x, weight.t(), bias=bias, quant_state=weight.quant_state) File "/root/miniconda3/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py", line 579, in matmul_4bit return MatMul4Bit.apply(A, B, out, bias, quant_state) File "/root/miniconda3/lib/python3.10/site-packages/torch/autograd/function.py", line 539, in apply return super().apply(*args, **kwargs) # type: ignore[misc] File "/root/miniconda3/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py", line 509, in forward output = torch.nn.functional.linear(A, F.dequantize_4bit(B, quant_state).to(A.dtype).t(), bias) File "/root/miniconda3/lib/python3.10/site-packages/bitsandbytes/functional.py", line 1347, in dequantize_4bit absmax = dequantize_blockwise(quant_state.absmax, quant_state.state2) File "/root/miniconda3/lib/python3.10/site-packages/bitsandbytes/functional.py", line 977, in dequantize_blockwise lib.cdequantize_blockwise_fp32(文件“/root/ComfyUI/execution.py”，第 152 行，recursive_execute output_data output_ui = get_output_data（obj， input_data_all） 文件“/root/ComfyUI/execution.py”，第 82 行，get_output_data return_values = map_node_over_list（obj， input_data_all， obj.FUNCTION，allow_interrupt=True） 文件“/root/ComfyUI/execution.py”，第 75 行，map_node_over_list results.append（getattr（obj， func）（**slice_dict（input_data_all， i））） 文件“/root/ComfyUI/custom_nodes/ComfyUI-Easy-Use/py/easyNodes.py”，第 5392 行，简单返回 super（）.run（pipe， None， None， None， None， None， None， image_output， link_id， save_prefix， 文件“/root/ComfyUI/custom_nodes/ComfyUI-Easy-Use/py/easyNodes.py”， 行 5361， 在运行返回 process_sample_state（管道、samp_model、samp_clip、samp_samples、samp_vae、samp_seed、samp_positive、samp_negative、步骤、start_step、last_step、cfg、sampler_name、调度器、去噪、image_output、link_id、save_prefix、tile_size、提示、extra_pnginfo、my_unique_id、preview_latent、force_full_denoise、disable_noise、samp_custom） 文件“/root/ComfyUI/custom_nodes/ComfyUI-Easy-Use/py/easyNodes.py”， 第 5131 行，process_sample_state samp_samples中，_ = sampler.custom_advanced_ksampler（噪声、引导器、_sampler、sigmas、samp_samples） 文件“/root/ComfyUI/custom_nodes/ComfyUI-Easy-Use/py/libs/sampler.py”，第 182 行，custom_advanced_ksampler个样本 = guider.sample（noise.generate_noise（潜在）， latent_image，采样器，sigmas，denoise_mask=noise_mask，文件“/root/ComfyUI/comfy/samplers.py”，第 716 行，在样本输出中 = self.inner_sample（noise， latent_image、设备、采样器、sigmas、denoise_mask、回调、disable_pbar、种子） 文件“/root/ComfyUI/comfy/samplers.py”，第 695 行，inner_sample样本 = 采样器。sample（self， sigmas， extra_args， callback， noise， latent_image， denoise_mask， disable_pbar） 文件“/root/ComfyUI/comfy/samplers.py”，第 600 行，在样本中 samples = self.sampler_function（model_k， noise， sigmas， extra_args=extra_args， callback=k_callback， disable=disable_pbar， **self.extra_options） 文件“/root/miniconda3/lib/python3.10/site-packages/torch/utils/contextlib.py”，第 115 行，decorate_context返回 func（*args， **kwargs） 文件“/root/ComfyUI/comfy/k_diffusion/sampling.py”，第 143 行，在sample_euler中 去噪 = model（x， sigma_hat * s_in， **extra_args） 文件“/root/ComfyUI/comfy/samplers.py”，第 299 行，在调用输出 = self.inner_model（x， sigma， model_options=model_options， seed=seed） 文件“/root/ComfyUI/comfy/samplers.py”， 第 682 行，在调用返回 self.predict_noise（*args， **kwargs） 文件“/root/ComfyUI/comfy/samplers.py”， 第 685 行，在 predict_noise 返回 sampling_function（self.inner_model， x， timestep， self.conds.get（“negative”， None）， self.conds.get（“positive”， None）， self.cfg， model_options=model_options， seed=seed） 文件 “/root/ComfyUI/comfy/samplers.py”，第 279 行，输入sampling_function输出 = calc_cond_batch（model， conds， x， timestep， model_options） 文件 “/root/ComfyUI/custom_nodes/ComfyUI-TiledDiffusion/.patches.py”，第 4 行，calc_cond_batch返回calc_cond_batch_original_tiled_diffusion_7732be64（模型、条件、x_in、时间步长、model_options） 文件“/root/ComfyUI/comfy/samplers.py”，第 228 行，calc_cond_batch输出 = model.apply_model（input_x，timestep，**c）.chunk（batch_chunks） 文件“/root/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet/adv_control/utils.py”，第 64 行，apply_model_uncond_cleanup_wrapper返回orig_apply_model（self， *args， **kwargs） 文件“/root/ComfyUI/comfy/model_base.py”， 第 145 行，apply_model model_output = 自我。diffusion_model（xc， t， context=context， control=control， transformer_options=transformer_options， **extra_conds）.float（） 文件“/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py”，第 1518 行，在_wrapped_call_impl返回 self._call_impl（*args， **kwargs） 文件“/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py”，第 1527 行，_call_impl返回 forward_call（*args， **kwargs） 文件“/root/ComfyUI/comfy/ldm/flux/model.py”，第 150 行，输入转发输出 = self.forward_orig（img、img_ids、上下文、txt_ids、timestep、y、guidance、control） 文件“/root/ComfyUI/comfy/ldm/flux/model.py”，第 104 行，forward_orig img = self.img_in（img） 文件“/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py”，第 1518 行，_wrapped_call_impl返回 self._call_impl（*args， **kwargs） 文件“/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py”，第 1527 行，_call_impl返回forward_call（*args， **kwargs） 文件“/root/ComfyUI/custom_nodes/ComfyUI-Easy-Use/py/bitsandbytes_NF4/init.py”，第 155 行，前向返回 functional_linear_4bits（x， self.weight， self.bias） 文件“/root/ComfyUI/custom_nodes/ComfyUI-Easy-Use/py/bitsandbytes_NF4/init.py”，第 21 行，输入functional_linear_4bits输出 = bnb.matmul_4bit（x， weight.t（）， bias=bias， quant_state=weight.quant_state） 文件 “/root/miniconda3/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py”， line 579， in matmul_4bit return MatMul4Bit.apply（A， B， out， bias， quant_state） 文件 “/root/miniconda3/lib/python3.10/site-packages/torch/autograd/function.py”， line 539， in apply return super（）.apply（*args， **kwargs） # type： ignore[misc] 文件 “/root/miniconda3/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py”， 第 509 行，在正向输出中 = torch.nn.functional.linear（A， F.dequantize_4bit（B， quant_state）.to（A.dtype）.t（）， bias） 文件“/root/miniconda3/lib/python3.10/site-packages/bitsandbytes/functional.py”，第 1347 行，dequantize_4bit absmax = dequantize_blockwise（quant_state.absmax， quant_state.state2） 文件“/root/miniconda3/lib/python3.10/site-packages/bitsandbytes/functional.py”，第 977 行，dequantize_blockwise库。cdequantize_blockwise_fp32（
> 
> Has ComfyUI been updated yet? ComfyUI更新了吗？

Yes!ComfyUI version detail：
ComfyUI: 2534[3e52e0](2024-08-13)
Manager: V2.48.4

**Comment by yincangshiwei** [comment]
> > > model_override is missing!.
> > > Look at #303
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/8185843/358102546-af331382-84bc-49b2-92fe-c77780e0789d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2OTUyNjUsIm5iZiI6MTcyMzY5NDk2NSwicGF0aCI6Ii84MTg1ODQzLzM1ODEwMjU0Ni1hZjMzMTM4Mi04NGJjLTQ5YjItOTJmZS1jNzc3ODBlMDc4OWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTVUMDQwOTI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTFjYjM2NjY2NWMxYTRiYmY5MjNjMGM0MDJmNTU3YWFhMzgwZWQxZWEwNjliMmMxNTM2ZGIzOWEzZmI2ZDI2MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6nueXh-p7VQeCjZfGuXU2yzZ13bWc565Z0ScL1txcpA)
> > Error occurred when executing easy kSampler:
> > 'NoneType' object has no attribute 'cdequantize_blockwise_fp32'
> > File "/root/ComfyUI/execution.py", line 152, in recursive_execute output_data, output_ui = get_output_data(obj, input_data_all) File "/root/ComfyUI/execution.py", line 82, in get_output_data return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True) File "/root/ComfyUI/execution.py", line 75, in map_node_over_list results.append(getattr(obj, func)(**slice_dict(input_data_all, i))) File "/root/ComfyUI/custom_nodes/ComfyUI-Easy-Use/py/easyNodes.py", line 5392, in simple return super().run(pipe, None, None, None, None, None, image_output, link_id, save_prefix, File "/root/ComfyUI/custom_nodes/ComfyUI-Easy-Use/py/easyNodes.py", line 5361, in run return process_sample_state(pipe, samp_model, samp_clip, samp_samples, samp_vae, samp_seed, samp_positive, samp_negative, steps, start_step, last_step, cfg, sampler_name, scheduler, denoise, image_output, link_id, save_prefix, tile_size, prompt, extra_pnginfo, my_unique_id, preview_latent, force_full_denoise, disable_noise, samp_custom) File "/root/ComfyUI/custom_nodes/ComfyUI-Easy-Use/py/easyNodes.py", line 5131, in process_sample_state samp_samples, _ = sampler.custom_advanced_ksampler(noise, guider, _sampler, sigmas, samp_samples) File "/root/ComfyUI/custom_nodes/ComfyUI-Easy-Use/py/libs/sampler.py", line 182, in custom_advanced_ksampler samples = guider.sample(noise.generate_noise(latent), latent_image, sampler, sigmas, denoise_mask=noise_mask, File "/root/ComfyUI/comfy/samplers.py", line 716, in sample output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed) File "/root/ComfyUI/comfy/samplers.py", line 695, in inner_sample samples = sampler.sample(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar) File "/root/ComfyUI/comfy/samplers.py", line 600, in sample samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options) File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context return func(*args, **kwargs) File "/root/ComfyUI/comfy/k_diffusion/sampling.py", line 143, in sample_euler denoised = model(x, sigma_hat * s_in, **extra_args) File "/root/ComfyUI/comfy/samplers.py", line 299, in **call** out = self.inner_model(x, sigma, model_options=model_options, seed=seed) File "/root/ComfyUI/comfy/samplers.py", line 682, in **call** return self.predict_noise(*args, **kwargs) File "/root/ComfyUI/comfy/samplers.py", line 685, in predict_noise return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed) File "/root/ComfyUI/comfy/samplers.py", line 279, in sampling_function out = calc_cond_batch(model, conds, x, timestep, model_options) File "/root/ComfyUI/custom_nodes/ComfyUI-TiledDiffusion/.patches.py", line 4, in calc_cond_batch return calc_cond_batch_original_tiled_diffusion_7732be64(model, conds, x_in, timestep, model_options) File "/root/ComfyUI/comfy/samplers.py", line 228, in calc_cond_batch output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks) File "/root/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet/adv_control/utils.py", line 64, in apply_model_uncond_cleanup_wrapper return orig_apply_model(self, *args, **kwargs) File "/root/ComfyUI/comfy/model_base.py", line 145, in apply_model model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float() File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "/root/ComfyUI/comfy/ldm/flux/model.py", line 150, in forward out = self.forward_orig(img, img_ids, context, txt_ids, timestep, y, guidance, control) File "/root/ComfyUI/comfy/ldm/flux/model.py", line 104, in forward_orig img = self.img_in(img) File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "/root/ComfyUI/custom_nodes/ComfyUI-Easy-Use/py/bitsandbytes_NF4/**init**.py", line 155, in forward return functional_linear_4bits(x, self.weight, self.bias) File "/root/ComfyUI/custom_nodes/ComfyUI-Easy-Use/py/bitsandbytes_NF4/**init**.py", line 21, in functional_linear_4bits out = bnb.matmul_4bit(x, weight.t(), bias=bias, quant_state=weight.quant_state) File "/root/miniconda3/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py", line 579, in matmul_4bit return MatMul4Bit.apply(A, B, out, bias, quant_state) File "/root/miniconda3/lib/python3.10/site-packages/torch/autograd/function.py", line 539, in apply return super().apply(*args, **kwargs) # type: ignore[misc] File "/root/miniconda3/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py", line 509, in forward output = torch.nn.functional.linear(A, F.dequantize_4bit(B, quant_state).to(A.dtype).t(), bias) File "/root/miniconda3/lib/python3.10/site-packages/bitsandbytes/functional.py", line 1347, in dequantize_4bit absmax = dequantize_blockwise(quant_state.absmax, quant_state.state2) File "/root/miniconda3/lib/python3.10/site-packages/bitsandbytes/functional.py", line 977, in dequantize_blockwise lib.cdequantize_blockwise_fp32(
> 
> Has ComfyUI been updated yet?

I just need to update it again
