### ISSUE TITLE
希望可以在loader comfy里面增加 positive weight normalization

### ISSUE THREAD

**Issue by whmc76** [yolain/ComfyUI-Easy-Use#31]
这个原因主要是因为使用full loader的时候我使用 everywhere 绑定模型输出的时候会和输入的三个override有loop冲突，但是comfy loader里面却没有positive weight normalization 用起来有点难受

**Comment by yolain** [comment]
不太会去加上这个，需要token_normalization 还是得用 完整版的Loader。你就在加载个checkpoint选择器吧，也只会读取一次模型，不会再读节点上的那个ckpt。

**Comment by whmc76** [comment]
> 不太会去加上这个，需要token_normalization 还是得用 完整版的Loader。你就在加载个checkpoint选择器吧，也只会读取一次模型，不会再读节点上的那个ckpt。

好吧 这个办法也不是太糟糕
