### ISSUE TITLE
拖拽搜索的功能能不能改改啊

### ISSUE THREAD

**Issue by jckwanghui** [yolain/ComfyUI-Easy-Use#311]
![屏幕截图 2024-08-16 111349](https://github.com/user-attachments/assets/3b212638-27da-49c8-9c4f-422334b3ecbc)
拖拽后就弹出搜索框，好不习惯。能不能和以前一样，通过右键菜单自己查找？

**Comment by yolain** [comment]
> ![屏幕截图 2024-08-16 111349](https://private-user-images.githubusercontent.com/126385840/358456826-3b212638-27da-49c8-9c4f-422334b3ecbc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3NzkyMzUsIm5iZiI6MTcyMzc3ODkzNSwicGF0aCI6Ii8xMjYzODU4NDAvMzU4NDU2ODI2LTNiMjEyNjM4LTI3ZGEtNDljOC05YzRmLTQyMjMzNGIzZWNiYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNlQwMzI4NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZmM0MjAzMWUxZTM0MTBmMjZjZDUxOTlmMzJiODUxZWZiMGQ0ODg2OTU1ZWNkYzQ1MGUwYzAwMmEyMzM0ZGUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bM8uPCCYKEdqwdEGw3pOyxSaT8hrmOHAySGjLX2WHCU) 拖拽后就弹出搜索框，好不习惯。能不能和以前一样，通过右键菜单自己查找？

设置中可以调回 原始的搜索框的。

**Comment by jckwanghui** [comment]
设置里面没找到，试了半天了。能告知哪里调吗？comfyui还是easyuse节点？
![无标题](https://github.com/user-attachments/assets/b73c187d-fb21-4d9d-89d1-0367303575e6)

**Comment by yolain** [comment]
<img width="1019" alt="截屏2024-08-16 11 44 54" src="https://github.com/user-attachments/assets/8353cc99-35b2-4ea4-9650-1d4c27cacfb4">
