### ISSUE TITLE
Groups Map missing, update: 6bce707

### ISSUE THREAD

**Issue by Orenji-Tangerine** [yolain/ComfyUI-Easy-Use#312]
Groups Map is missing after update.

**Comment by czcz1024** [comment]
同问，comfy新ui自带的不能排序，不能goto，没你这个好用，但是更新到最新版后，这个功能没有了

**Comment by yolain** [comment]
> 同问，comfy新ui自带的不能排序，不能goto，没你这个好用，但是更新到最新版后，这个功能没有了

在侧边栏呢，需要new menu调整到上方。 默认布局的我晚点适配下

**Comment by Shingkyo** [comment]
Still using the older UI, the new UI looks messy... Will this Groups Map be added back to the context menu?

**Comment by yolain** [comment]
> Still using the older UI, the new UI looks messy... Will this Groups Map be added back to the context menu?

Yes, but it may not appear in the context menu anymore. I'm adding the toolbar to the bottom left, you can also use this feature when the new menu is disabled.

**Comment by czcz1024** [comment]
> > 同问，comfy新ui自带的不能排序，不能goto，没你这个好用，但是更新到最新版后，这个功能没有了
> 
> 在侧边栏呢，需要new menu调整到上方。 默认布局的目前还没适配。
> 
> The groups map has been renamed to the nodes map and added on the new sidebar menu. The default menu layout has not been adapted yet.

啊，我以为侧边栏这个是comfy新ui自带的，这个新的现在不能拖动排序了是么？

**Comment by Shingkyo** [comment]
![Screenshot_20240822_221413.jpg](https://github.com/user-attachments/assets/12a06bc8-75f3-4f44-9332-cc90212a5149)

Hi, how do I get this option? I can't seem to find this.

**Comment by sanhedasheng** [comment]
nodes map  没以前 group map 好用。    group map 点一下直接点开关。 而group map 点击后占了一屏，  要关掉还得再去点nodes map 的图标，很不方便。     不过，nodes map 可以展开所有节点，看起来很方便，没实际使用过， 我估计具体每个节点去找不方便。

**Comment by Orenji-Tangerine** [comment]
> nodes map 没以前 group map 好用。 group map 点一下直接点开关。 而node map 点击后占了一屏， 要关掉还得再去点nodes map 的图标，很不方便。 不过，nodes map 可以展开所有节点，看起来很方便，没实际使用过， 我估计具体每个节点去找不方便。

用在怀念中，哈哈，没办法，只能试着去适应了
