### ISSUE TITLE
Save/Load disabled with the new ComfyUI update

### ISSUE THREAD

**Issue by DeepSeaCatz** [yolain/ComfyUI-Easy-Use#315]
There seems to be a conflict between the new update of ComfyUI and this custom node. Both dropdown arrows next to Save and Load of the right panel are disabled:
![image](https://github.com/user-attachments/assets/50084812-6179-4ee5-8742-1265951666fd)

I believe the Load arrow is from the pythongosssss custom node:
https://github.com/pythongosssss/ComfyUI-Custom-Scripts?tab=readme-ov-file#workflows

In previous updates, both custom nodes worked fine together. I don't see any error message in the console either.

Also, when updating ComfyUI, I had to uninstall and re-install the node, otherwise, it couldn't fetch it properly in the manager. Currently, I need to disable the Easy-Use nodes to access my workflows.

**Comment by yolain** [comment]
Ok，I'm working on fixing that.

**Comment by DeepSeaCatz** [comment]
If it helps funnel the issue, I realized all menus where there's a dropdown, like load checkpoints/lora are disabled and won't open.

**Comment by yolain** [comment]
> If it helps funnel the issue, I realized all menus where there's a dropdown, like load checkpoints/lora are disabled and won't open.

issue associated with custom_scripts have been resolved. You just need to update easyuse to the latest.

**Comment by DeepSeaCatz** [comment]
> > If it helps funnel the issue, I realized all menus where there's a dropdown, like load checkpoints/lora are disabled and won't open.
> 
> issue associated with custom_scripts have been resolved. You just need to update easyuse to the latest.

Works now! Thanks!
