### ISSUE TITLE
看起来sampler full的两个condition输入会覆盖前面pipe连接的controlnet设置？

### ISSUE THREAD

**Issue by whmc76** [yolain/ComfyUI-Easy-Use#32]
看起来sampler full的两个condition输入会覆盖前面pipe连接的controlnet设置
抱歉这个问题看起来有些初级，但是我经常因为不知道什么时候输入会加入管道 ，什么时候是覆盖管道，什么时候是一次性使用的，而花很多时间去实验，希望可以请教一下谢谢

**Comment by yolain** [comment]
没关系。 加入管道的只有节点中的选项，其他的连入都会覆盖。这边的所有节点基本除了pipe 其他都是可选输入，输入即覆盖pipe中的参数（如果pipe里存在）。  pipe 中一般存了 模型，正向条件，反向条件，VAE， CLIP，潜空间，随机种这几个基本参数。 （如：controlnet的输出是正反向条件，ipadpter、lora的输出是model）
