### ISSUE TITLE
Auto nest subdirectories is enabled by default

### ISSUE THREAD

**Issue by christian-byrne** [yolain/ComfyUI-Easy-Use#322]
It looks like this setting is supposed to be disabled by default

https://github.com/yolain/ComfyUI-Easy-Use/blob/4608de5cbf29d74a806a4687eb5dc51eda3af11b/web_version/v1/js/easy/easyContextMenu.js#L9-L17

But on the new frontend it starts in enabled state. Some people confused:

- Comfy-Org/ComfyUI_frontend#480

**Comment by yolain** [comment]
Auto nest subdirectories is now disabled by default.

**Comment by christian-byrne** [comment]
Thanks yolain
