### ISSUE TITLE
XY-plot bug

### ISSUE THREAD

**Issue by cardenluo** [yolain/ComfyUI-Easy-Use#33]
![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/133877069/5f9fe775-e3f4-4f8a-b5e4-41cc633e28df)

**Comment by yolain** [comment]
需要变动一下XYPLOT前节点的数值可恢复正常，不太好解决（由于这边把XYPLOT写进节点束了，prompt没有变动它自动读取之前的节点束的内容了，如果设定为PIPE和XYPLOT必须同时存在是可以 但是会影响快捷用法和XYPlot高级用法）

**Comment by yolain** [comment]
算了 我判断有没有存在XYPLOT节点吧，下次更新的时候就可以了，只要连节点束就可以了，ouputs里那个xyplot没有什么用了

**Comment by cardenluo** [comment]
你这xyplot很好用呀，比Tiny的好用，可以下拉快速选择

**Comment by forfai** [comment]
好像现在xy都用不了了。
Error occurred when executing easy kSamplerTiled:
'FreeTypeFont' object has no attribute 'getsize'

**Comment by yolain** [comment]
> 好像现在xy都用不了了。
> 
> Error occurred when executing easy kSamplerTiled:
> 
> 'FreeTypeFont' object has no attribute 'getsize'

降一下pillow版本，不造你们装什么包把这个依赖版本升级了，昨天也有问到
可以看这个
https://blog.csdn.net/a1397852386/article/details/134475080

**Comment by forfai** [comment]
> > 好像现在xy都用不了了。
> > 执行 easy kSamplerTiled 时出错：
> > “FreeTypeFont”对象没有属性“getsize”
> 
> 降一下pillow版本，不造你们装什么包把这个依赖版本升级了，昨天也有问到 可以看这个 https://blog.csdn.net/a1397852386/article/details/134475080

我看了一下最近更新的插件，comfyui_controlnet_aux包含了这个依赖，可能是这个东西造成的。
