### ISSUE TITLE
请问有支持Long-CLIP吗，以增强提示词

### ISSUE THREAD

**Issue by yincangshiwei** [yolain/ComfyUI-Easy-Use#330]
最新这个作者的zer0int/ComfyUI-Long-CLIP，支持超长提示词文本并且有一定的增强，同时支持SD1.5,SDXL和flux。希望可以在EasyUse里面支持LongClip的使用。

**Comment by yolain** [comment]
咋关闭了 他这个有啥问题么

**Comment by yincangshiwei** [comment]
> 咋关闭了 他这个有啥问题么

没，是说能否把这玩意也整合进去，他这个可以把长文本限制提升到200多个字，并且对提示词出图效果有一定的提升。
