### ISSUE TITLE
comfyui版本更新到最新后，使用过fooocus提示词的工作流均出现了如图画面

### ISSUE THREAD

**Issue by xiao-ning-ning** [yolain/ComfyUI-Easy-Use#339]
![PixPin_2024-08-22_14-40-43](https://github.com/user-attachments/assets/87a28621-63a8-48bf-a155-0f44679d6485)

**Comment by xiao-ning-ning** [comment]
大佬救命

**Comment by yolain** [comment]
啊？😂回头看下. 本体退回版本正常么

**Comment by xiao-ning-ning** [comment]
退回旧版会正常，但是我需要新版的GGUF的支持😂

**Comment by yolain** [comment]
> 退回旧版会正常，但是我需要新版的GGUF的支持😂

gguf不是前几天的吗，不用退那么早

**Comment by xiao-ning-ning** [comment]
挨个尝试了一下，comfyui版本ID 510f3438c1fab09657061f966d8272327ea1fd42（2024-08-2110:53:26)，最后一个正常的版本，GGUF也可以使用

**Comment by yolain** [comment]
> 挨个尝试了一下，comfyui版本ID 510f3438c1fab09657061f966d8272327ea1fd42（2024-08-2110:53:26)，最后一个正常的版本，GGUF也可以使用

咋复现呢。我更到了最新 没有碰到这个问题啊。 你easyuse也是最新的吗？

**Comment by xiao-ning-ning** [comment]
全部都是最新版，不清楚发生的原因，我这边的情况是：新建的fooocus提示词节点正常，之前搭建的工作流发生了这种情况。我退回到旧版，删除fooocus提示词节点后，更新到最新版，重新添加fooocus提示词节点，目前已经恢复正常。😂

**Comment by yolain** [comment]
> 全部都是最新版，不清楚发生的原因，我这边的情况是：新建的fooocus提示词节点正常，之前搭建的工作流发生了这种情况。我退回到旧版，删除fooocus提示词节点后，更新到最新版，重新添加fooocus提示词节点，目前已经恢复正常。😂

好的，感谢反馈。后面我再留意看看。

**Comment by xiao-ning-ning** [comment]
复现方式：更新到comfyui最新版，在工作流中添加“风格提示词选择器”，折叠节点，保存工作流，关闭工作流，重新读取工作流，就会出现如图情形。

**Comment by yolain** [comment]
> 复现方式：更新到comfyui最新版，在工作流中添加“风格提示词选择器”，折叠节点，保存工作流，关闭工作流，重新读取工作流，就会出现如图情形。

那我只能让它默认载入时自动展开了，折叠状态的时候绑定不进去

**Comment by xiao-ning-ning** [comment]
好的，谢谢赛博佛祖😂
