### ISSUE TITLE
风格文件建议

### ISSUE THREAD

**Issue by fs920105** [yolain/ComfyUI-Easy-Use#34]
很高兴你的节点能支持风格选择。
希望改进风格文件自定义，其实不用把他整合进一个文件，要不下滑滚轮时间太长，把他们分在一个文件夹内的json文件，这样也可以自己添加json风格文件。比如我主要是出动漫风格的，我会把fooo的描述词关于照片和3D的部分去掉，如果修改原版的json文件，这样每次修改都需要备份，时间长了也容易忘记当初为什么备份这一份了。直接访问文件下的所有json文件会方便一些。
![119182441](https://github.com/yolain/ComfyUI-Easy-Use/assets/135109872/537ecd1a-3418-4a6e-91b9-030a665f0eeb)

**Comment by fs920105** [comment]
风格负面提示词会打乱权重。
![203717](https://github.com/yolain/ComfyUI-Easy-Use/assets/135109872/14c544ba-b811-4d97-a7cf-ceb9971d472d)

**Comment by yolain** [comment]
> 很高兴你的节点能支持风格选择。
> 
> 希望改进风格文件自定义，其实不用把他整合进一个文件，要不下滑滚轮时间太长，把他们分在一个文件夹内的json文件，这样也可以自己添加json风格文件。比如我主要是出动漫风格的，我会把fooo的描述词关于照片和3D的部分去掉，如果修改原版的json文件，这样每次修改都需要备份，时间长了也容易忘记当初为什么备份这一份了。直接访问文件下的所有json文件会方便一些。
> 
> ![119182441](https://github.com/yolain/ComfyUI-Easy-Use/assets/135109872/537ecd1a-3418-4a6e-91b9-030a665f0eeb)
> 
> 

你可以自己定义 放到styles底下 类似我resources里面的fooocus_styles.json格式。 json文件名包含styles即可

**Comment by yolain** [comment]
> 风格负面提示词会打乱权重。
> 
> ![203717](https://github.com/yolain/ComfyUI-Easy-Use/assets/135109872/14c544ba-b811-4d97-a7cf-ceb9971d472d)
> 
> 

做了去重的原因，我后面考虑一下有没有更好的解决方案。

**Comment by fs920105** [comment]
是这样吗？我放过，识别不到
![20002151](https://github.com/yolain/ComfyUI-Easy-Use/assets/135109872/320ed158-9ac1-4a0e-9775-6fd8f1a7dd33)

**Comment by fs920105** [comment]
> > 风格负面提示词会打乱权重。
> > ![203717](https://private-user-images.githubusercontent.com/135109872/298068299-14c544ba-b811-4d97-a7cf-ceb9971d472d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2ODI0MzYsIm5iZiI6MTcwNTY4MjEzNiwicGF0aCI6Ii8xMzUxMDk4NzIvMjk4MDY4Mjk5LTE0YzU0NGJhLWI4MTEtNGQ5Ny1hN2NmLWNlYjk5NzFkNDcyZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOVQxNjM1MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMjYwZTBkYzMyYTYyMWY1N2EyZmI2ZDc1NDlmZGNiZjg2NjhiMGVhNDdkMmI4Y2NjNjdkMmEwMzRmZjk5ZTZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wnzTxPXJ8GpwEoGQ2cw1QSVpUv71O6jczTCodxCobnI)
> 
> 做了去重的原因，我后面考虑一下有没有更好的解决方案。

不知道这对处理重复有没有帮助，有时问问GTP或许会有头绪。
![0120004733](https://github.com/yolain/ComfyUI-Easy-Use/assets/135109872/50c2fd62-c5c2-4dce-96b4-9e386df6abf8)

**Comment by yolain** [comment]
> > > 风格负面提示词会打乱权重。
> 
> > > ![203717](https://private-user-images.githubusercontent.com/135109872/298068299-14c544ba-b811-4d97-a7cf-ceb9971d472d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2ODI0MzYsIm5iZiI6MTcwNTY4MjEzNiwicGF0aCI6Ii8xMzUxMDk4NzIvMjk4MDY4Mjk5LTE0YzU0NGJhLWI4MTEtNGQ5Ny1hN2NmLWNlYjk5NzFkNDcyZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOVQxNjM1MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMjYwZTBkYzMyYTYyMWY1N2EyZmI2ZDc1NDlmZGNiZjg2NjhiMGVhNDdkMmI4Y2NjNjdkMmEwMzRmZjk5ZTZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wnzTxPXJ8GpwEoGQ2cw1QSVpUv71O6jczTCodxCobnI)
> 
> > 
> 
> > 做了去重的原因，我后面考虑一下有没有更好的解决方案。
> 
> 
> 
> 不知道这对处理重复有没有帮助，有时问问GTP或许会有头绪。
> 
> ![0120004733](https://github.com/yolain/ComfyUI-Easy-Use/assets/135109872/50c2fd62-c5c2-4dce-96b4-9e386df6abf8)
> 
> 

感谢提供，这是比较常规的去重，不太适用SD。我的想法，应该需要首先对（）［］特殊符号的几种排列组合做进一步筛选。优先保留特殊符号内的完整性。

**Comment by yolain** [comment]
> 是这样吗？我放过，识别不到
> 
> ![20002151](https://github.com/yolain/ComfyUI-Easy-Use/assets/135109872/320ed158-9ac1-4a0e-9775-6fd8f1a7dd33)
> 
> 

是放在easy-use根目录下的styles文件夹下。 这里是节点包的资源文件 会受更新影响。

**Comment by fs920105** [comment]
> > 是这样吗？我放过，识别不到
> > ![20002151](https://private-user-images.githubusercontent.com/135109872/298132493-320ed158-9ac1-4a0e-9775-6fd8f1a7dd33.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2ODkzNDAsIm5iZiI6MTcwNTY4OTA0MCwicGF0aCI6Ii8xMzUxMDk4NzIvMjk4MTMyNDkzLTMyMGVkMTU4LTlhYzEtNGEwZS05Nzc1LTZmZDhmMWE3ZGQzMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOVQxODMwNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZjQ4NTgwMjNmZmNiYTU1ODI0OGVlZjFjMjgyNWIzZmQ3NDE1Y2MzYzAyNTBlNTdmYzIzYTUxNWQ2Y2Q3NzA3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ne0w2vjatbxOhKqygaJynv3w7YOjnvmRTDAuevwiPfs)
> 
> 是放在easy-use根目录下的styles文件夹下。这里是节点包的资源文件 会受更新影响。

原来是我放错了，现在可以了。
刚试了一下发现在一个栏目里选择一个后，再去其他栏选择就会清除已经选择的。其实可以在搜索栏下面让显示出来已经选择的不被刷新。
