### ISSUE TITLE
已关闭

### ISSUE THREAD

**Issue by BannyLon** [yolain/ComfyUI-Easy-Use#343]
我理解错了

**Comment by yolain** [comment]
左侧栏上方第三个小图标就是管理组

**Comment by BannyLon** [comment]
> 左侧栏上方第三个小图标就是管理组😂不是压在下面 是合到侧边菜单了

我知道，我的意思，comyui新的UI是设计了管理组这项功能，且放在了侧边栏第三个。而上图左侧我圈中的是插件ComfyUI-Easy-Use的功能，这两个不是一回事。以前插件ComfyUI-Easy-Use的设置项是有取消和放置左下角的设置功能，现在我是 没找到。

**Comment by BannyLon** [comment]
> 左侧栏上方第三个小图标就是管理组😂不是压在下面 是合到侧边菜单了

谢谢，我理解错了
