### ISSUE TITLE
希望在group map上增加调整排序和种子控制

### ISSUE THREAD

**Issue by whmc76** [yolain/ComfyUI-Easy-Use#35]
希望可以拖动或者手动排序group，这真的很重要哈哈
另外如果可以在这里增加一个global seed的控制箱就更好了 免得还要去找这个种子控制得节点在哪里，因为通常这两个都是搭配使用的，快速抽卡和高清放大分离执行

**Comment by yolain** [comment]
Groupmap 我想过这个问题，还没时间试。 1.0.3 有稍微调整了下排列顺序。 globalseed 不太好做在节点图以外，有个queue和prompt变化监听的关系。

**Comment by whmc76** [comment]
感谢大佬 期待技术突破
