### ISSUE TITLE
今天更新最新后，get node和set node都飙红了。

### ISSUE THREAD

**Issue by yincangshiwei** [yolain/ComfyUI-Easy-Use#355]
今天更新comfyui和easyuse后，easyuse的get和set都报红，然后无法add出来。
![image](https://github.com/user-attachments/assets/b1b15f7c-12dd-46a8-aa07-62f2a7c61b4f)
![kk-2024-08-29-17-02-45](https://github.com/user-attachments/assets/d7731559-ea9d-43e6-8301-f8f420f45002)

**Comment by yincangshiwei** [comment]
![image](https://github.com/user-attachments/assets/018f5312-9b5b-423e-8af2-1c40316c70e5)
前端页面报错。

**Comment by yolain** [comment]
不造哪个节点影响的。 我用mac环境最新的comfy和easy都正常。win的和你一样报错了。

**Comment by yolain** [comment]
修好了

**Comment by yincangshiwei** [comment]
> 修好了

好的，感谢！
