### ISSUE TITLE
flux里面有个guidance值，希望能在预设采样器里面加上这个值的填写。

### ISSUE THREAD

**Issue by yincangshiwei** [yolain/ComfyUI-Easy-Use#356]
在一些flux使用技巧里面发现，guidance这个值，可以很好的控制写实和非写实的效果，但我看EasyUse的预设采样器(custom)没有带上这个，希望能加上这玩意。
![image](https://github.com/user-attachments/assets/a28d8035-e709-430c-9733-8fd5a452b368)

**Comment by yolain** [comment]
嗯。我知道，我昨天就在考虑要不要加到loader上

**Comment by yincangshiwei** [comment]
> 嗯。我知道，我昨天就在考虑要不要加到loader上

对，加到loader那里比较好，原本就是loader flux。

**Comment by yolain** [comment]
会多占显存🥲 晕了。我跑第二张就闪退了。看来不能默认加上去啊。

**Comment by yincangshiwei** [comment]
> 会多占显存🥲 晕了。我跑第二张就闪退了。看来不能默认加上去啊。

可以搞个节点接进去么，有硬件条件的就使用。

**Comment by yolain** [comment]
> > 会多占显存🥲 晕了。我跑第二张就闪退了。看来不能默认加上去啊。
> 
> 
> 
> 可以搞个节点接进去么，有硬件条件的就使用。

不写在loader上的话多加个节点意义就不是很大了，可以配合pipeout pipein使

**Comment by yincangshiwei** [comment]
> > > 会多占显存🥲 晕了。我跑第二张就闪退了。看来不能默认加上去啊。
> > 
> > 
> > 可以搞个节点接进去么，有硬件条件的就使用。
> 
> 不写在loader上的话多加个节点意义就不是很大了，可以配合pipeout pipein使
我都没发现pipeout pipein可以连这个，我看下先。
