### ISSUE TITLE
ImageToMask node causes changes input tensor dimension

### ISSUE THREAD

**Issue by chflame163** [yolain/ComfyUI-Easy-Use#358]
The ImageToMask node causes a change in tensor dimension, while the official node does not

<img width="1255" alt="微信图片_20240830101420" src="https://github.com/user-attachments/assets/20e7039b-aa10-4502-bb97-48d17a514d45">

**Comment by yolain** [comment]
I can't quite remember which node needs it, the tensor is inconsistent because inputting to that node using the official node would report an error. Otherwise it wouldn't have written an extra node out.

**Comment by chflame163** [comment]
I see, so it seems that the correct usage of this node can be explained in the document. Dimensional changes may lead to unexpected events in subsequent processes  :)

**Comment by yolain** [comment]
> I see, so it seems that the correct usage of this node can be explained in the document. Dimension changes may lead to unexpected events in subsequent processes  :)

Okay！

**Comment by yolain** [comment]
I can't find the node associated with it, I just remember that it was something to do with mask ercode region or expansion or pasting region by was node suite. But I can run them with offcial node all fine now. The node was created last year, so maybe the problem has been solved with a version update. I may classify it as a deprecated node.

**Comment by chflame163** [comment]
> I can't find the node associated with it, I just remember that it was something to do with mask ercode region or expansion or pasting region by was node suite. But I can run them with official node all fine now. The node was created last year, so maybe the problem has been solved with a version update. I may classify it as a deprecated node.

Thanks!
