### ISSUE TITLE
two question,my sever is in autodl sever,not windows

### ISSUE THREAD

**Issue by silvbb** [yolain/ComfyUI-Easy-Use#36]
[ERROR] An error occurred while retrieving information for the 'easy stylesSelector' node.
Traceback (most recent call last):
  File "/root/ComfyUI/server.py", line 418, in get_object_info
    out[x] = node_info(x)
  File "/root/ComfyUI/server.py", line 396, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "/root/ComfyUI/custom_nodes/ComfyUI-Easy-Use/py/easyNodes.py", line 1331, in INPUT_TYPES
    for file_name in os.listdir(os.path.join(__file__, "../../styles")):
NotADirectoryError: [Errno 20] Not a directory: '/root/ComfyUI/custom_nodes/ComfyUI-Easy-Use/py/easyNodes.py/../../styles'
[ERROR] An error occurred while retrieving information for the 'TextToImage_AS' node.
Traceback (most recent call last):
  File "/root/ComfyUI/server.py", line 418, in get_object_info
    out[x] = node_info(x)
  File "/root/ComfyUI/server.py", line 396, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "/root/ComfyUI/custom_nodes/As_ComfyUI_CustomNodes/asnodes.py", line 189, in INPUT_TYPES
    fonts = os.listdir('C:\Windows\Fonts')
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Windows\\Fonts'
#read_workflow_json_files_all /root/ComfyUI/custom_nodes/comfyui-mixlab-nodes/app/

**Comment by yolain** [comment]
I think the issue might be that the autodl server doesn't have permission to create the folder via command. You can try to manually create a folder named "styles" in the root of "comfy-easy-use". The second problem comes from "As_ComfyUI_CustomNodes".

**Comment by silvbb** [comment]
i create a folder named "styles" in the root of "ComfyUI-Easy-Use". but i use easy use ,
All my other nodes can create folders. The problem is still not solved, and I don't know what files to put under the style folder. I opened a basic easyuse workflow, which alerted asnodes of the problem during initialization. I updated both easyuse and asnodes to the latest version.

**Comment by yolain** [comment]
you don't need to move any files to "styles". only the "As_ComfyUI_CustomNodes" issue remains, if the first issue doesn't report another error. you can either not use it or raise an issue on its gitHub repository

**Comment by DevDavid1307** [comment]
同样遇到了第一个问题，我的环境是在google cloud，我用os.path.isdir检测，打印的是False，我现在改了一下代码，运行成功了
![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/16041023/2a88113c-3cc0-432f-864b-a7876ac1e5dc)

**Comment by DevDavid1307** [comment]
同样遇到了第一个问题，我的环境是在google cloud，我用os.path.isdir检测，打印的是False，我现在改了一下代码，运行成功了
![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/16041023/38a9149a-467a-4ddf-9dc6-0eec83463f82)

**Comment by DevDavid1307** [comment]
> 同样遇到了第一个问题，我的环境是在google cloud，我用os.path.isdir检测，打印的是False，我现在改了一下代码，运行成功了 ![image](https://private-user-images.githubusercontent.com/16041023/298375593-38a9149a-467a-4ddf-9dc6-0eec83463f82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4MzI4MjcsIm5iZiI6MTcwNTgzMjUyNywicGF0aCI6Ii8xNjA0MTAyMy8yOTgzNzU1OTMtMzhhOTE0OWEtNDY3YS00ZGRmLTlkYzYtMGVlYzgzNDYzZjgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIxVDEwMjIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkODRlZDZjMWE4ZGZlZjg5NzM1ZDNlZDY1ZmIyYzQ4Zjc2YWRmNzE2MzlhMWYyZTMxODk4ZTA5YTc1YTVkOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BAU__WOOKQW76Qip1O038-cvj4HSnwY6tR52bKOK3fE)

我的环境是google cloud debian
