### ISSUE TITLE
set and get node bug?

### ISSUE THREAD

**Issue by K-O-N-B** [yolain/ComfyUI-Easy-Use#360]
1. 移动与get关联的节点，get会自动跳刀这个关联节点的旁边，摆好的get位置就乱了
2. get没有与set关联的线，无法溯源

**Comment by yolain** [comment]
1. 你可以在设置中禁用掉绑定 “Enable chain get node and set node with parent nodes” 
2. 没有做隐藏线。可以在选择get节点的时候，按键盘左键回到对应的set，反之按右键可以到get
