### ISSUE TITLE
bookmark失效

### ISSUE THREAD

**Issue by K-O-N-B** [yolain/ComfyUI-Easy-Use#363]
今天更新后，失效了

![image](https://github.com/user-attachments/assets/a98ac8eb-08e4-4698-93b0-d00925c8929f)

**Comment by Kimthanh27** [comment]
same error. very very frustrated after how many times updating, install.bat and reinstalling easy use. its difficult for users, it ain't easy at all

**Comment by yolain** [comment]
> same error. very very frustrated after how many times updating, install.bat and reinstalling easy use. its difficult for users, it ain't easy at all 

There is no way to keep up to date with the comfyui main core so synchronized updates, easyuse features are also a lot of the comfyui core changes will affect, it is recommended that there are problems when reback to the comfyui core revision first. I usually fix it within a day or two.

**Comment by yolain** [comment]
Fixed now.
