### ISSUE TITLE
loop -  total size -  can not be updated

### ISSUE THREAD

**Issue by mateng0716** [yolain/ComfyUI-Easy-Use#366]
![微信图片_20240902104740](https://github.com/user-attachments/assets/fa48a0bb-29d5-4dc4-a1b1-82e53a0ae82e)

loop start 的数值作为参数传入时， 不会每次根据 传入数值更新，  怀疑赋值一次后无法更新

**Comment by yolain** [comment]
easyuse是最新的么？我测了batch几张图片 获取count 走循环是没问题。重复获取也会赋值过去

**Comment by mateng0716** [comment]
> easyuse是最新的么？我测了batch几张图片 获取total 走循环是没问题。重复获取也会赋值过去。 是否是前面的节点没有发生变动， 然后就跳过了，你image前面的是什么。

一个 image batch  然后 get  image batchsize ， 只不过用了个  set  get 的节点传输

**Comment by yolain** [comment]
> > easyuse是最新的么？我测了batch几张图片 获取total 走循环是没问题。重复获取也会赋值过去。 是否是前面的节点没有发生变动， 然后就跳过了，你image前面的是什么。
> 
> 一个 image batch 然后 get image batchsize ， 只不过用了个 set get 的节点传输

试了 getset不影响呢。
