### ISSUE TITLE
提示词选择器导致网页FPS大幅降低

### ISSUE THREAD

**Issue by Xz3r0-M** [yolain/ComfyUI-Easy-Use#368]
视图中每多1个(从第2个开始),在拖动视图时就会降低10+FPS.
视图中如果同时出现10个那么拖动时FPS只有个位数.
折叠状态能稍微改善一些.
视图缩小到看不到节点内容时FPS最高(相对而言).

**Comment by yolain** [comment]
没感觉会掉帧，左下角FPS都在100多。。可能1000多个的话会。
一般一个工作流程中也不会太多的提示词选择器。

https://github.com/user-attachments/assets/3faca4f7-b4ab-460a-a746-aa57657531c8

**Comment by Xz3r0-M** [comment]
> 没感觉会掉帧，左下角FPS都在100多。。可能1000多个的话会。 一般一个工作流程中也不会太多的提示词选择器。
> 
>  default.mp4

是系统和浏览器的区别吗?
我用的win11和edge, 我工作流上百个节点, 只有这个会卡, 只要删掉这个FPS就比较正常, 空白工作流也是如此.

**Comment by yolain** [comment]
> > 没感觉会掉帧，左下角FPS都在100多。。可能1000多个的话会。 一般一个工作流程中也不会太多的提示词选择器。
> > default.mp4
> 
> 是系统和浏览器的区别吗? 我用的win11和edge, 我工作流上百个节点, 只有这个会卡, 只要删掉这个FPS就比较正常, 空白工作流也是如此.

用chrome看看。edge可能优化不是太好吧。我在win上也挺流畅的，但是这种html嵌入的节点也是最好一个流程不要用太多就是

**Comment by Xz3r0-M** [comment]
> > > 没感觉会掉帧，左下角FPS都在100多。。可能1000多个的话会。 一般一个工作流程中也不会太多的提示词选择器。
> > > default.mp4
> > 
> > 
> > 是系统和浏览器的区别吗? 我用的win11和edge, 我工作流上百个节点, 只有这个会卡, 只要删掉这个FPS就比较正常, 空白工作流也是如此.
> 
> 用chrome看看。edge可能优化不是太好吧。我在win上也挺流畅的，但是这种html嵌入的节点也是最好一个流程不要用太多就是

我试了两个浏览器, 我发现edge设置里的[优化性能]的几个功能会降低FPS, 关了之后和新装的默认chrome差不多, 甚至edge的FPS还高一丢丢, 我把浏览器的渲染模式改成了D3D11on12后FPS还能再高一点点, 改完这些FPS从10+到了40出头, 虽然和你视频里的情况差距还是挺大, 但也勉强够用了🥲.
