### ISSUE TITLE
ksample error fix, please fix it

### ISSUE THREAD

**Issue by G7b9** [yolain/ComfyUI-Easy-Use#370]
![image](https://github.com/user-attachments/assets/b6d04847-033a-41aa-ad91-f1b5657ba1ba)

**Comment by G7b9** [comment]
`if i not in control_output.keys():
    x = control_output['output'][i]
else:
    x = control_output[i]
`

**Comment by yolain** [comment]
It has nothing to do with easyuse

**Comment by G7b9** [comment]
Yes, updating the ComfyUI Advanced ControlNet can fix this.
