### ISSUE TITLE
模型加载那里，能够用树状形式展示和选择吗？

### ISSUE THREAD

**Issue by yincangshiwei** [yolain/ComfyUI-Easy-Use#375]
如题，发现EasyLoader里面，选择ckpt或者lora等模型不能以树状形式展示和选择，这是已经支持还是说还没支持？

**Comment by yolain** [comment]
<img width="957" alt="截屏2024-09-05 17 22 08" src="https://github.com/user-attachments/assets/9e0e0ba3-91e0-4204-bfb4-d8c0263657b7">

**Comment by yincangshiwei** [comment]
> <img alt="截屏2024-09-05 17 22 08" width="957" src="https://private-user-images.githubusercontent.com/73304135/364709741-9e0e0ba3-91e0-4204-bfb4-d8c0263657b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1NTM5NDgsIm5iZiI6MTcyNTU1MzY0OCwicGF0aCI6Ii83MzMwNDEzNS8zNjQ3MDk3NDEtOWUwZTBiYTMtOTFlMC00MjA0LWJmYjQtZDhjMDI2MzY1N2I3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDE2MjcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlNDY3YThkZWE1YzM5NTc1N2NlNTYwNmRkMTE3OGVkNTg1Nzk3NTE3NWQ2OTc0ODFjZjgyZjM2M2ZkYmY0NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CvRNtmXyeagkDnunyIO44IsiZxdRRqdBmDn66D8BGDs">
> Settings -> EasyUse -> Enable contextMenu auto nest subdirectories

ok,THANKS
