### ISSUE TITLE
New version of EasyUse prevents search from showing in comfyUI context menu

### ISSUE THREAD

**Issue by nux1111** [yolain/ComfyUI-Easy-Use#376]
I will appreciate if you can look into it but disabling easy use let's me have the search back in context menu.
![CleanShot 2024-09-07 at 12 24 59@2x](https://github.com/user-attachments/assets/ed5f6d78-8a6f-4e3e-aab1-d6bba6b53939)

**Comment by christian-byrne** [comment]
More context:

- Contextmenu (with "Search" entry) on link-release added here: Comfy-Org/ComfyUI_frontend#724 
- Associated Litegraph changes added here: Comfy-Org/litegraph.js#111

Related Issue:

- comfyanonymous/ComfyUI#4829

**Comment by yolain** [comment]
It is now fixed, just update easy-use to the latest version.

**Comment by flybirdxx** [comment]
> 现在已修复，只需将 easy-use 更新到最新版本即可。
![image](https://github.com/user-attachments/assets/44886f92-f36b-410a-b070-0f3b32d2b7a3)
Still no search item after update

**Comment by nux1111** [comment]
Thank you!
