### ISSUE TITLE
comfyui的object_info里没有select_styles，但是这个字段又是必传的，这让我的中转器很难受。

### ISSUE THREAD

**Issue by yu1ec** [yolain/ComfyUI-Easy-Use#384]
![image](https://github.com/user-attachments/assets/d064b6cf-52e6-4f5b-9bc8-8ff939184e47)
comfyui的object_info里扫不到select_styles这个字段的描述，但是经过ui那边数据提交上是带上的，导致我程序这边没法做拼接。

**Comment by yolain** [comment]
导出 跟导出api json 都是有的。

**Comment by yu1ec** [comment]
佬，我理解你意思，如果我全程用comfyui搞，是没毛病的，但其实我们做的是类似哩布哩布那种平台，是服务端通过api调用提交的prompt，而且中途对于某些值用户是可以自定义的，我这边要做替换，我看了api_json里确实有值，但是那些值是索引数组，没有key，所以，我还是要通过object_info里的定义去做关联。如果object_info里没有这个的话，那我要兼容这个节点，就只能在代码里写死了。主要是我没理解，这个节点信息是特意不加的嘛?

**Comment by yolain** [comment]
> 佬，我理解你意思，如果我全程用comfyui搞，是没毛病的，但其实我们做的是类似哩布哩布那种平台，是服务端通过api调用提交的prompt，而且中途对于某些值用户是可以自定义的，我这边要做替换，我看了api_json里确实有值，但是那些值是索引数组，没有key，所以，我还是要通过object_info里的定义去做关联。如果object_info里没有这个的话，那我要兼容这个节点，就只能在代码里写死了。主要是我没理解，这个节点信息是特意不加的嘛?

select_styles是从前端后加上去的。object_info应该是读不到吧。

**Comment by yolain** [comment]
异步从文件里获取的。完整的列表 在 /resources/fooocus_styles.json
