### ISSUE TITLE
text index switch

### ISSUE THREAD

**Issue by K-O-N-B** [yolain/ComfyUI-Easy-Use#387]
由于找不到说明文档，所以想问一下这个node的逻辑
是不是从0至最后，输入第一个有内容的text？那么下面的选择框有什么用？
![image](https://github.com/user-attachments/assets/cbae6cdd-1fed-453e-96d4-424f8a734138)

**Comment by yolain** [comment]
这个节点和 `easy anythingIndexSwitch` 一样适配了惰性求值

选择框 index 为0 时  输出的text 为text0结果，为1时 输出为text1结果， 
除被选择的项以外，其他输入索引前的节点将不会被执行。
