### ISSUE TITLE
切换节点的输入侧支持自定义名称

### ISSUE THREAD

**Issue by water110** [yolain/ComfyUI-Easy-Use#392]
![image](https://github.com/user-attachments/assets/15b36797-ab30-49ca-9738-04ed60e7e756)
![image](https://github.com/user-attachments/assets/2a854c69-623b-410d-983b-e49e6399e5dc)
有时输入条件太多时，无法分清具体哪个条件，希望可以支持自定义名称

**Comment by yolain** [comment]
> ![image](https://private-user-images.githubusercontent.com/29881977/368447408-15b36797-ab30-49ca-9738-04ed60e7e756.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NDMzNzEsIm5iZiI6MTcyNjY0MzA3MSwicGF0aCI6Ii8yOTg4MTk3Ny8zNjg0NDc0MDgtMTViMzY3OTctYWIzMC00OWNhLTk3MzgtMDRlZDYwZTdlNzU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDA3MDQzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkMGVkYTU2NDg2NzE2Y2Y1MjM1ZDIyMzcyYmJhN2M4YjliZTQxYmJiMTY3ZDgxYzkxM2U4ZTQ2NGJmZTIxYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UYblknBLaMgIkXmBm26C00U0_lNQTfhbJGyYBCDJ2UU) ![image](https://private-user-images.githubusercontent.com/29881977/368447577-2a854c69-623b-410d-983b-e49e6399e5dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NDMzNzEsIm5iZiI6MTcyNjY0MzA3MSwicGF0aCI6Ii8yOTg4MTk3Ny8zNjg0NDc1NzctMmE4NTRjNjktNjIzYi00MTBkLTk4M2ItZTQ5ZTYzOTllNWRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDA3MDQzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiZDNjN2E5NTUyZDkwOTUzMmYwYmJmMmNmMWZhYTdiYTljODM0OGI0YmY3Y2RlZTVkNDVlOWVlNjdlYmEyY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EJyV3EZQFhJCf0xVGlL0WnEsBReU2aRJ4tZeKSlbjsI) 有时输入条件太多时，无法分清具体哪个条件，希望可以支持自定义名称

新版本Comfy可以自定义呀,  在插槽小圆点右键就可以了
