### ISSUE TITLE
Flux的controlnet inpaint使用controlnet++怎么连

### ISSUE THREAD

**Issue by yincangshiwei** [yolain/ComfyUI-Easy-Use#398]
如题，阿里出了一个flux controlnet inpaint模型，用于flux重绘使用，阿里的官方节点mask这个输入，但EasyUse的controlnet里面没有这玩意。
![image](https://github.com/user-attachments/assets/9b4baffd-3d22-4f90-89b6-820b926941c6)

**Comment by yolain** [comment]
pipe in , pipe out, pipe edit

**Comment by yincangshiwei** [comment]
> pipe in , pipe out, pipe edit

太多线了，只是想说EasyUse有没有类似这种的整合节点。
