### ISSUE TITLE
节点建议

### ISSUE THREAD

**Issue by Walson23** [yolain/ComfyUI-Easy-Use#40]
建议把节点 预采样和采样变更成和COMFYUI保持一致，以免给新人造成困扰。采样种子COMFYUI更新后已可以通过菜单Widget Value Control Mode设置可以设置成前还是后，可设置成before固定种子数。

**Comment by fs920105** [comment]
直接解包接原版采样不就行了

**Comment by yolain** [comment]
> 建议把节点 预采样和采样变更成和COMFYUI保持一致，以免给新人造成困扰。采样种子COMFYUI更新后已可以通过菜单Widget Value Control Mode设置可以设置成前还是后，可设置成before固定种子数。

之前有测试过，官方更新的前生成无法兼容everywhere
