### ISSUE TITLE
应用ipadapter(区域)不支持kolors编码

### ISSUE THREAD

**Issue by liulsg** [yolain/ComfyUI-Easy-Use#407]
![image](https://github.com/user-attachments/assets/b4ea53fc-df3e-4329-a290-009e1fe451e0)

**Comment by yolain** [comment]
原版可以么

**Comment by liulsg** [comment]
> 原版可以么

我测试过，原版的可以。

**Comment by yolain** [comment]
> > 原版可以么
> 
> 我测试过，原版的可以。 1.测试步骤用easy先测试sdxl版本能跑通（测试通过）。 2.替换成kolors加载方式（不存在不熟练问题，每天都通过easy-kolors各种操作） 3.将ipadapter（区域）部分用mz插件编码则无问题。以下是跑通的图片 ![image](https://private-user-images.githubusercontent.com/97494068/371766729-f910d1a8-c804-44c7-b787-a4f41d6daa24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1MzU4NTgsIm5iZiI6MTcyNzUzNTU1OCwicGF0aCI6Ii85NzQ5NDA2OC8zNzE3NjY3MjktZjkxMGQxYTgtYzgwNC00NGM3LWI3ODctYTRmNDFkNmRhYTI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI4VDE0NTkxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhOWQ0MDZiOGU5MTUzMjc1YjA4MjI3ZDEzYjc4Y2Q0ZTI1ZTc1NjIyMjA4ODg5MDczNzhiMGExMzdmNDQ3NjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.x1inU-Iv6Z5N75qdi42SeV4XlRebowTzBu8tZRHNs4E)

应该是 regional  那个节点 没有做对 glm的适配。te还是普通clip的

**Comment by liulsg** [comment]
辛苦作者大大，能这么块的修复。
