### ISSUE TITLE
请问能把DragNUWA项目加入到easyuse里吗？

### ISSUE THREAD

**Issue by wujm424606** [yolain/ComfyUI-Easy-Use#41]
这是一个github上的一个项目[DragNUWA](https://github.com/chaojie/ComfyUI-DragNUWA)，但是缺少本地节点进行在图片上画线的功能，如果可以的话，请问能在这个基础上进行改进加整合一下吗？
![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/38379474/2ec28fbc-ad2b-44d2-8b86-6d4edb0dfc52)

**Comment by wujm424606** [comment]
如果可以的话，就太感谢作者了

**Comment by yolain** [comment]
现阶段应该不会有这个计划，等他完善吧，看那边issue貌似依赖问题也挺多的。 他这个如果用类似mask的那种展示方式可能会好些。
