### ISSUE TITLE
功能请求：“应用ipadapter（嵌入组）” 增加疯狂科学家权重

### ISSUE THREAD

**Issue by liulsg** [yolain/ComfyUI-Easy-Use#410]
@yolain 大大你好。
能为“应用ipadapter（嵌入组）”添加疯狂科学家权重功能吗？   如同“ipadapter(高级)”一样

![image](https://github.com/user-attachments/assets/33f8d2cb-88ea-4518-8068-f171355156eb)

**Comment by liulsg** [comment]
真的非常希望作者可以添加上权重功能，因为嵌入组包含了其他ipa的所用有功能，而其他的功能相对都比较分散。
如果能够添加上权重功能后，ipa的自由度会更高。

**Comment by yolain** [comment]
这是基于原版嵌套的，除非ipa作者那边有添加呢
