### ISSUE TITLE
Easy-Use兼容问题：越来越多模型花屏或黑图

### ISSUE THREAD

**Issue by freemde23** [yolain/ComfyUI-Easy-Use#414]
![2024-10-05_112538](https://github.com/user-attachments/assets/3256e964-e9f8-4e66-a136-fc5a97930df2)
之前发现少数如絮儿，waiCUTE等中国模型会出问题，但现在发现越来越多小马模型都出现问题（换系统默认加载和K采样节点就能很好出图）
希望尽快解决兼容问题

**Comment by yolain** [comment]
那你有没有发现默认加载和 easy 的加载器有哪个参数默认值是不同的。 pony模型有特殊设定呢

**Comment by freemde23** [comment]
![2024-10-11_154350](https://github.com/user-attachments/assets/30440f00-2ad3-418c-9927-009745fe89b0)
完全对比图，希望尽快解决兼容问题

**Comment by yolain** [comment]
> ![2024-10-11_154350](https://private-user-images.githubusercontent.com/122530501/375669909-30440f00-2ad3-418c-9927-009745fe89b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MzQ0NDcsIm5iZiI6MTcyODYzNDE0NywicGF0aCI6Ii8xMjI1MzA1MDEvMzc1NjY5OTA5LTMwNDQwZjAwLTJhZDMtNDE4Yy05OTI3LTAwOTc0NWZlODliMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMVQwODA5MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYzEzNTUwOWMzNjUyYmFmYzc1ZDkzNGY3Y2FlOTA3MTg5YmE5NTY4NmViMjdjNjUzYWEzMDE1YzUxMWRkMGUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.OAft_7xPO2oxheWgB_-ENuTISF0KyW1jsiHIRpdZUc0) 完全对比图，希望尽快解决兼容问题

没有兼容问题呢。那天是想告诉你，让你自己发现看看问题出在哪里。 XL的默认clip_skip是-2，pony只能在-2下是正常的。
