### ISSUE TITLE
INVALID SYNTAX

### ISSUE THREAD

**Issue by S0LTIS** [yolain/ComfyUI-Easy-Use#418]
D:\COMFYUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\libs\translate.py:188: SyntaxWarning: invalid escape sequence '\s'
  grammar = """
D:\COMFYUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py:1688: SyntaxWarning: invalid escape sequence '\.'
  pattern = 'sd2-1-open-clip|model\.(safetensors|bin)$'
D:\COMFYUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py:1700: SyntaxWarning: invalid escape sequence '\.'
  pattern = '(ViT.H.14.*s32B.b79K|ipadapter.*sd15|sd1.?5.*model|open_clip_pytorch_model\.(bin|safetensors))'
D:\COMFYUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py:1712: SyntaxWarning: invalid escape sequence '\.'
  pattern = 'vae-ft-mse-840000-ema-pruned\.(pt|bin|safetensors)$'
D:\COMFYUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py:2630: SyntaxWarning: invalid escape sequence '\.'
  pattern = 'brushnet.random.mask.sdxl.*\.(safetensors|bin)$'
D:\COMFYUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py:2632: SyntaxWarning: invalid escape sequence '\.'
  pattern = 'brushnet.random.mask.*\.(safetensors|bin)$'
D:\COMFYUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py:2636: SyntaxWarning: invalid escape sequence '\.'
  pattern = 'brushnet.segmentation.mask.sdxl.*\.(safetensors|bin)$'
D:\COMFYUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py:2638: SyntaxWarning: invalid escape sequence '\.'
  pattern = 'brushnet.segmentation.mask.*\.(safetensors|bin)$'
D:\COMFYUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py:2941: SyntaxWarning: invalid escape sequence '\.'
  pattern = 'Vit.Large.patch14.336\.(bin|safetensors)$'
D:\COMFYUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py:2943: SyntaxWarning: invalid escape sequence '\.'
  pattern = '(ViT.bigG.14.*39B.b160k|ipadapter.*sdxl|sdxl.*model\.(bin|safetensors))'
D:\COMFYUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py:2945: SyntaxWarning: invalid escape sequence '\.'
  pattern = '(ViT.H.14.*s32B.b79K|ipadapter.*sd15|sd1.?5.*model\.(bin|safetensors))'
D:\COMFYUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py:2964: SyntaxWarning: invalid escape sequence '\.'
  pattern = 'sd15.light.v11\.(safetensors|bin)$'
D:\COMFYUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py:2967: SyntaxWarning: invalid escape sequence '\.'
  pattern = 'sd15.light\.(safetensors|bin)$'
D:\COMFYUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py:2970: SyntaxWarning: invalid escape sequence '\.'
  pattern = 'ip.adapter.sdxl.vit.h\.(safetensors|bin)$'
D:\COMFYUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py:2972: SyntaxWarning: invalid escape sequence '\.'
  pattern = 'ip.adapter.sd15\.(safetensors|bin)$'
D:\COMFYUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py:2975: SyntaxWarning: invalid escape sequence '\.'
  pattern = 'ip.adapter.sdxl\.(safetensors|bin)$'
D:\COMFYUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py:2977: SyntaxWarning: invalid escape sequence '\.'
  pattern = 'sd15.vit.g\.(safetensors|bin)$'
D:\COMFYUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py:2980: SyntaxWarning: invalid escape sequence '\.'
  pattern = 'plus.sdxl.vit.h\.(safetensors|bin)$'
D:\COMFYUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py:2982: SyntaxWarning: invalid escape sequence '\.'
  pattern = 'ip.adapter.plus.sd15\.(safetensors|bin)$'
D:\COMFYUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py:2985: SyntaxWarning: invalid escape sequence '\.'
  pattern = 'plus.gener(nal|al)\.(safetensors|bin)$'
D:\COMFYUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py:2990: SyntaxWarning: invalid escape sequence '\.'
  pattern = 'plus.face.sdxl.vit.h\.(safetensors|bin)$'
D:\COMFYUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py:2992: SyntaxWarning: invalid escape sequence '\.'
  pattern = 'plus.face.sd15\.(safetensors|bin)$'
D:\COMFYUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py:2996: SyntaxWarning: invalid escape sequence '\.'
  pattern = 'full.face.sd15\.(safetensors|bin)$'
D:\COMFYUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py:2999: SyntaxWarning: invalid escape sequence '\.'
  pattern = 'plus.composition.sdxl\.(safetensors|bin)$'
D:\COMFYUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py:3001: SyntaxWarning: invalid escape sequence '\.'
  pattern = 'plus.composition.sd15\.(safetensors|bin)$'
D:\COMFYUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py:3004: SyntaxWarning: invalid escape sequence '\.'
  pattern = 'portrait.sdxl\.(safetensors|bin)$'
D:\COMFYUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py:3006: SyntaxWarning: invalid escape sequence '\.'
  pattern = 'portrait.v11.sd15\.(safetensors|bin)$'
D:\COMFYUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py:3009: SyntaxWarning: invalid escape sequence '\.'
  pattern = 'portrait.sd15\.(safetensors|bin)$'
D:\COMFYUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py:3019: SyntaxWarning: invalid escape sequence '\.'
  pattern = 'faceid.sdxl\.(safetensors|bin)$'
D:\COMFYUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py:3020: SyntaxWarning: invalid escape sequence '\.'
  lora_pattern = 'faceid.sdxl.lora\.safetensors$'
D:\COMFYUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py:3022: SyntaxWarning: invalid escape sequence '\.'
  pattern = 'faceid.sd15\.(safetensors|bin)$'
D:\COMFYUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py:3023: SyntaxWarning: invalid escape sequence '\.'
  lora_pattern = 'faceid.sd15.lora\.safetensors$'
D:\COMFYUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py:3027: SyntaxWarning: invalid escape sequence '\.'
  pattern = '(kolors.ip.adapter.faceid.plus|ipa.faceid.plus)\.(safetensors|bin)$'
D:\COMFYUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py:3034: SyntaxWarning: invalid escape sequence '\.'
  pattern = 'faceid.plus.sd15\.(safetensors|bin)$'
D:\COMFYUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py:3035: SyntaxWarning: invalid escape sequence '\.'
  lora_pattern = 'faceid.plus.sd15.lora\.safetensors$'
D:\COMFYUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py:3039: SyntaxWarning: invalid escape sequence '\.'
  pattern = 'faceid.plusv2.sdxl\.(safetensors|bin)$'
D:\COMFYUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py:3040: SyntaxWarning: invalid escape sequence '\.'
  lora_pattern = 'faceid.plusv2.sdxl.lora\.safetensors$'
D:\COMFYUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py:3042: SyntaxWarning: invalid escape sequence '\.'
  pattern = 'faceid.plusv2.sd15\.(safetensors|bin)$'
D:\COMFYUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py:3043: SyntaxWarning: invalid escape sequence '\.'
  lora_pattern = 'faceid.plusv2.sd15.lora\.safetensors$'
D:\COMFYUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py:3060: SyntaxWarning: invalid escape sequence '\.'
  lora_pattern = 'faceid.sdxl.lora\.safetensors$'
D:\COMFYUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py:3062: SyntaxWarning: invalid escape sequence '\.'
  lora_pattern = 'faceid.sd15.lora\.safetensors$'
D:\COMFYUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py:3064: SyntaxWarning: invalid escape sequence '\.'
  lora_pattern = 'faceid.plus.sd15.lora\.safetensors$'
D:\COMFYUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py:3066: SyntaxWarning: invalid escape sequence '\.'
  lora_pattern = 'faceid.plusv2.sdxl.lora\.safetensors$'
D:\COMFYUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py:3068: SyntaxWarning: invalid escape sequence '\.'
  lora_pattern = 'faceid.plusv2.sd15.lora\.safetensors$'
D:\COMFYUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py:5706: SyntaxWarning: invalid escape sequence '\.'
  pattern = 'brushnet.random.mask.sdxl.*\.(safetensors|bin)$'
D:\COMFYUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py:5708: SyntaxWarning: invalid escape sequence '\.'
  pattern = 'brushnet.random.mask.*\.(safetensors|bin)$'
D:\COMFYUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py:5712: SyntaxWarning: invalid escape sequence '\.'
  pattern = 'brushnet.segmentation.mask.sdxl.*\.(safetensors|bin)$'
D:\COMFYUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py:5714: SyntaxWarning: invalid escape sequence '\.'
  pattern = 'brushnet.segmentation.mask.*\.(safetensors|bin)$'
D:\COMFYUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\libs\wildcards.py:171: SyntaxWarning: invalid escape sequence '\+'
  subpattern = keyword.replace('*', '.*').replace('+','\+')
D:\COMFYUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\logic.py:1607: SyntaxWarning: invalid escape sequence '\o'
  if output_path.endswith("ComfyUI/output") or output_path.endswith("ComfyUI\output"):

**Comment by yolain** [comment]
This error looks like it's caused by a high version of python.

**Comment by S0LTIS** [comment]
I presume you mean latest version as in the node needs updating.

**Comment by yolain** [comment]
> I presume you mean latest version as in the node needs updating.

it seems to be a python==3.12 issue. We are generally using 3.10 or 3.11.

**Comment by S0LTIS** [comment]
Oh damn. miniconda installed python 3.12. Thanks for pointing this out. I've corrected the version, now I just need to test out the node. Will be back tomorrow with my results!

**Comment by S0LTIS** [comment]
Confirmed. Thank you for your time, God Bless.
