### ISSUE TITLE
feature request——希望增加一个getnode cached

### ISSUE THREAD

**Issue by whmc76** [yolain/ComfyUI-Easy-Use#42]
![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/129386342/0384297c-a6e4-4bab-8a22-fe077984c758)
komojini节点的这个读缓存在分组执行的时候很好用，可以把前置程序都给关掉跑并且不影响数据传递，期待大佬实装

**Comment by yolain** [comment]
之前研究过，没弄成功。不是非必要的功能，我先标注为无此计划了。
