### ISSUE TITLE
一使用'获取点'节点页面就卡死

### ISSUE THREAD

**Issue by jiushime** [yolain/ComfyUI-Easy-Use#44]
我只要添加获取点这个节点页面就会出现卡死，具体表现是：无法放大页面和拖动页面，也无法正常添加其它节点。只有重新刷新页面后立即删除获取点节点才能恢复正常，后台没看到报错，重新安装无用，换浏览器也无用。

**Comment by yolain** [comment]
没遇到过你这种情况，MAC系统和WIN都正常。 你看看使用其他的包的 getnode 看是否有这种情况。

**Comment by jiushime** [comment]
> 没遇到你这种情况，MAC系统和WIN都正常。你看看使用其他包的getnode看是否有这种情况。

你是说ComfyUI-extensions - diffus3这个吗，我试了他这个也不行，还有其他的包也有getnode吗？顺便说下我是win11系统，前天才开始使用easyuse的时候可以成功添加getnode没有卡，昨天开始只要添加getnode就会卡

**Comment by yolain** [comment]
> > 没遇到你这种情况，MAC系统和WIN都正常。你看看使用其他包的getnode看是否有这种情况。
> 
> 你是说ComfyUI-extensions - diffus3这个吗，我试了他这个也不行，还有其他的包也有getnode吗？顺便说下我是win11系统，前天才开始使用easyuse的时候可以成功添加getnode没有卡，昨天开始只要添加getnode就会卡

那就不太好判断是什么原因了。或许可能受其他包的影响了。简单的办法排查就是试试先把自定义节点包都复制到一个位置上，单独调用包含getSetNode的节点包（我这个或者diffus的），如果可以运行，在一个个包拉进来看是否是哪个包的兼容问题，如果一开始就不行 那就是可能是系统或者浏览器配置的原因了。

**Comment by jiushime** [comment]
> > > 没遇到你这种情况，MAC系统和WIN都正常。你看看使用其他包的getnode看是否有这种情况。
> > 
> > 
> > 你是说ComfyUI-extensions - diffus3这个吗，我试了他这个也不行，还有其他的包也有getnode吗？顺便说下我是win11系统，前天才开始使用easyuse的时候可以成功添加getnode没有卡，昨天开始只要添加getnode就会卡
> 
> 那就不太好判断是什么原因了。或许可能受其他包的影响了。简单的办法排查就是试试先把自定义节点包都复制到一个位置上，单独调用包含getSetNode的节点包（我这个或者diffus的），如果可以运行，在一个个包拉进来看是否是哪个包的兼容问题，如果一开始就不行 那就是可能是系统或者浏览器配置的原因了。

经过这几天的尝试我总算找到问题所在了，原因是我用的秋叶启动器里的一项设置导致的，就这个‘启动云端页面汉化’功能，只要打开它就会卡死，关了之后总算恢复正常了。
![Snipaste_2024-01-30_13-25-17](https://github.com/yolain/ComfyUI-Easy-Use/assets/103830876/605c9382-d496-4267-9371-d13c140cdb68)
