### ISSUE TITLE
当使用插件通过comfyui的api调用easyuse搭建的工作流会报错

### ISSUE THREAD

**Issue by wujm424606** [yolain/ComfyUI-Easy-Use#45]
具体描述如下：我下载https://github.com/AbdullahAlfaraj/Comfy-Photoshop-SD 节点，试图通过这个插件在ps中调用工作流api去生成图像，工作流是单纯使用easyuse搭建的，具体如下图
![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/38379474/78a11796-9720-418d-91ab-846782851dd4)
当在ps界面点击生成按钮，调用该工作流会在控制台报告如下错误，请问能看下是什么原因导致的吗？
![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/38379474/8341fd81-2bb1-42bd-bf4e-981544bbc990)
![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/38379474/1bcc001d-aa2d-4eb6-bcf7-05c80a68486f)

**Comment by yolain** [comment]
等我下个提交修复一下

**Comment by yolain** [comment]
已修复
