### ISSUE TITLE
Conditioning for XL models.

### ISSUE THREAD

**Issue by OleGrim** [yolain/ComfyUI-Easy-Use#46]
Not correct conditioning for XL models.
![Test_EU_bad](https://github.com/yolain/ComfyUI-Easy-Use/assets/75989890/6a79b102-2859-4a0e-9a6a-f48539e4831f)

**Comment by yolain** [comment]
Because XL models use ClipTextEncodeSDXL not ClipTextEncode

**Comment by OleGrim** [comment]
Your all Loaders use ClipTextEncode, and the "CLIP Text Encoder (Prompt)" node uses both ClipTextEncode and ClipTextEncodeSDXL, is that correct?

**Comment by yolain** [comment]
You've got that backwards.  All loaders in this package will choose whether to encode via ClipTextEncodeSDXL or ClipTextEncode, depending on whether they are xl models or not.  The "CLIP Text Encoder (Prompt)" node uses only ClipTextEncode.

**Comment by OleGrim** [comment]
I would like to repeat the generation result on other nodes, but...
![Test_EU-XL_v 7 0](https://github.com/yolain/ComfyUI-Easy-Use/assets/75989890/83dc89a3-f49f-43cd-8a90-243854944670)

**Comment by yolain** [comment]
The CLIP Set Last Layer node is missing from the original process.

**Comment by yolain** [comment]
> I would like to repeat the generation result on other nodes, but... ![Test_EU-XL_v 7 0](https://private-user-images.githubusercontent.com/75989890/301910169-83dc89a3-f49f-43cd-8a90-243854944670.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4OTY3NDUsIm5iZiI6MTcwNjg5NjQ0NSwicGF0aCI6Ii83NTk4OTg5MC8zMDE5MTAxNjktODNkYzg5YTMtZjQ5Zi00M2NkLThhOTAtMjQzODU0OTQ0NjcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDE3NTQwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4MjJiYjg2Zjc0ZDQzYTE0N2JkYmFjYmQ3MjMxNzU2NzkyYTllNjU4ZmQ1YTcxZjcwNTkyN2M5OWZmYjc0MTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A4SDXLTSkDAKvIXcLHcRMIaMvewu0rq28x81wMguVcc)

Excuse Me, can you tell me what is the name of the custom nodes that outputs the source?

**Comment by yolain** [comment]
![屏幕截图 2024-02-03 023139](https://github.com/yolain/ComfyUI-Easy-Use/assets/73304135/79195491-b160-46d8-81b7-7ce812c8821d)

**Comment by OleGrim** [comment]
Thanks for the example. I noticed a flaw in my second example. Adding clip layer -1 repeats the main result of the generation.
But the “clip” output of the “Pipe Out” node produces without -1 and it is necessary to add the “clip layer -1” node.
![Test_EU_god](https://github.com/yolain/ComfyUI-Easy-Use/assets/75989890/3d111461-5154-444d-9256-1b66460b5bd9)

**Comment by OleGrim** [comment]
> Excuse Me, can you tell me what is the name of the custom nodes that outputs the source?
These are the nodes in the initial installation ComfyUI: CLIPTextEncode and CLIPTextEncodeSDXL.

**Comment by yolain** [comment]
😂 I'm sorry. maybe i didn't phrase it right. What I want to know is the name of this node![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/73304135/a69aff6f-10e3-4561-b361-4032301ff82d)

**Comment by OleGrim** [comment]
Excuse me, I misunderstood this.
_Node_; Display Any (rgthree)
_Custom nodes_;: [rgthree's ComfyUI Nodes](https://github.com/rgthree/rgthree-comfy)
In the Manager: ID 153.

**Comment by yolain** [comment]
> Excuse me, I misunderstood this.
> 
> _Node_; Display Any (rgthree)
> 
> _Custom node_;: [rgthree's ComfyUI Nodes](https://github.com/rgthree/rgthree-comfy)
> 
> In the Manager: ID 153.

thx

**Comment by OleGrim** [comment]
![Test_EU_good-3ed](https://github.com/yolain/ComfyUI-Easy-Use/assets/75989890/c20f1a42-05b2-415e-b98b-9005b84fc12c)
