### ISSUE TITLE
请问是否能够做一些可以手动释放模型显存的节点？

### ISSUE THREAD

**Issue by wujm424606** [yolain/ComfyUI-Easy-Use#47]
因为有一些模型加载后会一直在显存里面，请问有什么办法去除掉这些模型占用的显存，手动实现更合理的显存分配，比如图片分割模型，controlnet模型，ipadpater模型，svd模型等

**Comment by yolain** [comment]
目前是没有想到有啥办法呢，这个可能需要comfyui官方去实现。
