### ISSUE TITLE
wildcard节点输出的tag无法预览

### ISSUE THREAD

**Issue by xin-r** [yolain/ComfyUI-Easy-Use#48]
如题，目前只有在使用easy use加载器的时候能显示抽到的tag，使用其他加载器或者直接连show text都无法正常显示，使用中还是不便，希望能直接输出文本到whow text中

**Comment by yolain** [comment]
993a51df153a3b7121cdfacca9bf44302232b29e
![屏幕截图 2024-02-07 015944](https://github.com/yolain/ComfyUI-Easy-Use/assets/73304135/5a101317-e4e8-40e4-aeec-284ebb8985c1)

**Comment by yolain** [comment]
这个只能满足wildcard的，lora还是需要走ez 的加载器才可以

**Comment by xin-r** [comment]
用上了，很好
