### ISSUE TITLE
关于运行时间的小建议

### ISSUE THREAD

**Issue by 807502278** [yolain/ComfyUI-Easy-Use#486]
大佬你好，有这个时间后面显示显存的太好了
我有个小建议：上一次运行的节点时间可不可以不清除掉？而是改用灰色显示？
因为运行一次后，那些已经从来结果的节点上的时间就看不到了
![image](https://github.com/user-attachments/assets/d4fb7170-5cf1-45bc-9d42-aa4b58b416af)

**Comment by yolain** [comment]
这应该是其他节点的

**Comment by 807502278** [comment]
啊这.....这就尴尬了，打扰了
