### ISSUE TITLE
xyplot sr  出错

### ISSUE THREAD

**Issue by lanwasss** [yolain/ComfyUI-Easy-Use#49]

**Comment by yolain** [comment]
XYPLOT需要再presampling 之后

**Comment by lanwasss** [comment]
> XYPLOT需要再presampling 之后
谢谢及时回答，刚刚试了，之后也会这样出错。

**Comment by yolain** [comment]
我修复下。之前更新的时候变动到了。

**Comment by lanwasss** [comment]
谢谢

**Comment by lanwasss** [comment]
我是想用xyplot sr来测试lora,不知道是不是使用不正确

**Comment by yolain** [comment]
> 我是想用xyplot sr来测试lora,不知道是不是使用不正确

sr 测提示词的。 xyplot advanced 还没有lora的，简易的有，xyinputs 的 lora年后会补齐。

**Comment by yolain** [comment]
15d13bc370adb34ace804f21b8a7aebf52be6de4 Fixed

**Comment by lanwasss** [comment]
需要更新一下插件就可以吗

**Comment by lanwasss** [comment]
thx

**Comment by lanwasss** [comment]
thx,解决了
