### ISSUE TITLE
请问这个pipe编辑是什么问题？

### ISSUE THREAD

**Issue by cardenluo** [yolain/ComfyUI-Easy-Use#494]
![image](https://github.com/user-attachments/assets/ef14d1a2-b425-4044-85a1-7c8cbddd515c)
是SD3.5的CLIP还不支持Pipe传递吗？

**Comment by yolain** [comment]
clip_skip 设为0

**Comment by cardenluo** [comment]
果然可以，感谢大佬

**Comment by cardenluo** [comment]
更新后，sd3.5和flux都不用设置clip了，但是xl用不了了。
![image](https://github.com/user-attachments/assets/2cda588c-1898-44b9-8388-4e2005c1b5b9)

**Comment by yolain** [comment]
> 更新后，sd3.5和flux都不用设置clip了，但是xl用不了了。 ![image](https://private-user-images.githubusercontent.com/133877069/380497319-2cda588c-1898-44b9-8388-4e2005c1b5b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwMzM4ODQsIm5iZiI6MTczMDAzMzU4NCwicGF0aCI6Ii8xMzM4NzcwNjkvMzgwNDk3MzE5LTJjZGE1ODhjLTE4OTgtNDRiOS04Mzg4LTRlMjAwNWMxYjViOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyN1QxMjUzMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNmMzOGU5MGRiM2FhMTRkYTA1ZmNlZmFmNTM5OTMzNjY3NDVhMDE3NzdlNjBhZWJkZDg5OWVmMTYwMDhkMTljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JyvoHoeSa0n4CemnMWPKmZLGVjHNqiyEYKoyM9cqZmo)

我修复下
