### ISSUE TITLE
使用嵌套for循环时出现 invalid literal for int() with base 10: '11.0.0.3.0.0.78'

### ISSUE THREAD

**Issue by void-Man** [yolain/ComfyUI-Easy-Use#496]
报错信息：
`!!! Exception during processing !!! invalid literal for int() with base 10: '11.0.0.3.0.0.78'
Traceback (most recent call last):
  File "D:\Program\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\Program\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\Program\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\Program\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "D:\Program\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\logic.py", line 842, in for_loop_end
    start_node = next((x for x in all_nodes if x['id'] == int(while_open)), None)
  File "D:\Program\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\logic.py", line 842, in <genexpr>
    start_node = next((x for x in all_nodes if x['id'] == int(while_open)), None)
ValueError: invalid literal for int() with base 10: '11.0.0.3.0.0.78'`

工作流如下：
[双层循环工作流测试.json](https://github.com/user-attachments/files/17553940/default.json)

**Comment by yolain** [comment]
试了下 双层嵌套 会无限循环。

**Comment by void-Man** [comment]
> 试了下 双层嵌套 会无限循环。

感谢大佬回复！意思是说这个报错是由于我的工作流有问题导致的？而不是双层循环嵌套导致的？

**Comment by yolain** [comment]
> > 试了下 双层嵌套 会无限循环。
> 
> 
> 
> 感谢大佬回复！意思是说这个报错是由于我的工作流有问题导致的？而不是双层循环嵌套导致的？

不是，是节点id获取问题 获取正确的话会无限循环。目前做不了双层嵌套

**Comment by void-Man** [comment]
> > > 试了下 双层嵌套 会无限循环。
> > 
> > 
> > 感谢大佬回复！意思是说这个报错是由于我的工作流有问题导致的？而不是双层循环嵌套导致的？
> 
> 不是，是节点id获取问题 获取正确的话会无限循环。目前做不了双层嵌套

好的好的，感谢大佬的解答

**Comment by yolain** [comment]
b75a247435a79f89fd5a9635ddfc273730867925 我在新的commit中支持了嵌套 不会无限循环了。不过感觉你发的这个流程没有按设想的执行，如果你有时间的话调整下再测试看看。

**Comment by void-Man** [comment]
> [b75a247](https://github.com/yolain/ComfyUI-Easy-Use/commit/b75a247435a79f89fd5a9635ddfc273730867925) 我在新的commit中支持了嵌套 不会无限循环了。不过感觉你发的这个流程没有按设想的执行，如果你有时间的话调整下再测试看看。

好的，感谢大佬的回复，我再试试看

**Comment by void-Man** [comment]
大佬，我试了下确实没问题了，那我关了这个issue了哈
