### ISSUE TITLE
Implement reuse of end nodes in the loop body

### ISSUE THREAD

**Issue by Shyryp** [yolain/ComfyUI-Easy-Use#514]
At the moment, when the "For Loop" cycle is running in ComfyUI, the end nodes (i.e. those nodes that have no further use in the cycle due to their missing connection to the For Loop End) are not reused in subsequent cycles after the first cycle. For example, Preview Image is used only in the first stage of the cycle (for example, when index = 0), but not in the second cycle (index = 1, 2, 3...).

It would be nice to see either a fix for this, or additional functionality (variable) in For Loop that would allow setting such behavior for the cycle, so that it would be possible to reuse end nodes in the body of the cycle.

**Comment by yolain** [comment]
You need to use nodes in the loop where non-output_node is true. 
For example, if you want to preview an image in a loop body you need to use the preview bridge from ComfyUI-Impack-Pack

**Comment by Shyryp** [comment]
@guill, is this really a problem of Core ComfyUI and Execution Model Inversion? Is there any possibility to set re-run of leaf nodes in Execution Model Inversion? Or does this require serious modification of Core ComfyUI?

**Comment by yolain** [comment]
> @guill, I remember you said that [this feature is "built" into Execution Model Inversion](https://github.com/comfyanonymous/ComfyUI/issues/4647), but not into the private For Loop implementation of your nodes in [this repository execution-inversion-demo-comfyui](https://github.com/BadCafeCode/execution-inversion-demo-comfyui). So is it really possible to implement this with the current Core ComfyUI functionality or not?
> 
> Thanks for info!

I found the solution, thanks for finding [guill](https://github.com/guill) 's previous reply, it was his answers that woke me up. I always thought it was the ComfyUI execution logic that had to be the cause, and it seems I was wrong.

**Comment by yolain** [comment]
It still seems a bit difficult to implement only on the second loop. The node ID changes at the beginning of the third time.
Need some time to work on it and see.

**Comment by Shyryp** [comment]
I tested the loops after commit [1be8fa5](https://github.com/yolain/ComfyUI-Easy-Use/commit/1be8fa596c65c2ce89c15b46223cc77644a087b2)
 
 Everything works fine, no issues so far, thanks for improving the loops! Now leaf nodes are reused!
 
 I think we can close this Issue.

**Comment by yolain** [comment]
I forgot to clear the commit number when committing and incorrectly associated the commit to this issue. It should point to #517.
