### ISSUE TITLE
xyplot

### ISSUE THREAD

**Issue by lanwasss** [yolain/ComfyUI-Easy-Use#52]
还是s/r 的问题，比方说prompt:1girl,<lora,xxxx:1.0>
 替换1girl就可以，替换lora里面的xxx没效果，1.0也没效果。

**Comment by yolain** [comment]
s/r 这边没有做提示词 wildcard 和 lora的判定，下个版本看下，如果可以的话我修复下。

**Comment by yolain** [comment]
prompt里的Lora在加载器时已经被读取了，无法参与后续xyplot，s/r这边读到的提示词都是去除掉lora和wildcards填充后的。 Xyplot如需要Lora对比，需要使用最新版本的 XYInput: Lora。
