### ISSUE TITLE
编号切换不够用

### ISSUE THREAD

**Issue by cardenluo** [yolain/ComfyUI-Easy-Use#521]
![image](https://github.com/user-attachments/assets/d094bd76-fadb-40fe-b5a9-91adba051841)
这个编号切换最多只能10个，循环任务不够用，能不限制或者加多几倍？

**Comment by yolain** [comment]
我感觉这个不需要用到编号切换呢。用promptline换行写文件名，然后转select index 成 input 用一个int当选择项
你这个表情姿势整理过吧，感觉不错样子，能不能发我一份。

**Comment by cardenluo** [comment]
是个好办法。
拿不出手，没有细调，仰头值拉最小，俯视值拉最大， 都是最大、最小，测试最大化效果

**Comment by cardenluo** [comment]
这个编号做流程切换蛮好用的，但是流程用不了promptline的文件名

**Comment by yolain** [comment]
> 这个编号做流程切换蛮好用的，但是流程用不了promptline的文件名

<img width="691" alt="截屏2024-11-10 12 30 09" src="https://github.com/user-attachments/assets/c4ca5073-7e47-44f6-8d78-70d12961e5a1">
