### ISSUE TITLE
Get节点和Set节点会随着相邻节点移动，影响操作

### ISSUE THREAD

**Issue by 2515448788** [yolain/ComfyUI-Easy-Use#526]
![942C5E4FE4D015FB2E1B1140D7CED9CF](https://github.com/user-attachments/assets/c5148a2d-a8c3-432a-8250-17cf7702abd7)
比如我移动节点束输出，BasePipe就会跟着一起动，相当影响使用，希望修复

**Comment by yolain** [comment]
这是故意这么做的，这样体验会好很多。当然，你也可以在设置中关闭掉父节点绑定。

**Comment by LiJT** [comment]
> 这是故意这么做的，这样体验会好很多。当然，你也可以在设置中关闭掉父节点绑定。

我也觉得这个做特别好，千万别改回去哈哈，我之前以为comfy自带能有这种功能，结果找了半天都没有
