### ISSUE TITLE
postive和negative的提示词节点无法实现提示词在画面上的分块控制

### ISSUE THREAD

**Issue by wujm424606** [yolain/ComfyUI-Easy-Use#53]
![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/38379474/4b61a3fc-7b43-4931-aef4-f6c1102c7bf8)
positive 和 negative节点无法实现上述效果，具体想要实现效果参考b站链接https://www.bilibili.com/video/BV1fK411a7sj/?spm_id_from=333.999.0.0&vd_source=656b1cb22cd2d7376847ef877c9afc81

**Comment by yolain** [comment]
类似这样呢。或者你用原始的也行。
<img width="1455" alt="1" src="https://github.com/yolain/ComfyUI-Easy-Use/assets/73304135/d5a2d807-7fac-4269-8538-ee3d71e5d45a">

**Comment by wujm424606** [comment]
> 类似这样呢。或者你用原始的也行。 <img alt="1" width="1455" src="https://private-user-images.githubusercontent.com/73304135/303970623-d5a2d807-7fac-4269-8538-ee3d71e5d45a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NDE4NTIsIm5iZiI6MTcwNzc0MTU1MiwicGF0aCI6Ii83MzMwNDEzNS8zMDM5NzA2MjMtZDVhMmQ4MDctN2ZhYy00MjY5LTg1MzgtZWUzZDcxZTVkNDVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDEyMzkxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0NTgxYWJiNzEwNWI4MTcyMTczZGZjZGMyMDNiNGIyMGY4YzNlNzgxMTA0MzAzZTY5MzNjMGI3ZWQ2MmQ5NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Tm2d8NOLcqHKUyc315k8fCy03f8j0ItgftE-7yBSiBw">

好的，谢谢
