### ISSUE TITLE
请问可以举一下LatentNoisy和LatentCompositeMaskedWithCond的使用例子吗？

### ISSUE THREAD

**Issue by wujm424606** [yolain/ComfyUI-Easy-Use#54]
![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/38379474/1bb564cf-fac8-4709-a051-b32101f73adf)
如果有工作流是最好的，这两个节点我没有搞清楚如何使用它们在自己的工作流中？希望作者有时间的情况下能解答一下

**Comment by yolain** [comment]
https://openart.ai/workflows/yolain/easy-facial-expression-variations/UMT4MEP0UuG5z4TGiUjm

**Comment by wujm424606** [comment]
> https://openart.ai/workflows/yolain/easy-facial-expression-variations/UMT4MEP0UuG5z4TGiUjm

好的，谢谢
