### ISSUE TITLE
关于for循环文生图

### ISSUE THREAD

**Issue by luckypigge1987** [yolain/ComfyUI-Easy-Use#540]
我在用for循环文生图，目前的工作流是所有图片输出后，在for循环结束的输出值1进行保存，但是经常爆内存……
能否使用save image（lazy）在工作流中进行保存？如果这样设置，那么for循环结束的节点，输出值1应该怎样连接？
![WX20241122-020119@2x](https://github.com/user-attachments/assets/d88a61ee-3d8e-43f1-ba0b-496d062e095b)

**Comment by yolain** [comment]
最新的不用lazy也可以了。最后接个showany或者清除显存的什么终止就行了
