### ISSUE TITLE
每次换个模型提示词栏大小自动重置

### ISSUE THREAD

**Issue by zmwv823** [yolain/ComfyUI-Easy-Use#55]
![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/13308350/9ce0f5af-422a-4499-8b43-856abacc92a6)
用来做图片重绘、放大等其他流程
不得已，只好拉出来做输入。
是否可以更改下逻辑，切换模型不重置大小。

**Comment by yolain** [comment]
下个版本更新的时候修复下

**Comment by yolain** [comment]
已修复
