### ISSUE TITLE
Flux Ipadapter is not working

### ISSUE THREAD

**Issue by nux1111** [yolain/ComfyUI-Easy-Use#553]
There are no errors to report with this but there is no influence of flux ipadapter in generations.

**Comment by yolain** [comment]
The ipadapter is working fine in my environment and I'm not quite sure what's causing it. Some users have given feedback that they get errors about tensors running on two devices, and I've referenced the source repository to make the corresponding changes.

**Comment by yolain** [comment]
I suspect it has something to do with the torch version or the configuration of the launcher.

**Comment by nux1111** [comment]
@yolain thanks for the response. It's quite strange. In my case, there is no effect at all.

**Comment by nux1111** [comment]
it works now for some reason. cheers!!
