### ISSUE TITLE
New issue: IndexError: tuple index out of range

### ISSUE THREAD

**Issue by wujm424606** [yolain/ComfyUI-Easy-Use#56]
![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/38379474/c1d40118-7e6e-4b89-aa6c-80352bfd0eb6)
当加载模型生成一次图片后，修改提示词再次生成图片时会爆出如下错误
![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/38379474/92f11214-6318-4db0-9381-e945c5ea9535)

**Comment by yolain** [comment]
28cef4c6468e2a30d0f6f0811f5fa8cb60a7da4a  Fixed
