### ISSUE TITLE
While Loop Start 节点输出的变量类型不被其他任意节点接受

### ISSUE THREAD

**Issue by zyd232** [yolain/ComfyUI-Easy-Use#567]
easy use 版本日期：12-02

问题描述：
比如，我将一个 int 值输入至 While Loop Start 节点的 initial_value1 入口，然后将 While Loop Start 节点的 value1 出口 连接至 easy mathInt 节点的 a 入口，就会报错：
`Return type mismatch between linked nodes: a, received_type(FLOW_CONTROL) mismatch input_type(INT)`

估计也是由于这个原因，While Loop End 节点输出的值也不被其他任意节点接受。

以往都是正常运行的，同样的工作流，就最近版本才出现的问题——现在 While Loop Start 节点输出的任意值，连接到任意节点，都不被其他节点接受。

**Comment by yolain** [comment]
你连错了应该。

**Comment by zyd232** [comment]
> 你连错了应该。
> 
> <img alt="截屏2024-12-04 16 05 43" width="1617" src="https://private-user-images.githubusercontent.com/73304135/392280677-1694a707-3de7-4a36-b4c9-f65bac95cea4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzOTE3OTAsIm5iZiI6MTczMzM5MTQ5MCwicGF0aCI6Ii83MzMwNDEzNS8zOTIyODA2NzctMTY5NGE3MDctM2RlNy00YTM2LWI0YzktZjY1YmFjOTVjZWE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDA5MzgxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjODhhZjViYThlMGU2NDAwZmU0NzJiZDEyNGU1YTc3MzIxZTQyYmViNDhmM2U1YTg2Y2U2ZDYyMjMxMTAwZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DeravqSIFZt_aTvTmFXb_Dzz7426V3q8219qP1psM9Q">

看起来是ComfyUI更新导致的问题，相关issue：[https://github.com/comfyanonymous/ComfyUI/issues/5884](url)
