### ISSUE TITLE
fooocus_styles ...

### ISSUE THREAD

**Issue by Torcelllo** [yolain/ComfyUI-Easy-Use#58]
... shows nothing! What am I missing? Should I have installed fooocus at all?

![Select Styles Error](https://github.com/yolain/ComfyUI-Easy-Use/assets/114806454/c9de2f66-2210-4e1c-859f-bf70866cbd20)

**Comment by yolain** [comment]
Is the "fooocus_styles.json" file in this directory?   (/custom_nodes/ComfyUI-Easy-Use/resources)
<img width="549" alt="screenshot" src="https://github.com/yolain/ComfyUI-Easy-Use/assets/73304135/5c98f182-ec0b-4166-b830-adfe7a710f59">

**Comment by yolain** [comment]
Does not require fooocus to be installed. It's just some combination of prompts.
