### ISSUE TITLE
cascade节点跑不通

### ISSUE THREAD

**Issue by joshua76y** [yolain/ComfyUI-Easy-Use#59]
<img width="1434" alt="capture" src="https://github.com/yolain/ComfyUI-Easy-Use/assets/42955367/02c11b2c-8f6a-44c1-8f09-27ae20527393">
如范例所示添加节点并选取模型后，跑到第二次sample后出错，用的是最近的更新后的4个cascade节点

**Comment by joshua76y** [comment]
更换旧easyksampler节点且无论有否选择presample里面的vae编解码都能出图

**Comment by yolain** [comment]
节点不对 cascade的preSampling和ksampler 是full分化出来的两个节点是处理c阶段的 b和a阶段还是原来的节点。看我readme那边的工作流示例

**Comment by yolain** [comment]
新的节点在工作流里只需要 cascadeloader+fullCascade 或者cascadeloader+两个分离出来的
