### ISSUE TITLE
是否可以写一个模型权重相加xyplot的节点

### ISSUE THREAD

**Issue by xueqing0622** [yolain/ComfyUI-Easy-Use#6]
我想更好的融合一些大模型, 在这个大神的lora上得到启发
https://www.youtube.com/watch?v=X9v0xQrInn8&ab_channel=Dr.Lt.Data%27sComfyUIExtension

我也跟他提了, 可是他太忙了,我提了两嘴,后面也懒得提了, 不用管合并模型,你有空可以看看
https://githubfast.com/ltdrdata/ComfyUI-Inspire-Pack/issues/26

我只是觉得合并模型很有用, 瞎搞乱填数值,还不如像lora一样,出一些xyplot的图, 很快就确定自己需要的block合起来就完美了

**Comment by yolain** [comment]
9041a21edd39b249e6020971b0abb1a717522cbf
