### ISSUE TITLE
1.0.7版本-组建加载不正常，部分组件无法找到

### ISSUE THREAD

**Issue by toddtail** [yolain/ComfyUI-Easy-Use#60]
## 运行时加载的custom nodes: 
```
ComfyUI/custom_nodes/ComfyUI-Custom-Scripts
ComfyUI/custom_nodes/rgthree-comfy
ComfyUI/custom_nodes/ComfyUI-Easy-Use
ComfyUI/custom_nodes/AIGODLIKE-ComfyUI-Translation
ComfyUI/custom_nodes/ComfyUI-Manager
ComfyUI/custom_nodes/ComfyUI-Inspire-Pack
ComfyUI/custom_nodes/ComfyUI_tinyterraNodes
ComfyUI/custom_nodes/ComfyUI_Comfyroll_CustomNodes
```

## 问题描述:
导入了该[视频](https://www.youtube.com/watch?v=siJKRX5D31w)下提供的json模板，出现错误提示如下：

> When loading the graph, the following node types were not found:
> easy stylesSelector

![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/18119423/2e8db3f1-5c84-4c2c-acf0-480dbb322eae)

经过排查，发现节点菜单中确实缺少部分组件，包括上述 stylesSelector、cascadeLoader、Logic 子菜单等，且在搜索中也无法找到。

![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/18119423/ec203da9-499a-4ef2-bd7c-68630590e2d2)

![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/18119423/b669c4bb-09c9-4205-a262-50d1996faf12)

希望大佬协助排错，感谢！

**Comment by yolain** [comment]
啊？你确定有更新到最新的。 运行的时候命令行会显示EasyUse的版本号。。有没有可能你之前不小心改动到文件 然后pull时候它其实并没有更新成功。  如果是1.0.7的话 可能要看运行时 有何报错了。 1.0.7 这些节点都是正常显示的。

**Comment by wujm424606** [comment]
我的1.0.7的版本也是正常的，应该是提问者没有更新到最新版本吧
