### ISSUE TITLE
Case sensitive for search

### ISSUE THREAD

**Issue by Pauweltje** [yolain/ComfyUI-Easy-Use#62]
"Fooocus Styles" Hi, when searching for e.g. porcelain, I had to type Po, with caps for the P, lowercase does not give a result.
Thanks!

**Comment by yolain** [comment]
Thanks for the feedback, I'll tweak it for the next commit

**Comment by Pauweltje** [comment]
Thanks very much! Glad to hear! is it also possible to add own styles? So that I can choose it in the pull-down menu? Thanks!

**Comment by yolain** [comment]
Yes, you can find the easy-use custom node package folder and refer to the fooocus_styles.json file in the resources directory , and then create a new json file under styles folder to define your own cue word styles
![1](https://github.com/yolain/ComfyUI-Easy-Use/assets/73304135/9372f4ca-32e5-45c2-af74-032dda94021d)

**Comment by yolain** [comment]
By the way, this customized styles.json filename needs to contain _styles

**Comment by Pauweltje** [comment]
> By the way, the filename of this customized styles.json needs to contain _styles.

Thank you very much...I will try this! :D
