### ISSUE TITLE
EasySeed doesn't work well with batch_size

### ISSUE THREAD

**Issue by Delerium** [yolain/ComfyUI-Easy-Use#64]
EasySeed doesn't seem to iterate with batch size. 

Example: Comparing a batch size of 4 with a fixed seed to 4 individual batches incrementing by 1, only the first image matches with each. the 2nd, 3rd, and 4th don't match at all, which makes me think that the seed doesn't actually increment at all.

**Comment by Delerium** [comment]
never mind. I'm just going about this the wrong way.

**Comment by yolain** [comment]
The batch size corresponds to the "batch_idx" and not the seed increment. In other words, the batch generated images are all the same seed value, the difference is its index.

**Comment by Delerium** [comment]
curiously, is there a way to manually set this "batch_idx" in comfyUI without iterating through a full batch?

**Comment by yolain** [comment]
Yes, there is a way to do it, but it may require you to update the easyuse package. I just fixed the issue about this.
You need to output the latent and then connect the node 'Latent from batch'.
<img width="1254" alt="截屏2024-02-28 16 41 32" src="https://github.com/yolain/ComfyUI-Easy-Use/assets/73304135/e4c801f2-1209-4d1b-ab6f-db721161b09c">

**Comment by yolain** [comment]
i prefer xyplot, because it has a seed value 😃
