### ISSUE TITLE
既然你已经对LLLite下手, 有空看看这个

### ISSUE THREAD

**Issue by xueqing0622** [yolain/ComfyUI-Easy-Use#7]
既然你已经对LLLite下手, 有空看看这个
https://githubfast.com/kohya-ss/ControlNet-LLLite-ComfyUI/issues/7
希望你能改到支持

**Comment by xueqing0622** [comment]
这个等于说让kohya的XL的control net支持动画的变数和sdweb里面的prompt is more important

**Comment by yolain** [comment]
你有完整的工作流吗？没玩过这个，看不太明白流程。如果单纯是直接传入CONTROL_NET 进来 转换不了。

**Comment by xueqing0622** [comment]
就是加一个contronet的输入节点进来,这样就支持animateDiff基于图片的动画处理, 还有sdweb里面的Prompt is more important
![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/114840118/50f57493-c81c-4f22-8fd9-0295cbfc6eef)
可以看看接入contronet的输入节点的视频教程
https://www.bilibili.com/video/BV1zG41127KB     (animateDiff应用)
https://www.bilibili.com/video/BV1zp4y1A7Uz     (Prompt is more important的应用)

这是我的工作流, pipeout pipein 和pipeEdit各种接你的节点各种出错, 我就先不用 用ttn节点做的示例, 你先看看
[controlnet test1.json](https://github.com/yolain/ComfyUI-Easy-Use/files/13667143/controlnet.test1.json)
![ref img](https://github.com/yolain/ComfyUI-Easy-Use/assets/114840118/f62a11e4-828a-4e8f-9a8e-01c232f24dbf)

**Comment by xueqing0622** [comment]
更新了一下comfyui和所有其他插件,现在可以了
我用你的插件连了一个
[EasyUse Prompt is more important.json](https://github.com/yolain/ComfyUI-Easy-Use/files/13667343/EasyUse.Prompt.is.more.important.json)

**Comment by yolain** [comment]
等 ComfyUI-Advanced-ControlNet 那个包把LLLite适配出来吧，没太多时间研究那个转换，有点麻烦。然后普通的EasyControlnet我加上了control_net可选参数

**Comment by xueqing0622** [comment]
没事 把能弄的弄好先,   LLLite那个等作者自己搞也行, EasyControlnet 和EasyControlnet adv你也加一个control_net输入口就好了
