### ISSUE TITLE
更新3月4之后的版本会导致所有node失效

### ISSUE THREAD

**Issue by K-O-N-B** [yolain/ComfyUI-Easy-Use#76]
反复排错了很多次，只要更新3月4号之后的版本，打开comfyui就会全屏黑红色（所有node都失效），3月3日及之前的不会有这个问题

**Comment by K-O-N-B** [comment]
![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/152141077/4f75db72-613c-4fc4-99aa-af980e44d10d)
可用的版本

**Comment by K-O-N-B** [comment]
![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/152141077/21f5ca2c-6bf6-459b-90bd-12c6a8cccf0f)
更新后：
![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/152141077/39a525e9-70cb-4abf-ac04-90d8e32d3ac1)

**Comment by wujm424606** [comment]
我没有遇到你说的情况

**Comment by wujm424606** [comment]
![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/38379474/5d36f3c4-debd-4220-a791-e32cb14e2690)

**Comment by K-O-N-B** [comment]
我也搞不懂。。。。开始还以为是comfyui问题，搞了2天终于发现是这个node一更新就会导致整个comfyui所有node都失效

**Comment by yolain** [comment]
不会吧，我们都运行得正常，你有ComfyUI运行日志么，或者控制台报错 发我看下。谢谢！

**Comment by yolain** [comment]
没看出啥问题，你这是运行成功的？需要就是那个失败的呢。

**Comment by K-O-N-B** [comment]
> 没看出啥问题，你这是运行成功的？需要就是那个失败的呢。

上面的log就是运行失败的, 我在试一次，这是更新到最新版之后的启动log:
[Diagnostics-1709804632.log](https://github.com/yolain/ComfyUI-Easy-Use/files/14522129/Diagnostics-1709804632.log)


这是截图：
![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/152141077/577b6374-e741-4ef2-bf73-97a457b9902b)


退回3月4日版本之后的log:
[Diagnostics-1709804762.log](https://github.com/yolain/ComfyUI-Easy-Use/files/14522160/Diagnostics-1709804762.log)


截图：
![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/152141077/886cdd60-61da-4a63-958d-7902ca181e0f)

**Comment by yolain** [comment]
看不出来，奇了怪了，日志里都是加载成功。

**Comment by cardenluo** [comment]
> 看不出来，奇了怪了，日志里都是加载成功。

加载是成功的，但是和comfyui 0246有冲突，两个同时装，插件就会全部不可见，旧版本不会有这个问题。

**Comment by cardenluo** [comment]
> 我也搞不懂。。。。开始还以为是comfyui问题，搞了2天终于发现是这个node一更新就会导致整个comfyui所有node都失效

你是不是也装了comfyui 0246 ？

**Comment by K-O-N-B** [comment]
> > 我也搞不懂。。。。开始还以为是comfyui问题，搞了2天终于发现是这个node一更新就会导致整个comfyui所有node都失效
> 
> 你是不是也装了comfyui 0246 ？

确实是这个问题，我把0246删了之后就没有问题了

**Comment by yolain** [comment]
> > > 我也搞不懂。。。。开始还以为是comfyui问题，搞了2天终于发现是这个node一更新就会导致整个comfyui所有node都失效
> 
> > 
> 
> > 你是不是也装了comfyui 0246 ？
> 
> 
> 
> 确实是这个问题，我把0246删了之后就没有问题了

没用过秋叶包 😂0246 是啥包。 有包地址吗 我看看啥原因造成的

**Comment by K-O-N-B** [comment]
https://github.com/Trung0246/ComfyUI-0246

**Comment by yolain** [comment]
> https://github.com/Trung0246/ComfyUI-0246

👌看到了

**Comment by K-O-N-B** [comment]
作者解决了说一下啊哈~

**Comment by yolain** [comment]
> 作者解决了说一下啊哈~

那个包 判断不严谨，可能也是没想到有这种情况吧。我调整了下，可以了！
