### ISSUE TITLE
[Seek Comments 征求意见] Whether to remove the forced control_before_generate 是否去除强制运行前操作

### ISSUE THREAD

**Issue by yolain** [yolain/ComfyUI-Easy-Use#82]
Since `Widget Value Control Mode` could not be set in earlier versions of comfyui, `control_before_generate` was forced in easyuse.
However, after comfyui added `Widget Value Control Mode`, I realized that if I didn't force it, it still wasn't compatible with the cg-everywhere node package, so I kept the force setting.
My apologies for not paying attention to cg-everywhere, I didn't realize until recently that it doesn't affect `Widget Value Control Mode` when `highlight connected nodes` is turned off.
So, I'm actually considering whether I should remove the force setting control mode and revert back to what comfyui originally had.

由于在早期的版本中，comfyui不能设置`Widget Value Control Mode`，于是在easyuse中 强制设置了`control_before_generate`。
然而，comfyui 增加了`Widget Value Control Mode`之后，我发现如果我不force，它还是无法与 cg-everywhere 节点包无法兼容，所以一直保留了force的设置。
很抱歉，一直没关注到cg-everywhere，近期我才发现，当通过关闭`highlight connected nodes`功能的时候，它可以不影响到`widget value control mode`。
所以，我有在考虑是否应该去除强制设定control mode，并恢复到comfyui原本的状态。

**Comment by wujm424606** [comment]
我认为在comfyui已经添加了widget value control mode的情况下，为了让easyuse可以更好的和更多组件联合使用，使用兼容性更高，去除强制设定control mode，恢复成comfyui原有状态是一个好的选择

**Comment by yolain** [comment]
> 我认为在comfyui已经添加了widget value control mode的情况下，为了让easyuse可以更好的和更多组件联合使用，使用兼容性更高，去除强制设定control mode，恢复成comfyui原有状态是一个好的选择

是的，我主要担心的是变更会影响到一些用户可能已经习惯了这种设定，还有就是早期做的介绍视频有提到这块，改变之后新观看的人怕会造成误导。

**Comment by wujm424606** [comment]
> > 我认为在comfyui已经添加了widget value control mode的情况下，为了让easyuse可以更好的和更多组件联合使用，使用兼容性更高，去除强制设定control mode，恢复成comfyui原有状态是一个好的选择
> 
> 是的，我主要担心的是变更会影响到一些用户可能已经习惯了这种设定，还有就是早期做的介绍视频有提到强制设定了运行前操作，改变之后新观看的人怕会给造成误导，有些刚接触comfyui的可能并不知道control mode选项设置。这是我比较纠结的点😂

乱神可以尝试做一个新的基础教程视频，或者这周末如果有时间我也试着做一下乱神的easyuse的基础使用教学，让乱神这么好用的插件让更多人知道
