### ISSUE TITLE
diffusers节点弃用警报日志

### ISSUE THREAD

**Issue by zmwv823** [yolain/ComfyUI-Easy-Use#84]
- py310+torch220+cu118（diffusers==0.26.3）
- py311+torch220+cu121（diffusers==0.25.0）
会出现这个警告，排查确认不加载easy-use就没这个。
D:\AI\ComfyUI_windows_portable\python_embeded\lib\site-packages\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
Comfy-Easy-Use (v1.1.0): Loaded

**Comment by yolain** [comment]
你的diffusers版本不一致嘛

**Comment by yolain** [comment]
0.25.0是比较稳定的

**Comment by zmwv823** [comment]
> 你的diffusers版本不一致嘛

额，py311+cu121是官方包带的，后面因为一些兼容问题，自己重新做了py310+cu118的运行环境。
unet2d翻到前面的issue，自己改了代码后没警报了。
就剩这个torch.utils._pytree._register_pytree_node。
310+cu118降级0.25.0就报错找不到diffusers module。

**Comment by yolain** [comment]
> > 你的diffusers版本不一致嘛
> 
> 额，py311+cu121是官方包带的，后面因为一些兼容问题，自己重新做了py310+cu118的运行环境。 unet2d翻到前面的issue，自己改了代码后没警报了。 就剩这个torch.utils._pytree._register_pytree_node。 310+cu118降级0.25.0就报错找不到diffusers module。

应该是 0.26.3 需要更改版本的torch 才行。。 我现在没有3.10的环境呢，不好帮你排查。 你试试找找为啥降到0.25.0它会找不到呢。   如果你不需要用到ayerDiffuse的话 可以把 diffusers 这个包删了，它也不会影响使用。就是我在Log会多输出一个告知 你需要安装diffusers 的提示

**Comment by zmwv823** [comment]
> > > 你的diffusers版本不一致嘛
> > 
> > 
> > 额，py311+cu121是官方包带的，后面因为一些兼容问题，自己重新做了py310+cu118的运行环境。 unet2d翻到前面的issue，自己改了代码后没警报了。 就剩这个torch.utils._pytree._register_pytree_node。 310+cu118降级0.25.0就报错找不到diffusers module。
> 
> 应该是 0.26.3 需要更高版本的torch 才行。。 我现在没有3.10的环境呢，不好帮你排查。 你试试找找为啥降到0.25.0它会找不到呢。 如果你不需要用到ayerDiffuse的话 可以把 diffusers 这个包删了，它也不会影响使用。就是我在Log会多输出一个告知 你需要安装diffusers 的提示

好的，谢谢
