### ISSUE TITLE
3月16日版随机种类型为什么变成INT:SEED了?

### ISSUE THREAD

**Issue by xwxxwk** [yolain/ComfyUI-Easy-Use#86]
3月16日版随机种变成INT:SEED类型了,是有什么理由吗?现在我外接的种子生成器全不能用了.

**Comment by yolain** [comment]
得把seed_num也调回 seed才行， 等我更新一下吧。 为了调回原来comfyui的control_mode状态，不然怕新人会懵逼，现在设置里可以设置 control_before_generate了，这样就没必要强制运行前操作了。
