### ISSUE TITLE
我记起来了, 你可以把efficiency的 seed迁移进来 好用

### ISSUE THREAD

**Issue by xueqing0622** [yolain/ComfyUI-Easy-Use#9]
我记起来了, 你可以把efficiency的 seed迁移进来 好用
![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/114840118/c54df04a-1f10-4647-958b-297c06cbea4d)

一键切换 不会有各种种子问题, 是我觉得comfyui最好用的seed

**Comment by xueqing0622** [comment]
[efficiency_seed修改的地方.zip](https://github.com/yolain/ComfyUI-Easy-Use/files/13672722/efficiency_seed.zip)
我见你那个seed还是有点不完美,今天用gpt改了一个, zip文件是改的东西, 你拿去看能不能整合进去, 
![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/114840118/41cab101-f549-491c-ad27-77f748c0bb0e)

**Comment by yolain** [comment]
昨天整了半天，发现效率节点的种子生成有个问题的，存的值如果是-1的时候，这样保存了图再重新运行拖入或者发给他人，会不知道当前工作流这个节点的种子值是多少。 感觉还是得用原来我写的那个逻辑，我解决了选fixed还会生成一下的问题，但是解决不了从历史记录去读取 显示的是上一个生成值，comfy保存历史记录的prompt 在 生成之前，目前试了好几种方式还是没办法更改。

**Comment by xueqing0622** [comment]
哈哈 seed这么基础的功能 搞得我们都头大啦
对了 cg-use-everywhere跟efficiency的seed有冲突 有人报了 还没解决
https://githubfast.com/jags111/efficiency-nodes-comfyui/issues/38

**Comment by Philmar1986** [comment]
seed我用rgthree的那个seed, 没什么问题，图片发给别人，工作流也能直接显示该图片的seed。

**Comment by yolain** [comment]
> seed我用rgthree的那个seed, 没什么问题，图片发给别人，工作流也能直接显示该图片的seed。

rgthree 应该是 last_seed有存值，效率那个我试过是不行。没事，这边我已经搞定了，不想要那么多按钮，之前的版本的seed还是有点问题的，过两天就更新了。
