### ISSUE TITLE
Error occurred when executing easy controlnetLoader

### ISSUE THREAD

**Issue by cardenluo** [yolain/ComfyUI-Easy-Use#95]
![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/133877069/858e889a-847a-4c40-8b45-01f2cd95fbce)
缩放权重不支持 SDXL？

**Comment by yolain** [comment]
不开缩放权重是可以的吗？我前两天好像也走不通， 缩放权重跟ComfyUI-Advanced-ContolNet那个包有关的，你试试升级下那个包看下

**Comment by cardenluo** [comment]
更新了不行哦，权重1是可以的，比1小不行。
但是SD1.5可以用

**Comment by cardenluo** [comment]
找到原因了，使用XL-open不支持柔和权重，运行过后，再使用其它CN控制也会报错，只能重启
