### ISSUE TITLE
feature request - batch images input support of fooocus inpaint

### ISSUE THREAD

**Issue by whmc76** [yolain/ComfyUI-Easy-Use#96]
![image](https://github.com/yolain/ComfyUI-Easy-Use/assets/129386342/af6f94ab-7b44-41f4-aaad-5dc6f7c07fa7)

如果普通的inpaint是可以这样跑的，但是接上fooocus patch之后就不行了 希望能早日支持

**Comment by yolain** [comment]
原版的也做不了batch_size，我试着改写一下 也不行。 fooocus的源码也是一样。
