### ISSUE TITLE
关于"节点束编辑"遇到的问题.

### ISSUE THREAD

**Issue by xwxxwk** [yolain/ComfyUI-Easy-Use#97]
![workflow (1)](https://github.com/yolain/ComfyUI-Easy-Use/assets/129860605/85373b50-6a5b-4312-b3a2-31b6130766d4)

如图所示,在中断处报错:

ComfyUI_smZNodes\modules\prompt_parser.py", line 107, in collect_steps
    return sorted(set(res))
                  ^^^^^^^^
TypeError: unhashable type: 'list'

经测试仅当最右边预采样器steps为外部输入时会触发,而绿色标题流程运作正常.

**Comment by yolain** [comment]
之前试过，最前面开的a1111_prompt_style, pipeEdit那边就用不了 concat，average, timerange
